### ISSUE TITLE
Plantillas de cliente con tareas predefinidas

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#10]
A ver que os parece. Después de haber dado de alta unas 30 máquinas cliente, me he dado cuenta de que en muchas de ellas (básicamente en las GNU/Linux) copio las mismas carpetas (/etc , /root, /var/spool/cron, /usr/lib/ssl , .....), y generalmente les aplico las mismas políticas, excepciones, exclusiones, etc.

Para mi habría sido muy útil y me habría ahorrado mucho tiempo el tener una plantilla en la que definir que tareas son las que quiero crear, de forma que si la aplico cuando doy de alta un nuevo cliente, me cree auto-mágicamente todas esas tareas para ese cliente.

Otra opción parecida podría ser la de crear un cliente copiando la configuración de otro previamente creado, de forma que hiciera un calco de todas sus tareas. 

¿Qué os parece ?

Agur.

**Comment by xezpeleta** [comment]
Podríamos añadir un botón "Duplicar" en los clientes. Pendiente para cuando revisemos la botonera de acciones de la ventana principal.

**Comment by antton** [comment]
Hi, 

This is what I did for the next version.

I didn't finish yet but the internal functionality is almost ready!

https://www.youtube.com/watch?v=mTBnUW4mSP0
