### ISSUE TITLE
compatibility with ubuntu 12.04 precise

### ISSUE THREAD

**Issue by mason-xx** [elkarbackup/elkarbackup#105]
Not an issue, more like a feature request. I would love to see this compatible with 12.04 precise.
As stated on the mailing list, seems an issue with incompatible php versions.

**Comment by xezpeleta** [comment]
Hi @mason-xx , we have decided to not support old Linux distributions / PHP versions.

Anyway, I tested elkarbackup on Ubuntu Precise and it works well if you upgrade your PHP version to 5.4: http://www.pixelite.co.nz/article/upgrading-php-54-ubuntu-1204-lts-support-drupal-8/

After doing that, you should reinstall Elkarbackup again:

```
apt-get install --reinstall elkarbackup
```

Thanks
