### ISSUE TITLE
Copiar directorios de windows con espacios en su nombre [Solucionado]

### ISSUE THREAD

**Issue by csanchez8** [elkarbackup/elkarbackup#107]
Hola,
dejo esta información aquí por si le ocurre a otra persona.
Tengo una tarea la 2.3 que me copia una carpeta de un servidor windows que está en H:\Sage Data en la que tengo espacios en el nombre.
En la configuración del fichero rsync.conf en windows tenía la configuración
```
[SAGE]
path = /cygdrive/h/Sage Data
```
Y me daba el error
```
	Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.2_3.cfg" sync 2>&1 failed. Diagnostic information follows: @ERROR: chdir failed rsync error: error starting client-server protocol (code 5) at main.c(1653) [Receiver=3.1.1] ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -c /tmp/rsnapshot.2_3.cfg sync ---------------------------------------------------------------------------- ERROR: /usr/bin/rsync returned 5 while processing 192.168.10.3::SAGE
```
Según leí en http://stackoverflow.com/questions/6993355/cwrsync-failing-due-to-spaces-in-directory-names lo configuré de la forma
```
[SAGE]
path = /cygdrive/h/"Sage Data"
```
Pero seguí dando el mismo error.

Así que decidí hacerme un enlace duro del directorio de windows con el comando MKLINK y así poder tener un nombre de carpeta sin espacios
```
mklink /j h:\sage "h:\Sage Data"
```
De esta forma en el fichero rsync.conf dejo la configuración sin espacios y problema solucionado
```
[SAGE]
path = /cygdrive/h/sage
```

Seguro que hay alguna forma de poner correcto el path para nombres con espacios, pero bueno. Es una solución.

**Comment by antton** [comment]
+1

**Comment by xezpeleta** [comment]
Buena manera de solucionarlo! Otra cosa más para añadir en la documentación...

Por cierto, el culpable del error del espacio creo que es Rsnapshot, y no cwRsync. Aparentemente esto estaría resuelto en Rsnapshot 1.4. Más información:

https://github.com/elkarbackup/elkarbackup/wiki/FAQ#can-i-set-a-backup-path-with-whitespaces

Si alguien quiere probar la versión 1.4, le recomiendo que pruebe el paquete para Debian Testing, rsnaphshot 1.4.1-1 (que parece que va bastante bien):

https://packages.debian.org/testing/rsnapshot

**Comment by alfredobz** [comment]
++ 1 

----- Jatorrizko mezua -----

> +1

> El 30 de octubre de 2015, 13:20, Carlos <notifications@github.com>
> escribió:

> > Hola,
> > dejo esta información aquí por si le ocurre a otra persona..
> > Tengo una tarea la 2.3 que me copia una carpeta de un servidor
> > windows que
> > está en H:\Sage Data en la que tengo espacios en el nombre.
> > En la configuración del fichero rsync.conf en windows tenía la
> > configuración
> >
> > [SAGE]
> > path = /cygdrive/h/Sage Data
> >
> > Y me daba el error
> >
> > Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.2_3.cfg" sync 2>&1
> > failed. Diagnostic information follows: @ERROR: chdir failed rsync
> > error: error starting client-server protocol (code 5) at
> > main.c(1653) [Receiver=3.1.1]
> > ----------------------------------------------------------------------------
> > rsnapshot encountered an error! The program was invoked with these
> > options: /usr/bin/rsnapshot -c /tmp/rsnapshot.2_3.cfg sync
> > ----------------------------------------------------------------------------
> > ERROR: /usr/bin/rsync returned 5 while processing
> > 192.168.10.3::SAGE
> >
> > Según leí en
> > http://stackoverflow.com/questions/6993355/cwrsync-failing-due-to-spaces-in-directory-names
> > lo configuré de la forma
> >
> > [SAGE]
> > path = /cygdrive/h/"Sage Data"
> >
> > Pero seguí dando el mismo error.
> >
> > Así que decidí hacerme un enlace duro del directorio de windows con
> > el
> > comando MKLINK y así poder tener un nombre de carpeta sin espacios
> >
> > mklink /j h:\sage "h:\Sage Data"
> >
> > De esta forma en el fichero rsync.conf dejo la configuración sin
> > espacios
> > y problema solucionado
> >
> > [SAGE]
> > path = /cygdrive/h/sage
> >
> > Seguro que hay alguna forma de poner correcto el path para nombres
> > con
> > espacios, pero bueno. Es una solución.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/elkarbackup/elkarbackup/issues/107>.
> >

> —
> Reply to this email directly or view it on GitHub .

-- 

Alfredo Barrainkua Zallo 
IKT Arduraduna 
Iurreta LHII Ikastetxea 
Olaburu 19, 48215 IURRETA 
Tel: 944 66 88 00 - 510 
Fax: 946 20 28 28
