### ISSUE TITLE
Backup process for multiple servers not working 

### ISSUE THREAD

**Issue by vasukolli** [elkarbackup/elkarbackup#112]
Hello,

I have configured elkarbackup to backup directories in 8 remote servers.when i click run backup button manually for all servers backup process is going on correctly but when i configured through policy elkarbackup is failing to execute jobs, these failed jobs belongs to different servers each time.
Log Data:
returned 0.99609375 while processing...user@hostaddress:/backupdirectory
My policy configuration:
1) hourly backups : backup at every 4th hour
2)daily : backup at 2AM   each day
3) weekly: at sunday 3AM
4)monthly : at 1st of every month 4AM
..each configuration doesn't conflict with other.

This same policy used for all servers.

**Comment by xezpeleta** [comment]
Hi @vasukolli ,

Can you add more information about the error? Please add the content of your logfiles:

```
/var/log/elkarbackup/BnvLog.log
/var/log/elkarbackup/prod.log
```

Thanks

**Comment by vasukolli** [comment]
Hi @xezpeleta ,
I have attached BnvLog.log file, please find it .I didn't find prod.log file in the directory.

Error which i am getting through mail:
Client 	Job 	Time 	Level 	Message
23.227.163.206 	backup_dir1 	2015-11-29 13:02:10 	ERROR 	Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.1_1.cfg" sync 2>&1 failed. Diagnostic information follows: ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg sync ---------------------------------------------------------------------------- ERROR: /usr/bin/rsync returned 0.99609375 while processing greenbuds@<<ipaddress>>:/home/greenbuds/webcontent/
<<ipaddress>> 	backup_dir1 	2015-11-29 13:02:10 	ERROR 	Client "1", Job "1" error.
<<ipaddress>>  	backup_dir1 	2015-11-29 13:02:10 	ERROR 	FAIL
The ipaddress and jobid  differs each time i get status mail.

Thank You,
vasu.

[BnvLog.txt](https://github.com/elkarbackup/elkarbackup/files/46895/BnvLog.txt)

**Comment by xezpeleta** [comment]
Ok @vasukolli . I would say that error is related with RSnapshot:

**Comment by vasukolli** [comment]
Rsnapshot version Info:

 rsnapshot-1.4.1

**Comment by xezpeleta** [comment]
What Debian/Ubuntu version is it?

Please, try downgrading to Rsnapshot 1.3.1-6 and try again. The following workaround should work in both, Debian Jessie and Ubuntu Trusty distros:

```sh
# Download deb package
wget https://launchpad.net/ubuntu/+source/rsnapshot/1.3.1-6ubuntu1/+build/6750119/+files/rsnapshot_1.3.1-6ubuntu1_all.deb
# Installation
dpkg -i rsnapshot_1.3.1-6ubuntu1_all.deb
```

**Comment by vasukolli** [comment]
Hello,
Thanks for reply.

Also this error may be  due to loss of  connectivity with the remote server.I have tested this senario the following error has appeared in log file:
Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.1_1.cfg" sync 2>&1 failed. Diagnostic information follows: ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg sync ---------------------------------------------------------------------------- ERROR: /usr/bin/rsync returned 0.99609375 while processing greenbuds@ipaddress:/home/greenbuds/webcontent/

**Comment by xezpeleta** [comment]
> I need to know whether the status mails are sent once all jobs are done or after completing each job?please clarify regarding this. 

After completing each job

**Comment by xezpeleta** [comment]
@vasukolli you closed the issue, does it mean you fixed it?

**Comment by vasukolli** [comment]
yes, this error occurred due to loss of connection with remote system.
