### ISSUE TITLE
logger shows wrong message

### ISSUE THREAD

**Issue by adrianles** [elkarbackup/elkarbackup#114]
At [DefaultController::setParameter method](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Controller/DefaultController.php#L1235), the logger writes identical messages in the then part and the else part of an if statement. The [else part](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Controller/DefaultController.php#L1249) should be something like 'Parameter not set... '

But also (in both, then and else, cases) a wrong link is getting generated:
    ['link' => $this->generateUrl('showPolicies')](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Controller/DefaultController.php#L1247)
The setParameter function is only being called from the DefaultController by the [manageBackupsLocationAction](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Controller/DefaultController.php#L1077) and [manageParametersAction](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Controller/DefaultController.php#L1137) methods, so any
'link' => $this->generateUrl('manageBackupsLocation') or
'link' => $this->generateUrl('manageParameters') would be more appropriate.

* setParameter, even being public, is only called from the DefaultController

**Comment by xezpeleta** [comment]
Thanks, we'll fix that!

**Comment by elacunza** [comment]
We'll try to send PRs tomorrow with the fixes ;)

El 02/12/15 a las 17:56, Xabi escribió:
>
> Thanks, we'll fix that!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/114#issuecomment-161363332>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by xezpeleta** [comment]
Great! :+1:

**Comment by xezpeleta** [comment]
> The else part should be something like 'Parameter not set... '

@adrianles that message remains with no change on the proposed PR. Is it pending or do you finally decided not to change it?

Thanks!!

**Comment by adrianles** [comment]
It was a mistake, I think it's fixed now
