### ISSUE TITLE
New v1.2-Pre-Alpha2 doesn't work with PHP 5.3

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#119]
I'm testing the new v1.2 pre alpha deb package on Ubuntu Precise and I have the following error:

```sh
$ /usr/share/elkarbackup/app/console cache:warmup --env=prod
PHP Parse error:  syntax error, unexpected '[' in /usr/share/elkarbackup/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/GenerateCommand.php on line 105
```
Apparently the Doctrine ORM v2.5 (included into the deb package) doesn't support PHP 5.3. We should downgrade to 2.4 if we want to support PHP 5.3 systems.

**Comment by elacunza** [comment]
Hi,

El 17/12/15 a las 00:19, Xabi escribió:
>
> I'm testing the new v12 pre alpha deb package on Ubuntu Precise and I 
> have the following error:
>
> $ /usr/share/elkarbackup/app/console cache:warmup --env=prod
> PHP Parse error:  syntax error, unexpected'['  in  /usr/share/elkarbackup/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/GenerateCommandphp on line 105
>
> Apparently the Doctrine ORM v25 (included into the deb package) 
> doesn't support PHP 53 We should downgrade to 24 if we want to support 
> PHP 53 systems
>
>
I think it's better in the medium and long term to require PHP 5.4 or 
better. A small recap of distros to PHP version

* Debian 7 - php 5.4.4 (2013-05)
* Ubuntu 12.10 - php 5.4.6 (2012-10)
* OpenSUSE 13.1 - php 5.4.20 (2013-11)
* Fedora 17 - php 5.4.1 (2012-05)
* CentOS 7 - php 5.4.16 (2015-03)

I don't think we need to release new versions for old distros. I know 
precise is 12.04LTS but if users want elkarbackup v1.2, I think it's 
reasonable to ask them to upgrade to 14.04LTS.

We can even drop Debian 7 support if that eases the work too. Also, I'm 
sure there will be precise repositories with php 5.4 or newer out there :)

My 1¢

Cheers
Eneko

-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
Update ubuntu 12.04 to PHP 5.4 or PHP 5.5 (just google it)
http://www.pixelite.co.nz/article/upgrading-php-54-ubuntu-1204-lts-support-drupal-8/

I think that we can give rsync support for all but PHP.... I agree with Eneko, that if you want the 1.2 version improvements, I see reasonable to upgrade the Ubuntu 12.04 version to fit the elkarbackup needs.

Cheers ;)

**Comment by antton** [comment]
Another option.
What about this? http://stackoverflow.com/questions/34210002/composer-json-should-uses-different-packages-versions-depending-of-php-version

We could specify doctrine (migrator library as I can see) which one to use in case of PHP version.

I don't know if this is possible I never try? Maybe @blaskurain knows more about it, but not me :D  

Bye

**Comment by blaskurain** [comment]
I didn't even know it was possible!

At any rate, I don't think it is a suitable solution: bear in mind that we use composer at build time, not at install time. To do what @antton suggest would require significant changes to the installation script, including but not limited to a call to composer. Calling composer at install time would also mean that the installation script would have to download the dependencies unless we found a way to include several versions of the problematic library inside the .deb.

Too much work/headaches for too little gain.

**Comment by xezpeleta** [comment]
I agree. The simplest way is to require PHP 5.4+

Doing that we could take advantage of Doctrine ORM 2.5 new features: http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/changelog/migration_2_5.html

**Comment by xezpeleta** [comment]
I can confirm that upgrading to PHP 5.4 [1]  everything works ok. I close the issue.

1: https://github.com/elkarbackup/elkarbackup/issues/119#issuecomment-165403772
