### ISSUE TITLE
Rsync Nice possible?

### ISSUE THREAD

**Issue by ricardo777** [elkarbackup/elkarbackup#129]
Hello,

Have searched the faq and wiki but couldn't find it.

Is a nice command possible? At the moment is uses all the LAN of my VPS it is going above 30MB

**Comment by xezpeleta** [comment]
Rsync supports the option to limit the used bandwith:

```
rsync --bwlimit=<kb/second> <source> <dest>
```

http://www.howtogeek.com/50794/keep-rsync-from-using-all-your-bandwidth/

Right now Elkarbackup doesn't have the possibility to modify Rsync advanced arguments in the GUI. But you could change it in the sources.

https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Resources/views/Default/rsnapshotconfig.txt.twig#L141

You have to add your customized argument (--bwlimit=200) on **rsync_long_args**. Example:

```
rsync_long_args --delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx -bwlimit=200
```

I hope this answers your question.

**Comment by xezpeleta** [comment]
Upcoming version (v1.2.0) will have the possibility to add custom Rsync parameters under `Client configuration -> Advanced configuration -> Rsync long args`

If you want to limit the used bandwidth to 500kb/s, you should add: `--bwlimit=500`

If you want to test that feature, you can install the Beta1 version:

https://github.com/elkarbackup/elkarbackup/releases/tag/elkarbackup_1.2.0-beta1
