### ISSUE TITLE
ElkarBackup on CentOS 7

### ISSUE THREAD

**Issue by marceloeng** [elkarbackup/elkarbackup#132]
Hello,

Can I install on CentOS 7?

Thanks

**Comment by xezpeleta** [comment]
Hi @marceloeng ,

Not at the moment, but it's in our roadmap.

We will keep you updated!

**Comment by xezpeleta** [comment]
Hi @marceloeng 

You can now install Elkarbackup on CentOS 7: https://github.com/elkarbackup/elkarbackup/wiki/Installation#centos-7
