### ISSUE TITLE
Beta version 1.2 move health indicator

### ISSUE THREAD

**Issue by ricardo777** [elkarbackup/elkarbackup#134]
Hello,

I am trying out Beta 1.2 good work interface is much better.

Only one thing with my notebook small scren 15.4 there is alot of white height becuase of the heal indicator button maybe you can move it along the Jobs title or next to the other buttons.

See screenshot.
![screenshot-195 154 76 12 2016-04-06 09-36-38](https://cloud.githubusercontent.com/assets/1004317/14309189/276d307c-fbdb-11e5-9468-9078869c1f4a.png)

**Comment by xezpeleta** [comment]
Yes, it's a provisional box and we will probably change that before the stable release.

Thanks for testing the beta package.

**Comment by xezpeleta** [comment]
The next Beta2 package will have the new disk usage indicator:

![screenshot from 2016-05-26 13-33-38](https://cloud.githubusercontent.com/assets/1846038/15573388/014c9c78-2347-11e6-9be2-08466c349893.png)

![screenshot from 2016-05-26 13-34-15](https://cloud.githubusercontent.com/assets/1846038/15573465/82dd8f4a-2347-11e6-9a10-d59e561c7c3c.png)


The color of the icon and the bar will change depending of the disk usage.

**Comment by ricardo777** [comment]
Looks very nice, Great work. 

Love the project.

**Comment by elacunza** [comment]
El 26/05/16 a las 13:41, Xabi escribió:
>
> The next Beta2 package will have the new disk usage indicator:
>
> screenshot from 2016-05-26 13-33-38 
> <https://cloud.githubusercontent.com/assets/1846038/15573388/014c9c78-2347-11e6-9be2-08466c349893.png>
>
> screenshot from 2016-05-26 13-34-15 
> <https://cloud.githubusercontent.com/assets/1846038/15573465/82dd8f4a-2347-11e6-9a10-d59e561c7c3c.png>
>
> The color of the icon and the bar will change depending of the disk usage.
>
Wouldn't it be better to show the percentaje besides de icon, so that 
there's no need to hover the icon to see free space? :)

Cheers

-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943493611
       943324914
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
We are thinking to give more stats than disk free space if future releases, that why we need more space than the percent next to the hard disk icon.

If anyone have more ideas or needs just let us know.
