### ISSUE TITLE
Blank page after login

### ISSUE THREAD

**Issue by vasukolli** [elkarbackup/elkarbackup#137]
Hi,

After updating the sendmail configuration , I cannot access the application it's displaying blank page.
I tried to access in private window but the same issue occure after logging in.
I have attached log files please find them.

[access.txt](https://github.com/elkarbackup/elkarbackup/files/239848/access.txt)
[BnvLog.txt](https://github.com/elkarbackup/elkarbackup/files/239849/BnvLog.txt)
[error.txt](https://github.com/elkarbackup/elkarbackup/files/239850/error.txt)

**Comment by xezpeleta** [comment]
Hi @vasukolli 

I would need to see your parameters.yml (`/usr/share/elkarbackup/app/config/parameters.yml`). Remember to hide your passwords.

Thanks

**Comment by xezpeleta** [comment]
Another question: how did you change the sendmail configuration?

Thanks

**Comment by vasukolli** [comment]
Hi,
Thanks for reply.

Parameters.yml data:


parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: elkarbackup
    database_user: elkarbackup
    database_password: password
    mailer_transport: sendmail
    mailer_host: smtp.pepipost.com
    mailer_user: greenbuds
    mailer_password: password
    locale: en
    secret: secretkey
    database_path: null
    upload_dir: /var/spool/elkarbackup/uploads
    backup_dir: /var/spool/elkarbackup/backups
    public_key: /var/lib/elkarbackup/.ssh/id_rsa.pub
    max_log_age: P1M
    tmp_dir: /tmp
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
    url_prefix: 
    disable_background: false

    mailer_from: backup_admin@greenbuds.in

I have changed using web interface.

**Comment by xezpeleta** [comment]
Please, try to do this as root:

```sh
/usr/share/elkarbackup/app/console c:c --env=prod
```

Any error?

**Comment by vasukolli** [comment]
This is the error message displayed:
                                                               
  [InvalidArgumentException]                                     
  The namespace "c" is ambiguous (cache, container and 1 more).

**Comment by vasukolli** [comment]
Didn't exactly what caused this error, but after deleting contents in "/usr/share/elkarbackup/app/cache"
I am able to access the web interface.

**Comment by xezpeleta** [comment]
Thanks @vasukolli . What elkarbackup version do you have installed?

**Comment by vasukolli** [comment]
Version: 1.1.5

**Comment by xezpeleta** [comment]
That works well in a default installation. I have the same version in my backup server and I can manage parameters via GUI without problems.

Can you send more info? Did you make any change to the installation? Any permission changed? Do you have enough space in your disk?

By the way, can you send us a screenshot of you "Manage parameters" window?

Thanks

**Comment by vasukolli** [comment]
-os: Debian 8
-Nearly 300GB space available
-I have not done any changes to installation
-Regarding permissions please suggest me recommended permissions 
Screen Shot:
![manage_parameter](https://cloud.githubusercontent.com/assets/9819197/1491594/28dbb026-0e34-11e6-907a-1f9ccfcb7e0f.png)

Thank You.

**Comment by xezpeleta** [comment]
> Regarding permissions please suggest me recommended permissions

Here you have:

```
-rw-rw-r-- 1 www-data www-data 783 Apr  5 18:17 /etc/elkarbackup/parameters.yml
```

Try this: back up your current `parameters.yml` and then try to change some parameter through the GUI. Now, compare both files (the new one and the old one) to be sure it is not changing any password, or any permission.

**Comment by vasukolli** [comment]
File permissions seems to be same. Changes which I have made are reflecting to file correctly.

But this time blank page occurs after random save attempts i.e..may be after 2nd 3rd or 4th change.

**Comment by xezpeleta** [comment]
> I think the problem may not be with elkarbackup but with symphony cache or php

I agree.

By the way, I realized the command I gave you to clear the cache do not work in Elkarbackup 1.1.5 (Symfony 2.3). Please, try the following command:

```sh
/usr/share/elkarbackup/app/console cache:clear --env=prod
```

Now, try again, and please check if you see something in `/var/log/elkarbackup/prod.log`

Thanks

**Comment by vasukolli** [comment]
I have cleared cache using above command. Now issue not recurring.

**Comment by xezpeleta** [comment]
Great! I close the issue.
