### ISSUE TITLE
jobs show as running that appear not to be, will not abort

### ISSUE THREAD

**Issue by tjfayaz** [elkarbackup/elkarbackup#138]
ok so I have some jobs which show as "running" but they don't seem to be doing anything. Also I cannot abort them.If I press "abort" then the job says "aborting" forever!

ps aux|grep du        - shows nothing running
ps aux|grep rsync   - shows nothing running

any suggestions how I can stop these jobs?

![screen shot](https://cloud.githubusercontent.com/assets/18698591/14890014/e5dddc6c-0d58-11e6-9b31-6d08acdd021a.png)

**Comment by xezpeleta** [comment]
Abort button triggers abortJob function. I guess it saw there was nothing running, so it finished without change the "aborting" status (maybe I should change that).

So the real question here is: why do you have some jobs as "running" (while they are not really running)? I recommend you to analyze these jobs one by one. Try to run it manually and check de logs, to see what is happening.

For example, let's start with the first one. Can you start the job backup manually? Can you send us your logs?

**Comment by tjfayaz** [comment]
Hi I think it's because I keep getting problems with backups queueing and not running so I then have to force the jobs to start. Then I end up with errors and "failed" on jobs which seem to still be running. Other sshow as "running" when they are not.
 e.g.
> Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.8_8.cfg" Daily 2>&1 failed

How can I make it so all jobs start as per the schedule and stop them queueing? I cannot wait for the queue or the jobs don't have time to finish before the next day! I need all my jobs to start at the smae time - or at least an option for setting it to either queue or immediate start?

**Comment by xezpeleta** [comment]
> Hi I think it's because I keep getting problems with backups queueing and not running so I then have to force the jobs to start

Do you mean they appear as "queued" and they won't start running? 

> Then I end up with errors and "failed" on jobs which seem to still be running. Other show as "running" when they are not (no rsync process for the job).

Do you see more than one job as "running" at the same time? That's strange, as the backup should work sequentially. 

We need more info. You should check your logs to see what's happening there:

- /var/log/elkarbackup/BnvLog.log
- /var/log/apache/elkarbackup-error.log
- /var/log/apache/elkarbackup-ssl.error.log
- /var/log/syslog

Do you see something strange there?

**Comment by tjfayaz** [comment]
they do work sequentially but my problem is I want them to all run at the same time. Is this possible? I can only get it to all run at same time when I start them all manually.

I can't let them run sequentially because there is not enough time so I need them all starting at the same time

**Comment by xezpeleta** [comment]
> my problem is I want them to all run at the same time. Is this possible? I can only get it to all run at same time when I start them all manually.

No, sorry. Elkarbackup was designed to run jobs sequentially.

**Comment by tjfayaz** [comment]
Ah ha ok thanks. It's still awesome.

I'll see if I can make some changes to mine and get it the way I want. Thanks for your fast responses 😊

**Comment by xezpeleta** [comment]
You can try adding several scheduled backups during the day. For instance, every 5 hours. With only one or two retention policy. In this way, it will need less time to copy the files in the Daily backup.

Try and tell us if you discover any kind of workaround to make it work.

Thanks ;)
