### ISSUE TITLE
Remove "owner" field in Job edition form and add "Client owner" instead

### ISSUE THREAD

**Issue by tjfayaz** [elkarbackup/elkarbackup#139]
could we restrict owner selection in the "Edit job" so that non admin users cannot see or change ownership of jobs?

**Comment by xezpeleta** [comment]
If I'm not wrong ownership only works in client level.

/cc @antton

**Comment by antton** [comment]
Hi @tjfayaz, 

I think you are confused with job owner and email notification owner.

Only admin type users can assign jobs to an other user or even remove this the ownership.

Are we talking about the same?

Let me know please! And we would try to clarify the new users and permission situation.

Thanks!

**Comment by antton** [comment]
Hi again, 

I write "Only admin type users can assign jobs to an other user or even remove this the ownership."

But I wanted to say "Only admin type users can assign clients to an other user or even remove this the ownership."

Jobs does not have any kind of owner assignment only notification "email" owner.
 
Sorry for my mistake!

**Comment by xezpeleta** [comment]
Probably we should change "Owner" label to something like "Email owner" or "Notify to" in Jobs. I'm gonna keep this issue open until fix that.

**Comment by antton** [comment]
It's a good idea! +1

**Comment by tjfayaz** [comment]
Hi what I mean is the "owner" dropdown allows users to see all the other email owners. I don't want users to be able to change the email owner or see other users in the system! I would rather only administrators can change the email owners - does that make sense? I use this with different customers and I don't want them to see who else is on the system!

**Comment by antton** [comment]
Got it! I'll chat with @xezpeleta and check what can we do for this 1.2 release about this "problem"

We let you know!

**Comment by xezpeleta** [comment]
Ok @tjfayaz 

I suggest the following change for the Job edition form:

![screenshot from 2016-04-29 11-48-28](https://cloud.githubusercontent.com/assets/1846038/14913035/65cd1d8c-0e00-11e6-9194-809323ce8ce2.png)

We'd remove the field "owner" for Jobs, and now "owner" select box under "Send notices to" means "Client owner". Which is something only admins can change from Client form.

What do you think?

**Comment by tjfayaz** [comment]
that would be perfect!
