### ISSUE TITLE
fies not showing on restore browsing on 1.2

### ISSUE THREAD

**Issue by tjfayaz** [elkarbackup/elkarbackup#144]
I've found that I cannot browse to files or folders on backups even though those files are there!

For example I can click and browse to xyz/xyzDaily.1/var/www/imscp/gui/
nothing is in here in the browser. I have tried various web browsers too. But if I browse the storage location on SSH I can see files. The files are the correct ownership of elkerbackup too.  

Why are the files not showing in the web browser and how can I fix this? 

root@ubuntu:~# su elkarbackup
elkarbackup@ubuntu:/root$ ls -l /mnt/nas/elkarbackups/0001/0001/Daily.1/var/www/imscp/gui
total 24
dr-xr-x--- 9 elkarbackup elkarbackup 4096 Sep 23  2014 data
drwx------ 3 elkarbackup elkarbackup 4096 Aug 29  2014 i18n
dr-xr-x--- 6 elkarbackup elkarbackup 4096 Aug 29  2014 library
drwxr-x--- 2 elkarbackup elkarbackup 4096 Aug 29  2014 plugins
dr-xr-x--- 7 elkarbackup elkarbackup 4096 Feb 15 09:45 public
dr-xr-x--- 3 elkarbackup elkarbackup 4096 Aug 29  2014 themes
elkarbackup@ubuntu:/root$

**Comment by xezpeleta** [comment]
Take a look at this: https://github.com/elkarbackup/elkarbackup/wiki/FAQ#restore-button-is-disabled-or-it-doesnt-work-i-have-an-error-404-not-found

**Comment by tjfayaz** [comment]
ok thanks I can fix it below. But the original /mnt/nas/elkarbackups is the correct permissions so how is it the permissions are not correct for some folders? Do I need to run a chown command after every backup? 

chmod o+r -R /mnt/nas/elkarbackups/0001/0001/Daily.1

**Comment by xezpeleta** [comment]
> so how is it the permissions are not correct for some folders? Do I need to run a chown command after every backup? 

If you have wrong permissions in some clients, probably is because the first time you run its jobs was with a command by hand. Doing this with the GUI the permission should be ok.

> UPDATE I'm going to try this as a custom arg to rsync which I think will fix it
> --chown=elkarbackup:elkarbackup

Very interesting. Thanks ;)

**Comment by tjfayaz** [comment]
thanks for a fast answer again. never ran it by hand, so I'll use that chown long arg and see what happens :). I think it will be ok now as I used to have this problem with rsnapshot until I used the chown option

**Comment by xezpeleta** [comment]
> thanks for a fast answer again. never ran it by hand, I realised I made a mistake above - it's the apache user which cannot read the elkarbackup folder so I changed apache to run as elkarbackup and now it's fixed. I removed the log args chown above.

You don't need to do that. If you check the FAQ link you will see that the correct permissions should be something like that:

```sh
# file: /var/spool/elkarbackup
# owner: elkarbackup
# group: elkarbackup
user::rwx
group::r-x
other::r-x
```

In https://github.com/elkarbackup/elkarbackup/issues/144#issuecomment-216488082 you added read (r) permission for others, but you need to add access (x) permission too in the directories.

From the FAQ:

> Otherwise, fix it removing all extended ACL entries:
> 
> setfacl -bn /var/spool/elkarbackup
> 
> And restore the default permissions:
> 
> setfacl g::r-x /var/spool/elkarbackup
> setfacl o::r-x /var/spool/elkarbackup

**Comment by tjfayaz** [comment]
Hi I tried but it doesn't work for me syntax problem so I used chown instead.

sysadmin@ubuntu:~$ setfacl g::r-x /mnt/nas/elkarbackups
Usage: setfacl [-bkndRLP] { -m|-M|-x|-X ... } file ...
Try `setfacl --help' for more information.

But also I don't understand how the permissions got broken, because I never ran the backups outside of the web interface, and they look correct as per below. Anyway I think my problem is gone now so we can close this

sysadmin@ubuntu:~$ getfacl /mnt/nas/elkarbackups
getfacl: Removing leading '/' from absolute path names
# file: mnt/nas/elkarbackups
# owner: elkarbackup
# group: elkarbackup
user::rwx
group::r-x
other::r-x

**Comment by xezpeleta** [comment]
> But also I don't understand how the permissions got broken, because I never ran the backups outside of the web interface, and they look correct as per below

You are not using the default directory for backups (`/var/spool/elkarbackup/backups`) so I imagine that your permission problem is caused by that change.

> Anyway I think my problem is gone now so we can close this

Great. Tell us if you have more problems.
