### ISSUE TITLE
"run now" commandline

### ISSUE THREAD

**Issue by tjfayaz** [elkarbackup/elkarbackup#145]
Hi I know this was designed to run each job sequentially but I really need all my jobs to start at the exact time I tell them regardless. Currently I have all my jobs set to run at 5pm but they never finish becuase the first job takes 6+hrs to complete.

Is there a quick easy way I can force all my jobs to start at the scheduled time? Currently I have to login manually and press "run now" against every job at 5pm and then all my jobs complete by morning. I have plenty of bandwidth so this is not a limiting factor for me and I do not need jobs to "queue".

I tried starting the job on commandline as per the wiki but this simply queues it. How can I do a "run now" on the command line?

**Comment by xezpeleta** [comment]
> I tried starting the job on commandline as per the wiki but this simply
> queues it. How can I do a "run now" on the command line?
>


Hi, what command are you using? Did you try to write any script to run all
the jobs at same time?

**Comment by tjfayaz** [comment]
Hi I tried the below command as user elkarbackup. It didn't work or seem to do anything. Job was still queued and not running

/usr/share/elkarbackup/app/console elkarbackup:run_job <client-id> <job-id>

**Comment by antton** [comment]
Via Curl maybe using the new token key?

**Comment by tjfayaz** [comment]
Antton could you expand on that?

**Comment by antton** [comment]
If I'm not wrong you whereusing the last 1.20 beta version, isn't it?

**Comment by tjfayaz** [comment]
Yes that's correct. But I also have 1 server running the stable version

**Comment by antton** [comment]
I was thinking and is better if you use the run_job command line mode instead of curl (this is better for remote servers or other operations) If I where you I would just use this as follow:

/usr/share/elkarbackup/app/console elkarbackup:run_job <client-id> <job-id> &

As I see you try with it, but you write wrong the job-id part, the id of the job is the number behind the point for example

/usr/share/elkarbackup/app/console elkarbackup:run_job 1 3 &
/usr/share/elkarbackup/app/console elkarbackup:run_job 1 11 &

and not

/usr/share/elkarbackup/app/console elkarbackup:run_job 1 1.3 &
/usr/share/elkarbackup/app/console elkarbackup:run_job 1 1.11 &

I'm not really sure if your problem is gonna solve in this way, but you can try, I recommend you to put more backups a day instead of launch all at the same time, but maybe is not possible in your organization infrastructure.

Cheers

**Comment by tjfayaz** [comment]
Thanks I can see my mistake on the calling the job! I will try it later and post results. Will "/usr/share/elkarbackup/app/console elkarbackup:run_job &" start ALL jobs running? Or should I call them each in turn? I will make a cron if it works.

**Comment by antton** [comment]
We don't have any option to make it work all together.

You need to write one by one.

Let us know!

**Comment by tjfayaz** [comment]
ok so I ran them one by one but all it did was queue them! So they didn't run immediately. There must be a way on commandline I can do a "run now"? When I press run now on each job it works manually.

**Comment by antton** [comment]
Ok! Can you try the following, remember that it's only working in the last version.

Get you task token and do the following.

curl —insecure —data "token=581cfa928350ccdd2e390411c2aa2880" https://192.168.33.10/client/40/job/37/run

As I can remember now it only works if your installation is https.

Try and let us know!!

**Comment by tjfayaz** [comment]
ok trying but failing to get the curl way to work, when I try with curl and the correct token I always get 

curl: (6) Could not resolve host: xn--insecure-0n3d

But the URL I'm using is resolvable and even if I use https://localhost/client/2/job/2/run it still says the same error!

**Comment by xezpeleta** [comment]
I think @antton 's command has a typo related with the hyphen. The correct way would be:

```
curl --insecure --data ...
```

**Comment by tjfayaz** [comment]
sorry no joy, trying this results in "curl: (6) Could not resolve host: xn---data-3u3b"

curl --insecure —-data "token=8f583e7a51f1c2f5a96e6aebb5217ad5" https://backups.withsupport.co.uk/client/2/job/2/run

**Comment by xezpeleta** [comment]
You're still using the wrong dash mark

**Comment by tjfayaz** [comment]
ok fixed the dashes but now I get this

{"status":"false","msg":"You need to login or send properly values"}

**Comment by xezpeleta** [comment]
So apparently you're not sending the correct token for the job 2 (under client 2).

**Comment by tjfayaz** [comment]
yay thanks it's working now after token regen! Now I also noticed that the RAM usage is mega - I had to add 32GB RAM to stop it from getting used up while running backups (tick). I will see how it goes now.
