### ISSUE TITLE
rsync fallow symlink

### ISSUE THREAD

**Issue by mpisek** [elkarbackup/elkarbackup#146]
Hello!

How would I be able to follow symlinks and copy them.

I have some volumeshadowcopies accessible via cygwin but can't copy them! ElkarBackup "rsync" replies:  succeeded with output: skipping non-regular file 

I think there is a switch rsync -l for that...

Thanks for your help! Regards, Matej

**Comment by xezpeleta** [comment]
Hi, you have more info about that question in this thread:

https://groups.google.com/forum/#!topic/elkarbackup-users/tlfIJcQY9ro
