### ISSUE TITLE
feature request:  multiple backups location

### ISSUE THREAD

**Issue by varuzam** [elkarbackup/elkarbackup#149]
Hi.

it would be nice to be able to add multiple backups location and choose them in job

**Comment by kayvanaarssen** [comment]
+1!!!

**Comment by launtony** [comment]
+1 :)

**Comment by xezpeleta** [comment]
This feature has been added. It will be available in the next version.

**Comment by alfredobz** [comment]
+1!

2018-03-02 12:45 GMT+01:00 Xabi <notifications@github.com>:
