### ISSUE TITLE
Restore -> The server returned a "404 Not Found"

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#15]
He configurado el servidor para que guarde las copias en un recurso tipo NFS. Monta perfectamente el NFS y realiza las copias sin problema.

El tema es que desde que he hecho esto ya no puedo acceder a la parte de "Restore". Independientemente del cliente seleccionado, me aparece este error:

```
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please e-mail us at [email] and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

¿Alguien sabe a qué puede ser debido? ¿Tiene sentido que la parte de copias funcione y la de restore no?

Eskerrik asko

**Comment by duven87** [comment]
Hola! 
acabo de instalar ahora mismo elkarbackup. Todo el proceso ha ido bien pero una vez finalizado me he redirigido en el navegador: https://192.168.1.82/elkarbackup/app.php/login
y me aparece esto tambien:


Oops! An Error Occurred
The server returned a "404 Not Found".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Los logs de elkarbackup estan vacios.. no se que hacer.

**Comment by igorbga** [comment]
app.php?
Puede ser que te falte el módulo de rewrite en Apache?

**Comment by xezpeleta** [comment]
> creo que SOLVED:
> No habia que redifirse a esa pagina, si no a http://localhost/elkarbackup/login
> No he seguido bien la docu o es que esta mal redactado?

He actualizado la documentación apuntando a la URL correcta

gracias
