### ISSUE TITLE
ElkarBackup on Ubuntu 16.04 LTS ?

### ISSUE THREAD

**Issue by kovalroma** [elkarbackup/elkarbackup#150]
Hello,
Can I install on Ubuntu 16.04 ?

Thanks!

**Comment by xezpeleta** [comment]
Hi @kovalroma, can you try now?

**Comment by kovalroma** [comment]
According to this instruction 
https://github.com/elkarbackup/elkarbackup/wiki/Installation#ubuntu-1604-lts

I've got error in first step.
`root@ubuntu:~# apt-get install debconf php5 php5-cli rsnapshot mysql-server php5-mysql acl bzip2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  php7.0-cli:i386 php7.0-cli

Package php5-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5' has no installation candidate
E: Package 'php5-cli' has no installation candidate
E: Package 'php5-mysql' has no installation candidate
root@ubuntu:~#
`

It seems that Ubuntu 16.04  doesn't contain php5 in repository.

**Comment by joker-x** [comment]
Ubuntu 16.04 use PHP 7, you can try install:

```
apt-get install debconf libapache2-mod-php php-cli rsnapshot mysql-server php-mysql acl bzip2
```

**Comment by xezpeleta** [comment]
@kovalroma did you finally fix it?

**Comment by xezpeleta** [comment]
We have updated the instructions for Ubuntu 16.04: https://github.com/elkarbackup/elkarbackup/wiki/Installation#ubuntu-1604-lts

**Comment by xezpeleta** [comment]
This bug should be fixed.

The bad news: we have to create two deb packages.
