### ISSUE TITLE
job stops with error

### ISSUE THREAD

**Issue by xkoyot** [elkarbackup/elkarbackup#154]
Hello, got a problem with running a job job stops with:

 	Command "/usr/bin/rsnapshot" -V -c "/tmp/rsnapshot.1_1.cfg" sync 2>&1 failed. Diagnostic information follows: ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -V -c /tmp/rsnapshot.1_1.cfg sync ---------------------------------------------------------------------------- ERROR: /tmp/rsnapshot.1_1.cfg on line 190: ERROR: backup 10.53.1.44:myData . - Source directory "10.53.1.44:myData" \ doesn't exist ERROR: --------------------------------------------------------------------- ERROR: Errors were found in /tmp/rsnapshot.1_1.cfg, ERROR: rsnapshot can not continue. If you think an entry looks right, make ERROR: sure you don't have spaces where only tabs should be. /usr/bin/logger -i -p user.err -t rsnapshot /usr/bin/rsnapshot -V -c \ /tmp/rsnapshot.1_1.cfg sync: ERROR: Errors were found in \ /tmp/rsnapshot.1_1.cfg, rsnapshot can not continue.

config on windows pc looks like:

uid=0
gid=0

use chroot = false
strict modes = false
hosts allow = 10.53.0.25 # Elkarbackup server IP address. Important: DNS name will not work!
log file = rsyncd.log

[myData]
path = /cygdrive/c/Backups
read only = true
transfer logging = yes

Also cant configure sending emails... set an IMAP server adre instead of localhost, but in logs i see this:

Command was unable to send the notification message: Connection could not be established with host localhost [Connection refused #111]

I've made cache clear but no changes. 

Thx

**Comment by BryanARivera** [comment]
@xkoyot Maybe check this out first:

`Source directory "10.53.1.44:myData" \ doesn't exist`
