### ISSUE TITLE
rsnapshot-1.4.2

### ISSUE THREAD

**Issue by m-osmani** [elkarbackup/elkarbackup#156]
hello,

it is possible to build a new deb file based on rsnapshot-1.4.2 (https://github.com/rsnapshot/rsnapshot/releases/download/1.4.2/rsnapshot-1.4.2.tar.gz ) and offer it in your debian wheezy/jessie repository ?

**Comment by xezpeleta** [comment]
Hi @m-osmani , we didn't test it well, but if you want, you can install it using Debian Testing repository:

https://packages.debian.org/stretch/rsnapshot

**Comment by xezpeleta** [comment]
Hi @m-osmani 

After checking everything is working well, I've added rsnapshot 1.4.2 from Debian Testing repositories (https://packages.debian.org/testing/rsnapshot) to the Elkarbackup official Debian Jessie repository.

Thanks
Thanks
