### ISSUE TITLE
[PHP 7] Error 500 al guardar politicas

### ISSUE THREAD

**Issue by mikolatero** [elkarbackup/elkarbackup#161]
Tengo instalado elkarbackup en una VM desde hace tiempo pero debido a problemas de espacio, he decidido instalarlo sobre una maquina física. 

He instalado Ubuntu Server 16.04 y la he actualizado a tope.  Para la instalación de elkarbackup he seguido los siguientes pasos: https://github.com/elkarbackup/elkarbackup/wiki/Installation#ubuntu-1604-lts 

En un principio funcionaba bien pero a la hora de guardar una politica de copias (ya sea editar las predefinidas o bien crear una nueva) me da un error 500:

"
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
"

En el log de apache me muestra lo siguiente:

PHP Fatal error:  Cannot use 'True' as class name as it is reserved in /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/True.php on line 24, referer: http://192.168.0.183/elkarbackup/policy/1?

He instando instalarlo desde GIT generando el deb pero me da el mismo resultado.

php -v me devuelve:

PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

Por lo que he estado leyendo por internet PHP 7 impide que en las clases se usen palabras reservadas (en este caso Class True).

**Comment by mikolatero** [comment]
He intentado realizar un downgrade a PHP 5.6 y ahora es peor, ni me carga en login.

**Comment by xezpeleta** [comment]
Buenas tardes,

La versión compatible con Ubuntu 16.04 (PHP7) ha sido publicada
recientemente y aun no ha sido probada en profundidad.

Le echaré un vistazo, para intentar reproducir el error que mencionas.

En cuanto al downgrade al PHP5.6, debería funcionar sin problemas. Si
quieres puedes probar a limpiar la cache de Symfony ejecutando:

```sh
/usr/share/elkarbackup/app/console cache:clear --env=prod
```

Esto debería solucionar el problema del login.

Hasta pronto

2016-09-27 11:22 GMT+02:00 Jose Maria <notifications@github.com>:

**Comment by xezpeleta** [comment]
Bug solucionado. Intentaremos publicar una nueva versión lo antes posible.

Si tienes prisa, puedes arreglarlo tu cambiando el fichero `/usr/share/elkarbackup/Binovo/ElkarBackupBundle/Entity/Policy.php`, línea 75 sustituir True por IsTrue https://github.com/elkarbackup/elkarbackup/commit/f264e65ce9689a69ac298549aa44825a24ea862b

Gracias por el reporte
