### ISSUE TITLE
rsnapshot spaces error

### ISSUE THREAD

**Issue by heradon** [elkarbackup/elkarbackup#171]
Hello guys,

I have a problem with a fresh installation of elkbackup (CentOS 7)

i created a complete new system (the first) with a job of backup /etc
![image](https://cloud.githubusercontent.com/assets/908529/19726380/f995d4d8-9b8a-11e6-9c92-98c8f242ad06.png)
![image](https://cloud.githubusercontent.com/assets/908529/19726389/0a2c2ff4-9b8b-11e6-8628-c68dca12e5d7.png)

But in the logs i can see rsnapshot runns into an error:

`[2016-10-26 16:24:01] BnvWeb.ERROR: Command "/usr/bin/rsnapshot" -V -c "/tmp/rsnapshot.2_2.cfg" sync 2>&1 failed. Diagnostic information follows:  ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -V -c /tmp/rsnapshot.2_2.cfg sync ---------------------------------------------------------------------------- ERROR: /tmp/rsnapshot.2_2.cfg on line 190: ERROR: backup tower.DOMAIN.de:/etc . - Source directory \          "tower.DOMAIN.de:/etc" doesn't exist ERROR: --------------------------------------------------------------------- ERROR: Errors were found in /tmp/rsnapshot.2_2.cfg, ERROR: rsnapshot can not continue. If you think an entry looks right, make ERROR: sure you don't have spaces where only tabs should be. /usr/bin/logger -i -p user.err -t rsnapshot /usr/bin/rsnapshot -V -c \     /tmp/rsnapshot.2_2.cfg sync: ERROR: Errors were found in \     /tmp/rsnapshot.2_2.cfg, rsnapshot can not continue. {"source":"RunJobCommand","link":"/client/2/job/2"}  `

Can anyone help me to fix this error?
Thank you

**Comment by parreitu** [comment]
Hi @heradon

According to the message, elkarbackup is not able to find the "/etc" folder
in the host "tower.DOMAIN.de"

Can you check if the Elkarbackup server can communicate with tower.DOMAIN.de
?  a ping should be eough

See you.



2016-10-26 14:48 GMT+02:00 heradon <notifications@github.com>:

**Comment by antton** [comment]
What about the ssh key? Did you already copy in in the tower server?

Can you ssh from elkarbackup server into the tower server?

**Comment by heradon** [comment]
i have generated the ssh key (on the page) and copy to tower (with ssh-copy.... from the wiki)
no tested yet. But rsnapshot says in the config are spaces??

i can test tomorrow (my workday is over ^.^)

**Comment by heradon** [comment]
ssh -i /usr/local/elkarbackup/keys/.ssh/id_rsa root@tower.DOMAIN.de
(Do Okt 27, 09:07:05)--(root@tower)--(0 jobs)--(~)
$ Abgemeldet
Connection to tower.DOMAIN.de closed.

**Comment by xezpeleta** [comment]
Hi @heradon 

What is the generated rsnapshot configuration? https://github.com/elkarbackup/elkarbackup/wiki/FAQ#is-there-a-way-to-see-the-generated-rsnapshot-configuration-file

You can check it running it manually: `rsnapshot -V -c rsnapshot_config.cfg sync`

**Comment by heradon** [comment]
Hey dude thank you for the info ;) Here i can post you the config (for you)

#################################################
# rsnapshot.conf - rsnapshot configuration file #
#################################################
#                                               #
# PLEASE BE AWARE OF THE FOLLOWING RULES:       #
#                                               #
# This file requires tabs between elements      #
#                                               #
# Directories require a trailing slash:         #
#   right: /home/                               #
#   wrong: /home                                #
#                                               #
#################################################

#######################
# CONFIG FILE VERSION #
#######################

config_version	1.2

###########################
# SNAPSHOT ROOT DIRECTORY #
###########################

# All snapshots will be stored under this root directory.
#
snapshot_root	/var/spool/elkarbackup/backups/0002/0002

# If no_create_root is enabled, rsnapshot will not automatically create the
# snapshot_root directory. This is particularly useful if you are backing
# up to removable media, such as a FireWire or USB drive.
#
#no_create_root	1

#################################
# EXTERNAL PROGRAM DEPENDENCIES #
#################################

# LINUX USERS:   Be sure to uncomment "cmd_cp". This gives you extra features.
# EVERYONE ELSE: Leave "cmd_cp" commented out for compatibility.
#
# See the README file or the man page for more details.
#
cmd_cp		/bin/cp

# uncomment this to use the rm program instead of the built-in perl routine.
#
cmd_rm		/bin/rm

# rsync must be enabled for anything to work. This is the only command that
# must be enabled.
#
cmd_rsync	/usr/bin/rsync

# Uncomment this to enable remote ssh backups over rsync.
#
cmd_ssh	/usr/bin/ssh

# Comment this out to disable syslog support.
#
cmd_logger	/usr/bin/logger

# Uncomment this to specify the path to "du" for disk usage checks.
# If you have an older version of "du", you may also want to check the
# "du_args" parameter below.
#
#cmd_du		/usr/bin/du

# Uncomment this to specify the path to rsnapshot-diff.
#
#cmd_rsnapshot_diff	/usr/local/bin/rsnapshot-diff

# Specify the path to a script (and any optional arguments) to run right
# before rsnapshot syncs files
#
#cmd_preexec	/path/to/preexec/script

# Specify the path to a script (and any optional arguments) to run right
# after rsnapshot syncs files
#
#cmd_postexec	/path/to/postexec/script

#########################################
#           BACKUP INTERVALS            #
# Must be unique and in ascending order #
# i.e. hourly, daily, weekly, etc.      #
#########################################

retain	Daily	5
retain	Weekly	4
retain	Monthly	12

############################################
#              GLOBAL OPTIONS              #
# All are optional, with sensible defaults #
############################################

# Verbose level, 1 through 5.
# 1     Quiet           Print fatal errors only
# 2     Default         Print errors and warnings only
# 3     Verbose         Show equivalent shell commands being executed
# 4     Extra Verbose   Show extra verbose information
# 5     Debug mode      Everything
#
verbose		2

# Same as "verbose" above, but controls the amount of data sent to the
# logfile, if one is being used. The default is 3.
#
loglevel	3

# If you enable this, data will be written to the file you specify. The
# amount of data written is controlled by the "loglevel" parameter.
#
#logfile	/var/log/rsnapshot

# If enabled, rsnapshot will write a lockfile to prevent two instances
# from running simultaneously (and messing up the snapshot_root).
# If you enable this, make sure the lockfile directory is not world
# writable. Otherwise anyone can prevent the program from running.
#
lockfile	/tmp/rsnapshot.0002_0002.pid

# Default rsync args. All rsync commands have at least these options set.
#
#rsync_short_args -a
#rsync_long_args	--delete --numeric-ids --relative --delete-excluded
rsync_long_args	--delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats  

# ssh has no args passed by default, but you can specify some here.
#
ssh_args	-o BatchMode=yes -o StrictHostKeyChecking=no 

# Default arguments for the "du" program (for disk space reporting).
# The GNU version of "du" is preferred. See the man page for more details.
# If your version of "du" doesn't support the -h flag, try -k flag instead.
#
#du_args	-csh

# If this is enabled, rsync won't span filesystem partitions within a
# backup point. This essentially passes the -x option to rsync.
# The default is 0 (off).
#
#one_fs		0

# The include and exclude parameters, if enabled, simply get passed directly
# to rsync. If you have multiple include/exclude patterns, put each one on a
# separate line. Please look up the --include and --exclude options in the
# rsync man page for more details on how to specify file name patterns.
#
#include	???
#include	???
#exclude	???
#exclude	???

# The include_file and exclude_file parameters, if enabled, simply get
# passed directly to rsync. Please look up the --include-from and
# --exclude-from options in the rsync man page for more details.
#
#include_file	/path/to/include/file
#exclude_file	/path/to/exclude/file

# If your version of rsync supports --link-dest, consider enable this.
# This is the best way to support special files (FIFOs, etc) cross-platform.
# The default is 0 (off).
#
#link_dest	0

# When sync_first is enabled, it changes the default behaviour of rsnapshot.
# Normally, when rsnapshot is called with its lowest interval
# (i.e.: "rsnapshot hourly"), it will sync files AND rotate the lowest
# intervals. With sync_first enabled, "rsnapshot sync" handles the file sync,
# and all interval calls simply rotate files. See the man page for more
# details. The default is 0 (off).
#
#sync_first	0
sync_first	1

# If enabled, rsnapshot will move the oldest directory for each interval
# to [interval_name].delete, then it will remove the lockfile and delete
# that directory just before it exits. The default is 0 (off).
#
#use_lazy_deletes	0

###############################
### BACKUP POINTS / SCRIPTS ###
###############################

# LOCALHOST
backup	tower.DOMAIN.de:/etc	.

**Comment by heradon** [comment]
[root@localhost www]# rsnapshot -V -c test.conf sync
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot -V -c test.conf sync
----------------------------------------------------------------------------
ERROR: test.conf on line 190:
ERROR: backup tower.int-group.de:/etc . - Source directory \
         "tower.DOMAIN.de:/etc" doesn't exist
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in test.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
/usr/bin/logger -i -p user.err -t rsnapshot /usr/bin/rsnapshot -V -c \
    test.conf sync: ERROR: Errors were found in test.conf, rsnapshot can not \
    continue.

**Comment by xezpeleta** [comment]
What version of Rsnapshot do you have installed?

```sh
$ rpm -q rsnapshot
```

**Comment by heradon** [comment]
rsnapshot-1.3.1-13.el7.noarch

Greez Ralf

**Comment by xezpeleta** [comment]
I've just realized you didn't add a username in your host url (username@host):

![screenshot from 2016-10-27 10-04-34](https://cloud.githubusercontent.com/assets/1846038/19759346/e2a8643c-9c2c-11e6-81fb-ad4b1944c243.png)

Try using *root@tower.DOMAIN.de* as Client Url.

**Comment by heradon** [comment]
Ok. NOW i hate myself!
It woks :dancing_men: with root@domain.tld 

Thank you bro ;) you are the best

**Comment by xezpeleta** [comment]
Great! I'm glad :)
