### ISSUE TITLE
Cannot Download Backup Files

### ISSUE THREAD

**Issue by kayvanaarssen** [elkarbackup/elkarbackup#175]
Hi,

I cannot download a file form a backup only the tar.gz files.

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

URL: 
http://domain.com/elkarbackup/client/2/job/4/backup/download//Hourly.1/backups/databases//game_dream.sql

I see a few: // in the URL.
Even if i delete those it would not download...

I have Setup the storage like this:
/mnt/server-backups/Z_Servers

And on the job:

Path *: /backups/

And like I Said tar.gz files work. it seems only to be that its not working in the last folder.

See the screencast here: http://d.pr/i/XJ89

**Comment by xezpeleta** [comment]
Hi Kay,

How big is your file?

Try increasing the following values in your php.ini:


   - max_execution_time
   - memory_limit

Thanks


2016-11-12 12:48 GMT+01:00 Kay van Aarssen <notifications@github.com>:

**Comment by kayvanaarssen** [comment]
Thanks for the reply.

Is it also possible to let elkarbackup run multiple jobs at once?
Now it starts at the top. And works its way down.

But we have hourly backups of 12 servers and it does not finish them all in one hour since it runs 1-2 jobs at the time

Please let me know if that’s changeable.

Met vriendelijke groet,

Kay van Aarssen

[cid:image001.png@01D23EC1.3B818580]
SPECIALISTEN IN OPLOSSINGEN MET MEETBARE RESULTATEN
Postadres: Steinsedijk 27 / Postcode: 2851LB / Plaats: Haastrecht / Tel: +31 (0) 85 401 71 24
E-mail: info@ictwebsolution.nl<mailto:info@ictwebsolution.nl> / KVK: 53922522 / Webadres: www.ictwebsolution.nl<http://www.ictwebsolution.nl/>

Van: Xabi <notifications@github.com>
Beantwoorden - Aan: elkarbackup/elkarbackup <reply@reply.github.com>
Datum: maandag 14 november 2016 21:45
Aan: elkarbackup/elkarbackup <elkarbackup@noreply.github.com>
CC: Kay Aarssen <kay@kayvanaarssen.com>, Author <author@noreply.github.com>
Onderwerp: Re: [elkarbackup/elkarbackup] Cannot Download Backup Files (#175)

Hi Kay,

How big is your file?

Try increasing the following values in your php.ini:


- max_execution_time
- memory_limit

Thanks


2016-11-12 12:48 GMT+01:00 Kay van Aarssen <notifications@github.com>:
