### ISSUE TITLE
Run Multiple backups at a time

### ISSUE THREAD

**Issue by kayvanaarssen** [elkarbackup/elkarbackup#176]
Now, backups get queued and Elkar works its way form the top to bottom.
Would be nice if you could set a number of running jobs at a time.
Lets say 6 for example.
We now have this: 

<img src='http://d.pr/i/TKmY+'>

**Comment by xezpeleta** [comment]
Currently that's not possible.

The idea could be interesting to investigate. I'm not sure if that will improve the performance.

**Comment by kayvanaarssen** [comment]
It would be awsome as an option.
We are now looking at your product and Burp backup with the Web-Ui.

It would be an awesome feature we have our backup running to 8TB of 15K sas storage with 10Gbit links.

Met vriendelijke groet,

Kay van Aarssen

Verstuurd vanaf mijn iPhone.

Op 14 nov. 2016 om 22:02 heeft Xabi <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Currently that's not possible.

The idea could be interesting to investigate. I'm not sure if that will improve the performance.

-

**Comment by elacunza** [comment]
If we consider this with #149 , I think we'd need a bit more of configuration params. What about the following:
- Global max_parallel_jobs config. There should be never more than that number of parallel jobs running. (default 1)
- Per client client_max_parallel_jobs. Don't do more than this number of parallel jobs for this client (default 1)
- Per storage storage_max_parallel_jobs. Don't do more than this number of parallel jobs for this storage.

**Comment by elacunza** [comment]
@Igortxete7 is working on this, I think he'll have a PR in about a month.
