### ISSUE TITLE
Feature, elkarbackup agent

### ISSUE THREAD

**Issue by ricardo777** [elkarbackup/elkarbackup#178]
Is there any progress with the agent I saw the project but nothing more about it.

Would be a great feature also for ease of setup.

**Comment by xezpeleta** [comment]
Actually that project is quite abandoned.

The things changed quickly when Microsoft introduced the WSL on Windows 10. Currently it's easier to configure a Windows machine to connect with Elkarbackup server. So I believe we should rewrite the code of elkarbackup-agent focusing on WSL.

Probably first step is documentation. We still don't have any configuration guide of ElkarBackup in Windows 10 environment using WSL. Any help will be welcome! ;)

**Comment by antton** [comment]
Yes, please!!!

**Comment by ricardo777** [comment]
And how about a linux agent?

**Comment by ricardo777** [comment]
So with WSL you can run the same agent on windows and linux?

**Comment by antton** [comment]
Hi,

As Xabi said, the agent was a parallel project that is in stand by now.

We need to fix it or rewrite it completely to make something better for any OS as we could.

We are thinking in some new features for elkarbackup and this is gonna be on a list but we can't estimate the release time of it right now.

Sorry!!!

**Comment by elacunza** [comment]
Closing because 2+ years without comment. Not very clear what should feature an agent either.
