### ISSUE TITLE
Error when installing on clean Centos7 OVH template

### ISSUE THREAD

**Issue by ricardo777** [elkarbackup/elkarbackup#179]
According to: https://github.com/elkarbackup/elkarbackup/wiki/Installation#centos-7

I get this error:

Press any key to continue...

which: no composer in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
Download and install composer
All settings correct for using Composer
Downloading 1.2.2...

Composer successfully installed to: /usr/local/elkarbackup/composer.phar
Use it: php composer.phar
Download and install jquery 1.12.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 97362  100 97362    0     0  63387      0  0:00:01  0:00:01 --:--:-- 63428
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
    Failed to download doctrine/lexer from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php.ini
    Now trying to download from source
  - Installing doctrine/lexer (v1.0.1)
    Cloning 83893c552fd2045dd78aef794c31e694c37c0b8c

  [RuntimeException]
  Failed to clone https://github.com/doctrine/lexer.git, git was not found, check
  that it is installed and in your PATH env.
  sh: git: command not found

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

chown: cannot access ‘/usr/local/elkarbackup/app/config/parameters.yml’: No such file or directory
sed: can't read /usr/local/elkarbackup/app/config/parameters.yml: No such file or directory
chown: missing operand after ‘elkarbackup:elkarbackup’
Try 'chown --help' for more information.
ERROR: error bootstraping elkarbackup

**Comment by ricardo777** [comment]
Update

Missing depencies yum install zip unzip git

**Comment by xezpeleta** [comment]
Ok, done. Thank you very much!
