### ISSUE TITLE
Support for Google Nearline cheap solution

### ISSUE THREAD

**Issue by ricardo777** [elkarbackup/elkarbackup#180]
Hello again,

Would be great if Google nearline can be supported for cheap storage: https://cloud.google.com/storage-nearline/

**Comment by xezpeleta** [comment]
Hi @ricardo777,

Do you want to upload a backup to Google Nearline?

As far as I understand, you can do that using a _post_ script. Install gsutil and write a simple script to sync the backup directory in the job/client.

**Comment by ricardo777** [comment]
@xezpeleta

Hello,

Yes indeed I was forgetting that will look into that. 

When I succeed I will post the script.

**Comment by xezpeleta** [comment]
Great, I will be glad to upload your script to [elkarbackup-scripts](/elkarbackup/elkarbackup-scripts)

**Comment by elacunza** [comment]
It's over a year since last post, and this was more a question that a bug/feature request. Closing.
