### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by ricardo777** [elkarbackup/elkarbackup#181]
When I run the installer following this guide: https://github.com/elkarbackup/elkarbackup/wiki/Installation#centos-7

I get the error apache is not installed but it is:

` 3356 apache    20   0  371088    788    780 S  0.0  0.2   0:00.00 httpd
 3357 apache    20   0  371088    784    780 S  0.0  0.1   0:00.00 httpd
 3358 apache    20   0  371088    784    780 S  0.0  0.1   0:00.00 httpd
 3359 apache    20   0  371088    784    780 S  0.0  0.1   0:00.00 httpd
 3360 apache    20   0  371088    784    780 S  0.0  0.1   0:00.00 httpd
 3442 mysql     20   0    9468   1192   1192 S  0.0  0.2   0:00.00 mysqld_safe
 3598 mysql     20   0  941760  65332   8848 S  0.0 12.5   0:00.26 mysqld
 4266 root      20   0   51816   1964   1456 R  0.0  0.4   0:00.00 top

[root@Bk03 ~]# bash -c "$(curl -s https://gist.githubusercontent.com/xezpeleta/c5a5fe960b39cfab29e935dd381a4ab2/raw/eb-installer.sh)"

****************************

* ELKARBACKUP INSTALLATION *

****************************

This program will install ElkarBackup "latest"
Do you want to continue? yes

Checking installed web servers:

 - apachectl           [NOT FOUND]
 - nginx               [NOT FOUND]
ERROR: install a webserver (currently only Apache2 supported)
[root@Bk03 ~]#
`

Version: CentOS Linux release 7.2.1511 (Core)

**Comment by xezpeleta** [comment]
Hi @ricardo777 

In orther to check that Apache is installed, the installation is looking for the command `apachectl`

Did you install Apache using the common way (yum install...)?

**Comment by ricardo777** [comment]
Yes via the command in the guide yum install httpd

**Comment by antton** [comment]
Could you paste the result of:

/usr/sbin/apachectl status

Thanks!

2016-12-02 12:37 GMT+01:00 ricardo777 <notifications@github.com>:

**Comment by antton** [comment]
And I'm not sure but the documentation I think it has a bug in the first
part on which we need to start mariadb and httpd after the required
packages install:

I think it should be systemctl start httpd.service insted of systemctl
start httpd

Could you let me know @ricardo777 if I am right?

Thanks


2016-12-02 12:50 GMT+01:00 Antton Rodriguez <antton.rodriguez@gmail.com>:

**Comment by ricardo777** [comment]
@antton 

Here is the output of the command

`
* httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-12-02 04:19:24 EST; 2h 48min ago
     Docs: man:httpd(8)
           man:apachectl(8)
 Main PID: 3355 (httpd)
   Status: "Total requests: 0; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           |-3355 /usr/sbin/httpd -DFOREGROUND
           |-3356 /usr/sbin/httpd -DFOREGROUND
           |-3357 /usr/sbin/httpd -DFOREGROUND
           |-3358 /usr/sbin/httpd -DFOREGROUND
           |-3359 /usr/sbin/httpd -DFOREGROUND
           `-3360 /usr/sbin/httpd -DFOREGROUND

Dec 02 04:19:24 Bk03.intio.nl systemd[1]: Starting The Apache HTTP Server...
Dec 02 04:19:24 Bk03.intio.nl systemd[1]: Started The Apache HTTP Server.
Dec 02 04:20:41 Bk03.intio.nl systemd[1]: Started The Apache HTTP Server.
Dec 02 04:24:38 Bk03.intio.nl systemd[1]: Started The Apache HTTP Server.`

Also

systemctl start httpd.service
OR systemctl start httpd

works both

**Comment by xezpeleta** [comment]
Hi, try that please:

```sh
which apachectl
```

**Comment by ricardo777** [comment]
Yes Solved, I was missing which so Installed it via yum.

Again an additional for the wiki =)

**Comment by antton** [comment]
great!!!

2016-12-02 13:29 GMT+01:00 ricardo777 <notifications@github.com>:

**Comment by xezpeleta** [comment]
Wow!! I thought `which` was always installed in almost every distros :open_mouth: 

Thanks, I've already add it to the installation guide :wink:

**Comment by ricardo777** [comment]
@xezpeleta Yes I was happy yum and wget was installed, installation is still failed is there something like a installation log? of the script

**Comment by xezpeleta** [comment]
No, there is no log, but you can try the debug mode to obtain more information:

```sh
bash -c "$(curl -s https://gist.githubusercontent.com/xezpeleta/c5a5fe960b39cfab29e935dd381a4ab2/raw/eb-installer.sh)" -c -d
```

Can you show us the output?

Thanks

**Comment by ricardo777** [comment]
I have tried debug mode but I only have some of the total output.

**Comment by antton** [comment]
Is not working yet?

2016-12-05 13:51 GMT+01:00 ricardo777 <notifications@github.com>:

**Comment by ricardo777** [comment]
Not yet at the moment.

Last lines are:

`login as: root
root@88.198.5.71's password:
Last login: Mon Dec  5 07:15:40 2016 from ns3278537.ip-5-39-90.eu
[root@Bk03 ~]# ls
eb-installer.sh  file.log
[root@Bk03 ~]# vi file.log
|                 |
|       .         |
|      . S        |
|       . . o o   |
|      . o = B.   |
|    E .o o Ooo.. |
|     . .o.++*+o..|
+-----------------+




Download and install composer
All settings correct for using Composer
Downloading 1.2.3...

Composer successfully installed to: /usr/local/elkarbackup/composer.phar
Use it: php composer.phar
Download and install jquery 1.12.0
Creating the "app/config/parameters.yml" file

 // Clearing the cache for the dev environment with debug true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


 Trying to install assets as relative symbolic links.

 --- -------------------------- ------------------
      Bundle                     Method / Error
 --- -------------------------- ------------------
  ▒~\~T   FrameworkBundle            relative symlink
  ▒~\~T   BinovoElkarBackupBundle    relative symlink
  ▒~\~T   SensioDistributionBundle   relative symlink
 --- -------------------------- ------------------

 [OK] All assets were successfully installed.


DB updated

Elkarbackup admin user created
VirtualHost configuration:
ServerRoot: "/etc/httpd"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/etc/httpd/logs/error_log"
Mutex default: dir="/run/httpd/" mechanism=default
Mutex mpm-accept: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
Mutex authdigest-client: using_defaults
Mutex proxy: using_defaults
Mutex authn-socache: using_defaults
PidFile: "/run/httpd/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="apache" id=48
Group: name="apache" id=48
ERROR: cannot add cron configuration
`

**Comment by antton** [comment]
ls -lah /etc/cron.d/elkarbackup

did the script create this file?

**Comment by ricardo777** [comment]
ls: cannot access /etc/cron.d/elkarbackup: No such file or directory

**Comment by antton** [comment]
so the previous cp doesn't work properly.

Let me check!!

2016-12-05 14:20 GMT+01:00 ricardo777 <notifications@github.com>:

**Comment by ricardo777** [comment]
You can check via SSH do you have a mail adres where I can mail the login to?

**Comment by antton** [comment]
Morning @ricardo777 before that enter into your server I would like to fix the script.

Could you tell me witch version of CentOS are you installing, I would try to make your steps in a VM and let you know what's going on or try to fix the script.

Thanks!

**Comment by ricardo777** [comment]
Goodmorning 

Centos 7 Version: CentOS Linux release 7.2.1511 (Core)

**Comment by xezpeleta** [comment]
We can't reproduce it. We've tried installing elkarbackup in a clean Centos7 and it creates cron configuration under /etc/cron.d without problems.
