### ISSUE TITLE
Es possible tener el servidor en cloud?

### ISSUE THREAD

**Issue by matalaaranya** [elkarbackup/elkarbackup#183]
Es decir no depender de que todo los backups esten en la oficina.
Necesito poder realizar backups windows pero que el servidor no este en la red local del cliente.
No encontrado informacion sobre esto.

Muchas gracias

**Comment by xezpeleta** [comment]
Hola @matalaaranya 

Si realmente quieres tener el servidor fuera de la oficina, lo recomendable es utilizar _SSH+Rsync_ para conectar de forma segura el equipo windows con el servidor externo.

En equipos posteriores a Windows 10 esto se puede llevar a cabo sin software de terceros, utilizando WSL (aunque de momento la configuración no es sencilla). Si tienes un Windows 8/Windows Server 2012 o anterior, hay que instalar **[Cygwin](https://www.cygwin.com/)**. A partir de ahí, la configuración sería igual que en un cliente Linux.

Por cierto, si lo que buscas es externalizar los datos por seguridad, puedes utilizar un servidor sencillo en la oficina con Elkarbackup y replicar sus datos periódicamente a un servidor externo. [Más información](https://docs.elkarbackup.org/es/configuracion_de_la_aplicacion/copia_del_repositorio.html)

Por último, también puedes hacer uso de los [postscripts](https://docs.elkarbackup.org/es/scripts/un_nuevo_script.html) para subir los datos de Elkarbackup a [servicios en la nube tipo Dropbox](https://docs.elkarbackup.org/es/anexos/sincronizacion_con_la_nube.html).
