### ISSUE TITLE
Question to understand a function

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#189]
Hej @all

in the doumentation in [policies.md](https://github.com/elkarbackup/elkarbackup-docs/blob/master/en/policies.md) I found the following text:

> When we choose this option we tell rsnapshot to first synchronize the files in a folder called .sync to free  the client as soon as possible. When it finishes this part and after leaving the client free, it will compare the data of the last copy (for example Daily.0) with those in the .sync folder, and generate the new structure by adding the necessary hardlinks.

Some questions:
1. Is it really copying the whole data from source to Elkarbackup server in every single backup run if function **sync_first** is enabled? Isn't it time consuming as well?
2. Or is it keeping the data from last run in *.sync folder, just adding the new and changed data and is syncing with the (e.g.) daily.0 afterwards?
3. What happens to the *.sync folder once it was synced with the mentioned daily.0 folder?

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

It doesn't copy whole data every single backup. Rsync/Rsnapshot will copy only the changes, keeping the .sync directory always synchronized (if you have the **_sync_first_** option enabled). And the, the rotation process will start.

More about the Rsnapshot rotation process [here](https://docs.elkarbackup.org/en/rotation.html)

**Comment by parreitu** [comment]
Hi @nephilim75

Yes, as you say * "it is keeping the data from last run in *.sync folder,
just adding the new and changed data and is syncing with the (e.g.) daily.0
afterwards"*

When it exists, you could consider the .sync folder as the lowest level in
the hierarchy, below hourly.0



2017-01-22 18:32 GMT+01:00 Xabi <notifications@github.com>:

**Comment by nephilim75** [comment]
Thank you for clearification. :-)

I'm still translating the documentation. Around 80 % are done right now. Hope to get it finished (translated & reviewed) by end of second week in February. Once it is done I will send a pull request.

Kind regards
//neph
