### ISSUE TITLE
How to configure port elkarbackup listens on?

### ISSUE THREAD

**Issue by aurabindo** [elkarbackup/elkarbackup#191]
I have apache listening on 80 and 443. How do I configure for this situation ? I'm on debian 7

**Comment by xezpeleta** [comment]
Hi @aurabindo

Apache is automatically configured by the ElkarBackup Debian installer. Once the installation is finished, you can access to the web UI using one of those URLs:

http://your-ip-address/elkarbackup
https://your-ip-address/

Thanks
