### ISSUE TITLE
Question - pull request

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#192]
Hello

2 things I need your assistance with:

1. I cloned the [elkarbackup-docs repo](https://github.com/elkarbackup/elkarbackup-docs) into my Github desktop version. Then I created a new branch (called german translation). Then I placed the german translation of the documention into this branch and commited it. Then I tryied to send a pull request but receiving this message:

![sync_fails](https://cloud.githubusercontent.com/assets/19992865/22522370/a70ee794-e8bb-11e6-99bb-da6844918bc8.PNG)

<br />

2. Something similar happened to Elkarbackup repo. I cloned it to my desktop version and did some changes on the german language file. I missed to create a new branch for this as there are just minor changes in the file itself. Then I tried to commit these changes but to me it looks like nothing happens. In the timeline a new circle for the commit appears but it won't be synced with master. Same message as shown above is coming up.

Any idea what I am doing wrong and how I can get the changes submitted?

It is the first time I am contributing on Github. Sorry. :-(

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

In a few words, you should:
- Fork the repository (you will see it now under your account)
- Apply your changes in your fork after all the changes are done (you can do that with the Github Desktop if you want)
- Open a Pull request from your fork to the source repository and wait to be accepted (take care, if you change your code the PR will be updated too)

I think that's enough to start. If you want to go further, you should familiarize first with the [GitHub Workflow](https://guides.github.com/introduction/flow/)

**Comment by nephilim75** [comment]
Hej,

sorry to ask but what means PR?

Kind regards
//neph
-- 
Von (m)einer Couch gesendet...

Am 1. Februar 2017 20:38:20 MEZ schrieb Xabi <notifications@github.com>:
>Hi @nephilim75 
>
>In a few words, you should:
>- Fork the repository (you will see it now under your account)
>- Apply your changes in your fork after all the changes are done (you
>can do that with the Github Desktop if you want)
>- Open a Pull request from your fork to the source repository and wait
>to be accepted (take care, if you change your code the PR will be
>updated too)
>
>I think that's enough to start. If you want to go further, you should
>familiarize first with the [GitHub
>Workflow](https://guides.github.com/introduction/flow/)

**Comment by antton** [comment]
It means pull request ;)

**Comment by nephilim75** [comment]
*lol* It was much too late...

Well, I have send a pull request for the german translation of the [documentation](https://github.com/elkarbackup/elkarbackup-docs).

Please check an d review.

Kind regards
//neph

**Comment by nephilim75** [comment]
*lol* It was much too late.

I have send a pull request to [this repo](https://github.com/elkarbackup/elkarbackup-docs). Please check and review.

Kind regards
//Neph

**Comment by nephilim75** [comment]
I guess, I got it. :-) Thank you so much for all your efforts and patience.
