### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#194]
Hello

is it possible to implement a function to create a new key pair?

Kind regards
//neph

**Comment by xezpeleta** [comment]
If you really know what are you doing, you can generate a new SSH keypair using the following command:

```bash
/usr/share/elkarbackup/app/console elkarbackup:generate_keypair
```

Furthermore, if no keypair is found in the elkarbackup user's home, the GUI will show a button (under `Manage preferences`) to generate a new keypair.

**Comment by nephilim75** [comment]
I thought this is a good feature for people who don't want to interact with a console. Was just an idea. If this is not usefull or reliable, just close this request.

Kind regards
//neph

**Comment by xezpeleta** [comment]
In my opinion that would be a little bit dangerous and not so useful. If you regenerate the ssh keypair you need to reinstall that keypair to all your machines again.

Currently, the keypair is generated in every new installation, so I understand that the only reason to regenerate that keypair is that your private key has been compromised (something not very usual)...
