### ISSUE TITLE
Support for Arch Linux

### ISSUE THREAD

**Issue by kamzata** [elkarbackup/elkarbackup#195]
Hi, could you add support for Arch Linux? By the way, really nice software. Good job!

**Comment by xezpeleta** [comment]
Hi, we're sorry but currently it's not in our roadmap plan. If you want to adapt the current installer to Arch Linux, we will welcome your contribution.

**Comment by xezpeleta** [comment]
Hi, I'm closing this issue.

If you want to install it in a non-Debian-based distro you can try our universal installer: 
https://raw.githubusercontent.com/elkarbackup/elkarbackup/master/install/eb-installer.sh
