### ISSUE TITLE
What value is required by field "Mailer from"?

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#197]
Hello

I receive an error while trying to send information mails from my Elkarbackup backup server:

```
Exception Address in mailbox given [Backup-Server] does not comply with RFC 2822, 3.6.2. running command {"command":"elkarbackup:run_job","client":"1","job":"1"}: 
```

I guess there is something wrong with my input. What did I miss to do? My installed version has the mailer host enabled already.

Kind regards
//neph

**Comment by nephilim75** [comment]
Hej guys

any idea or news on this?

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

What value did you set up there? That should be your custom "from" address for the mail alerts: i.e. elkarbackup@yourserver

Thanks

**Comment by nephilim75** [comment]
Here is my config:

![mail_config](https://cloud.githubusercontent.com/assets/19992865/24079792/effbe436-0c90-11e7-8646-57331255b6e3.PNG)

Error:

```
Exception Address in mailbox given [Elkarbackup] does not comply with RFC 2822, 3.6.2. running command {"command":"elkarbackup:run_job","client":"1","job":"1"}: 
```

Kind regards
//neph

**Comment by antton** [comment]
Hi,

Check you don't have any space after you server name and email address.

Which version of PHP are you using?

Check it and let us know about it.

Cheers!

**Comment by xezpeleta** [comment]
Hi @nephilim75 

As I said before, the "Mailer from" field must contain a valid email address. "Elkarbackup" is not a correct address...

**Comment by nephilim75** [comment]
I am so srorry. My fault. I will try. I made a mistake in the translation. I will correct it with my next PR.

Thank you so much.

Kind regards
//neph

**Comment by nephilim75** [comment]
Closed.
