### ISSUE TITLE
Question - installation without being prompted for user and password possible?

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#199]
Hello

sorry to bother you again.

Is it possible to install ElkarBackup application without being prompted for user and password? I would like to automate the installation and I would like to give the username and password with the installation command. Is this possible? How needs the command look like? I am using `apt-get install elkarbackup` right now.

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

You can do it as you do with any other Debian package installation. Take a look to the Elkarbackup Docker scripts for instance: https://github.com/elkarbackup/elkarbackup-docker/tree/master/latest

You also could use something like Ansible to automate the installation: https://github.com/xezpeleta/elkarbackup-ansible

Thanks

**Comment by nephilim75** [comment]
Thank you so much.
