### ISSUE TITLE
GPG verification fails

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#200]
Hello

I can install EB on server but there seems to be an issue with GPG key verification. My system returned:

```
apt-get install elkarbackup rsnapshot
W: GPG error: http://elkarbackup.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 83C92315F6576C74
```

Kind regards
//neph

**Comment by antton** [comment]
Did you do that before installing the package?
wget -O - http://elkarbackup.org/apt/archive.gpg.key | apt-key add -
Let us know!

**Comment by nephilim75** [comment]
did a fresh installation to recreate the error but it did not appear again. :-)

Kind regards
//neph
