### ISSUE TITLE
Restore options

### ISSUE THREAD

**Issue by JamesColeman-SH** [elkarbackup/elkarbackup#203]
Currently there is not any options to actually restore to a remote machine by using the ELKARbackup interface. I see that there is an idea to add specific restore options, however I would like to specify what I would like to see.

1. Ability to choose a destination client or to manually enter destination ssh/rsync hosts.
2. Ability to specify the restore directory and rather to overwrite existing files or not.

Additionally, it would be nice if the restore system provided a progress interface where you can watch the restore as it occurs.

Right now I can happily just manually use rsync from ssh, however it would be nice to be able to actually restore from the interface so that we could allow our support team to do restores.

**Comment by xezpeleta** [comment]
Thanks @JamesColeman-SH 

This idea is in our roadmap. We'll keep you updated.

**Comment by xezpeleta** [comment]
This feature request has been implemented in #301 

Thanks
