### ISSUE TITLE
Question: delete logs

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#204]
Hello

how can I delete all log entries in log section?

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

You can delete the logs using the console. You can find the logs under /var/log/elkarbackup directory.

**Comment by nephilim75** [comment]
Hej 

I know this directory, and I removed all log entries from this file. Anyhow, log section in app still shows entries over 2 pages.

![eb_logs](https://cloud.githubusercontent.com/assets/19992865/23889201/1ac76d60-088c-11e7-8c01-71207beaa48a.PNG)

I want to get rid of them as well. Is this possible?

Kind regards
//neph

**Comment by xezpeleta** [comment]
Ah ok, that's stored in the DB. If I'm not wrong, there is a table called "LogRecord". I'm not sure if you can delete all its contents. Anyway, I recommend you to make a backup (mysqldump) before any change.

**Comment by nephilim75** [comment]
Thank you so much...

Kind regards
//neph
