### ISSUE TITLE
Question: pw of elkbarbackup user

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#205]
Hello

I want to know the default password of user *elkarbackup*. I want to access a directory via FTP.

Kind regards
//neph

**Comment by xezpeleta** [comment]
elkarbackup user is created with no password. Check it yourself:

```
$ grep elkarbackup /etc/shadow
elkarbackup:*:15988:0:99999:7:::
```
From `man shadow`: _"If the password field contains some string that is not a valid result of crypt(3), for instance ! or *, the user will not be able to use a unix password to log in (but the user may log in the system by other means)."_
