### ISSUE TITLE
Policies Schedule: monthly backups without weekly

### ISSUE THREAD

**Issue by joseguilherme001** [elkarbackup/elkarbackup#206]
Is possible in same policy, schedule snapshot in During the Day, Daily and Monthly?

**Comment by xezpeleta** [comment]
Hi @joseguilherme001 

Yes, i'd say that's possible. Did you get any error?

Thanks

**Comment by joseguilherme001** [comment]
Hi xezpeleta
I' don't get any error. I create the daily and the monthly scheduled , but only execute daily. It seems that the monthly schedule is ignored.

**Comment by xezpeleta** [comment]
You're right. Rsnapshot always needs a backup in the lower level to do the rotation. So you need to specify at least one weekly backup with retention to 1.

**Comment by joseguilherme001** [comment]
I edited the policy and only mark the snapshot as monthly. When finished I mark the daily and execute. After the two bases(daily and monthly) were created I did the scheduling again the daily and monthly and it worked. Is correctly? 
But this configuration spend a lot space the HD, because 1 base for daily another for monthly.

ps. Retention for daily is 180; Retention for monthly is 13.

**Comment by xezpeleta** [comment]
No, it isn't. You made the monthly backups manually, but in that way is not doing the rotation well.

> ps. Retention for daily is 180; Retention for monthly is 13.

That's the problem. Then you have to wait to have 180 daily backups until the system will rotate the last one and create the first monthly backup...

I recommend you to read more about Rsnapshot [rotation](https://docs.elkarbackup.org/en/rotation.html) concept

**Comment by joseguilherme001** [comment]
I read about rsnapshot. I think another way, because I used Backup Exec for long time. After read about rsnapshot I better understand.

Thanks a lot!

**Comment by xezpeleta** [comment]
You're welcome ;)
