### ISSUE TITLE
Windows backup not working

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#208]
Hej guys

sorry to bother you again. I need again your assistance.

I tried to backup some files of my Windows device, but it fails. Here are the steps I did to reproduce:

I installed cwRsync on my Windows computer. I have created user SvcCWRSYNC and added the user to Admin group.

![users](https://cloud.githubusercontent.com/assets/19992865/24079442/8359272e-0c88-11e7-9a92-5596368b1945.PNG)

I started the service Rsync:

![service](https://cloud.githubusercontent.com/assets/19992865/24079445/8ee02f52-0c88-11e7-82d1-a267637f0395.PNG)

This is the content of rsyncd.conf:

```
uid=0
gid=0
use chroot = false
strict modes = false
hosts allow = *
log file = rsyncd.log

# Module definitions
# Remember cygwin naming conventions : c:\work becomes /cygwin/c/work
#
[Data]
path = /cygdrive/c/users/**censored**/nextcloud
read only = false
transfer logging = yes
```

Now I defined the device in EB...

![device_config](https://cloud.githubusercontent.com/assets/19992865/24079451/ab68f2b2-0c88-11e7-98b1-09b7f26b0b2b.PNG)

... and added a job:

![job_config](https://cloud.githubusercontent.com/assets/19992865/24079454/b65237d8-0c88-11e7-8f81-1404d72efebf.PNG)

Unfortunately it fails:

![overview](https://cloud.githubusercontent.com/assets/19992865/24079537/a72cf87c-0c8a-11e7-91ec-8dbb124d6d39.PNG)

Log:

![error log](https://cloud.githubusercontent.com/assets/19992865/24079540/ad234150-0c8a-11e7-9bfd-5e6df4cdabf0.PNG)

Do you see why?

Your assistance is higly appreciated.

Kind regards
//neph

**Comment by antton** [comment]
Can you try a simple rsync from command line first?

I'm not sure but I think the port 873 must be open on windows machine to make it work rsync otherwise install openssh server as well and use both of them in conjunction.

Cheers

**Comment by antton** [comment]
Try to telnet from you EB server to windows machine to the 873 port.

**Comment by nephilim75** [comment]
Hello

I have added firewall rule within Windows and deactivated my Antivirus.

![grafik](https://cloud.githubusercontent.com/assets/19992865/24081252/8cd6a088-0cb0-11e7-81bb-8c46de3ba0a7.png)
<br />

> Try to telnet from you EB server to windows machine to the 873 port.

Well, this is the result:
```
pi@pcf-backup:~ $ ping 192.168.178.39
PING 192.168.178.39 (192.168.178.39) 56(84) bytes of data.
64 bytes from 192.168.178.39: icmp_seq=1 ttl=128 time=2.17 ms
64 bytes from 192.168.178.39: icmp_seq=2 ttl=128 time=2.15 ms
64 bytes from 192.168.178.39: icmp_seq=3 ttl=128 time=2.11 ms
64 bytes from 192.168.178.39: icmp_seq=4 ttl=128 time=2.03 ms
^C
--- 192.168.178.39 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 2.033/2.119/2.175/0.054 ms
pi@pcf-backup:~ $ telnet 192.168.178.39:873
telnet: could not resolve 192.168.178.39:873/telnet: Name or service not known
pi@pcf-backup:~ $ telnet 192.168.178.39:873
telnet: could not resolve 192.168.178.39:873/telnet: Name or service not known
pi@pcf-backup:~ $
```
<br />

> Can you try a simple rsync from command line first?

I don't know how to do on a Windows system. I moved to `c:\Program Files (x86)\ICW>` were I suggested the rsync in but the command prompt replies that my command is unknown:

```
c:\Program Files (x86)\ICW>rsync -a -r i:\backup_final.img i:\rsynctest
Der Befehl "rsync" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

c:\Program Files (x86)\ICW>
```
<br />

> (...) otherwise install openssh server as well and use both of them in conjunction.

Is there a how to?

Kind regards
//neph

**Comment by antton** [comment]
The telnet is not working

Try with this

Telnet IP port

Example:

telnet 192.168.0.30 873

Let me know

Enviado desde mi iPhone

**Comment by nephilim75** [comment]
Looks connected, right?

```
pi@pcf-backup:~ $ telnet 192.168.178.39 873
Trying 192.168.178.39...
Connected to 192.168.178.39.
Escape character is '^]'.
@RSYNCD: 30.0
```

Kind regards
//neph

**Comment by antton** [comment]
It works!!

Try agaian now via elkarbackup ;)

**Comment by nephilim75** [comment]
Well, this is working perfectly fine now. Thank you so much. :-)

But there are questions left:

1. Is this kind of backup with Windows as documented [here](https://docs.elkarbackup.org/en/add-windows-clients.html) a secure way? Is there any key authentication?

2. You wrote, it is working in a combination with OpenSSH. Looks like [Cygwin](http://cygwin.org/) is necessary for this, right? Should it not be documented as well?

Kind regards
//neph

**Comment by xezpeleta** [comment]
> Is this kind of backup with Windows as documented here a secure way? Is there any extra authentication? To me it looks like that all incoming communication is accepted by Windows computer depending on definition of firewall rule.

On Windows clients Rsnapshots recommends to use Rsync protocol with cwRsync, even if it's a not encrypted protocol. You can find more info [here](http://rsnapshot.org/faq.html).

> You wrote, it is working in a combination with OpenSSH. Looks like Cygwin is necessary for this, right? Should it not be documented as well?

As I said before, Rsnapshot suggests to use cwRsync. I know there are some people using Cygwin with SSH&Rsync. If you want you can try that, but we can't help you with that.

At the same time, we're also investigating Windows 10 WSL feature, but apparently that's not very stable yet.

**Comment by nephilim75** [comment]
> On Windows clients Rsnapshots recommends to use Rsync protocol with cwRsync, even if it's not an encrypted protocol.

Am I understand it the correct way, that the communication between EB-Server and the Windows client is not encrypted?

**Comment by antton** [comment]
Hi,

I'll try for you an encrypted way via ssh and let you know how is it going but as far as I know, is now so stable!

You could try with copssh server 

https://itefix.net/content/copssh-free-edition

Is for the sane creators as cwrsync but I never try with it.

Cheers!!

**Comment by antton** [comment]
Hello @nephilim75

I let you know How you can do via ssh.

SSHServer install
1.- Install COPSSH free edition (https://itefix.net/content/copssh-free-edition)
2.- Follow the installation, it will create a service user to start the SSH server
3.- Configure your server with a user (if the backup users is not on the list, create it first)
4.- Add the Elkarbackup ssh public key to the previous decided user on the respective Users tab clicking on the Keys.. button.
5.- Once everything is done restart the service from the Status tab, and try to login via command line. If everything is fine your ssh server part is done!

Rsync client configuration
1.- Download cwRsync (https://itefix.net/content/cwrsync-free-edition) unzip and take the files from /bin/ folder (You don't need to install cwRsync as server).
2.- Make a copy of this files in a known folder for the PATH for example c:\windows or if you are already inside the server via ssh in /cygdrive/c/WINDOWS
3.- Configure your elkarbackup to make a copy of the folders you need. Enjoy!!

Let us know, we already try it and it's working fine ;)

Cheers!

**Comment by nephilim75** [comment]
Hej Antton

the SSH part is done and is working perfectly fine. :-)

I copied all files from CWRSYNC to cygdrive/c/windows/elkarbin folder. Unfortunately I am not aware of how and where to edit the PATH variable. Could you assist me with this as well?

Kind regards
//neph

**Comment by antton** [comment]
As I can't remember now how to do it with cygwin, try copying the files inside elkarbin one directory upper, I know that is not a good idea and less a clean one but just try to try everything is working until I chech how to add more routes into the PATh env. variable.

Cheers

**Comment by nephilim75** [comment]
Once I moved the files to C:\Windows it worked fine. :-)

**Comment by antton** [comment]
As i'm not in front of the computer, could you open bash from the user which you are going to use to get into the windows ssh server, you can do it localy or via ssh, and chech if .bashrc file exist and .bash_profile.

Let me know

**Comment by nephilim75** [comment]
The user I created for the tasks is called "elkar". When checking C:\users\elkar I can see 

```
-rw-r----- 1 elkar Benutzer    181 Mar 22 09:52 .bash_history
-rw-r----- 1 elkar Benutzer   1150 Feb 25  2009 .bash_profile
-rw-r----- 1 elkar Benutzer   3116 Feb 25  2009 .bashrc
-rw-r----- 1 elkar Benutzer   1461 Feb 25  2009 .inputrc
drwxr-x--- 1 elkar Benutzer      0 Mar 22 08:43 .ssh/
```

**Comment by antton** [comment]
Check what the .bashrc has inside

Add  PATH=$PATH:/your/new/path at the end of this file and remove rsync files from windows folder.

You must write /your/new/path in linux format and not msdos.

**Comment by antton** [comment]
Like this
    PATH=$PATH:/cygdrive/c/windows/elkarbin

;)

**Comment by nephilim75** [comment]
It is working perfectly fine. Thank you so much.

Kind regards
//neph

**Comment by nephilim75** [comment]
Closed.

**Comment by antton** [comment]
We need to document the process.

Could you write a line about final steps?

Thanks!!

**Comment by nephilim75** [comment]
Yes, I will do so. But it will take some time.

**Comment by nephilim75** [comment]
Well, here we go. Hope this is OK with you.

[WinSSH.zip](https://github.com/elkarbackup/elkarbackup/files/862734/WinSSH.zip)

Kind regards
//neph

**Comment by antton** [comment]
Hey @nephilim75 

Thank you for the document, we will convert it into markdown and pass into the official documentation.

Thanks again.

**Comment by nephilim75** [comment]
Here are the *.md files:

[WinSSH_md.zip](https://github.com/elkarbackup/elkarbackup/files/867132/WinSSH_md.zip)
*.md files:

**Comment by ffabreti** [comment]
I would like to stress that this method as an advantage of Elkarbackup been authenticated on the Windows client thru the Elkarbackup's public key copied into Windows client.

cwRsync doesn't provide this kind of authentication, as far as I've seen it working.
