### ISSUE TITLE
Editing a user forces a password change

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#210]
Right now, when modifying a user, new password fields are mandatory. They should be optional, maybe we don't know that user's password but want to edit another field - ie email.

**Comment by xezpeleta** [comment]
It's fixed in the upcoming release (v1.2.6)

![screenshot from 2017-06-29 14-14-12](https://user-images.githubusercontent.com/1846038/27686952-440ea0ec-5cd5-11e7-9e43-3ad0bed1e0ed.png)
