### ISSUE TITLE
help needed to understand log

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#211]
Hello

I need some assistance to understand log entry:

<details>
<summary>error log</summary>

```
Befehl "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.3_6.cfg" Weekly 2>&1 fehlgeschlagen. Diagnosehinweis(e): rsync: send_files failed to open "/cygdrive/d/System Volume Information/klmeta.dat": Device or resource busy (16) Number of files: 4,791 (reg: 4,036, dir: 755) Number of created files: 0 Number of deleted files: 0 Number of regular files transferred: 0 Total file size: 11,304,163,191 bytes Total transferred file size: 0 bytes Literal data: 0 bytes Matched data: 0 bytes File list size: 34,730 File list generation time: 0.001 seconds File list transfer time: 0.000 seconds Total bytes sent: 858 Total bytes received: 118,549 sent 858 bytes received 118,549 bytes 8,844.96 bytes/sec total size is 11,304,163,191 speedup is 94,669.18 rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [generator=3.1.1]
```
</details>

<br />

![grafik](https://cloud.githubusercontent.com/assets/19992865/24330751/99c91472-1225-11e7-8fbf-bf25e25e6bd1.png)

What I have done so far is to backup a folder. I can see that it backed up more than 10.5 GB of data. But still receive this log and don't know what is wrong. Do you know?

Kind regards
//neph

**Comment by antton** [comment]
You are trying to copy a file that is in use or locked by the system for different reasons.

That's what the log said!

Antton

**Comment by nephilim75** [comment]
Hej Antton,

thank you for your reply. Is this due to file `/cygdrive/d/System Volume Information/klmeta.dat`?

I can exclude some folder or files from being backed up, right? What is the correct syntax? I added

`/cygdrive/d/System Volume Information`

to exclude field but this generates this log entry:

<details>
<summary> error log </summary>
```
Befehl "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.3_6.cfg" Weekly 2>&1 fehlgeschlagen. Diagnosehinweis(e): Unexpected remote arg: backup@sydewi-ws01:/cygdrive/d rsync error: syntax or usage error (code 1) at main.c(1348) [sender=3.1.1] ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -c /tmp/rsnapshot.3_6.cfg Weekly ---------------------------------------------------------------------------- ERROR: /usr/bin/rsync returned 1 while processing backup@sydewi-ws01:/cygdrive/d
```
</details>

<br />

Any idea what I am doing wrong?

Kind regards
//neph

**Comment by antton** [comment]
It should work with this examples.

http://www.thegeekstuff.com/2011/01/rsync-exclude-files-and-folders/?utm_source=feedburner


Antton

**Comment by xezpeleta** [comment]
The recommended way to escape whitespaces is using the quotation mark: /tmp/Documents?and?Settings

https://github.com/elkarbackup/elkarbackup/wiki/FAQ#can-i-use-directories-with-spaces-in-excludeinclude-option

**Comment by xezpeleta** [comment]
By the way, you also could use shadow volume copy to avoid that problem. Is not properly documented but I guess some people is using it:

https://github.com/elkarbackup/elkarbackup/blob/master/extra/windows/cygwin_vss/ssh-vss.sh

**Comment by nephilim75** [comment]
I tried to backup a whole Windows share (partition) but this run into error due to hidden folder "System Volume Information". By excluding this from job (`System?Volume?Information` added to exclude field) the task got finished without further errors. :-)

Thank you so much guys.

Kind regards
//neph
