### ISSUE TITLE
DB name database not escaped for creation

### ISSUE THREAD

**Issue by peterschen** [elkarbackup/elkarbackup#212]
When creating the database the name is not escaped with backticks. This makes it impossble to create databases which have dashes or other kinds of characters in them which are allowed but need to be escaped.

Doctrine on the other hand will handle this case fine.

**Comment by xezpeleta** [comment]
Thanks @peterschen 

We'll take a look!

**Comment by xezpeleta** [comment]
Hopefully it will be fixed in the next version ;)
