### ISSUE TITLE
debian 8.7 after install reboot needed to run jobs.

### ISSUE THREAD

**Issue by mwacgi** [elkarbackup/elkarbackup#214]
debian 8.7 install elkarbackup follow this instruction :https://github.com/elkarbackup/elkarbackup/wiki/Installation#debian-jessie-80

I've created a client and a job, I click the "Run now", no any logs. After reboot the OS, there're some logs about "RunJobCommand" and "TickCommand".

Why I have to reboot the OS to take elkarbackup effect?

**Comment by xezpeleta** [comment]
You don't need to reboot the computer. Did you reloaded the website?

**Comment by mwacgi** [comment]
I've restarted the service apache2 and mysql, there's no effect.The job can't run until reboot OS.

**Comment by xezpeleta** [comment]
Sorry, but I can't reproduce the problem you have reported with the same OS in a clean installation.

When you "Run now" a job, you just need to wait 1 minute maximum. If you refresh your browser the new status and logs will be there.
