### ISSUE TITLE
Cloning annoyance

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#216]
Hi,

When cloning a client from job list, view is dynamically refreshed with new cloned client and jobs.
If elkarbackup is not installed in root path, new cloned client and jobs links fail (there've missing url).

For example, I have elkarbackup in http://backup/elkarbackup

New entries have URL http://backup/client/5 , but should have http://backup/elkarbackup/client/5

Clicking in "Jobs" main menu fixes the issue.

Cheers
Eneko

**Comment by xezpeleta** [comment]
Thanks! We'll take a look :)

**Comment by xezpeleta** [comment]
This issue has been fixed (PR #225) and it will be ready for the upcoming version v1.2.6

Thanks
