### ISSUE TITLE
Postscript-ek eskuragarri dituzten ingurune-aldagaiak osatu

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#22]
Ondokoak eskura izatea ondo legoke:
ELKARBACKUP_CLIENT_NAME
ELKARBACKUP_JOB_NAME
ELKARBACKUP_JOB_RUN_SIZE (bytes backed up this run)
ELKARBACKUP_JOB_TOTAL_SIZE

**Comment by xezpeleta** [comment]
Ea zer iruditzen zaizun:
ELKARBACKUP_NAME aldagaia gehitu dut. Kontestuaren arabera, bezeroaren izena da edo lanaren izena.

Bestalde, tamainarekin erlazionatutako bi aldagaiak momentuz ez ditut gehitu. Arazoa da scripta exekutatzean oraindik ez dugula datu hau: "du" agindua ondoren exekutatzen baita. Sakonago begiratu beharko da ea hau aldatzeak zer ondorio ekar ditzaken.

**Comment by elacunza** [comment]
Zergaitik konbinatu? Agian job mailan bezeroaren izena ere erabilgarria da?

**Comment by xezpeleta** [comment]
Aldaketa errezagoa delako planteatu dut horrela, baina konbentzitu didazu eta zuk esan bezela jarri dut azkenean:

ELKARBACKUP_CLIENT_NAME
ELKARBACKUP_JOB_NAME

(LEVEL = CLIENT denean, ELKARBACKUP_JOB_NAME hutsik egongo da)

**Comment by xezpeleta** [comment]
Bestalde, hobeto begiratu dut eta "du" komandoa scripta baina lehenago exekutatzen da. Hortaz ELKARBACKUP_JOB_TOTAL_SIZE erraz atera daiteke.

Erreza ez dena da ELKARBACKUP_JOB_RUN_SIZE ateratzea. Okurritzen zait scriptak berak kalkulatu dezakela, TOTAL_SIZE horren pre-script eta post-scriptaren arteko diferentzia ikusita...

**Comment by xezpeleta** [comment]
Ahaztu aurreko mezuan aipatutakoa. Azkenean hori ere gehitu dut.

@parreitu eta @elacunza hemen dituzue egindako aldaketekin hurrengo bertsioan (v1.1.4) eskuragarri egongo diren aldagai berriak (laguntzan ere gehitu dut informazio hau):

ELKARBACKUP_CLIENT_NAME: bezeroaren izena
ELKARBACKUP_JOB_NAME: lanaren izena (hutsik bezeroan)
ELKARBACKUP_OWNER_EMAIL: lanaren arduradunaren email helbidea (hutsik bezeroan)
ELKARBACKUP_RECIPIENT_LIST: lanaren notifikazio email zerrenda (hutsik bezeroan)
ELKARBACKUP_CLIENT_TOTAL_SIZE: bezeroaren tamaina guztira (KB-etan)
ELKARBACKUP_JOB_TOTAL_SIZE: lanaren tamaina guztira (KB-etan)
ELKARBACKUP_JOB_RUN_SIZE: lan exekuzio honetan kopiatutako fitxategien tamaina (KB-etan)

**Comment by elacunza** [comment]
Milesker!

On 23/03/15 23:01, Xabi wrote:
>
> Ahaztu aurreko mezuan aipatutakoa. Azkenean hori ere gehitu dut.
>
> @parreitu <https://github.com/parreitu> eta @elacunza 
> <https://github.com/elacunza> hemen dituzue egindako aldaketekin 
> hurrengo bertsioan (v1.1.4) eskuragarri egongo diren aldagai berriak 
> (laguntzan ere gehitu dut informazio hau):
>
> ELKARBACKUP_CLIENT_NAME: bezeroaren izena
> ELKARBACKUP_JOB_NAME: lanaren izena (hutsik bezeroan)
> ELKARBACKUP_OWNER_EMAIL: lanaren arduradunaren email helbidea (hutsik 
> bezeroan)
> ELKARBACKUP_RECIPIENT_LIST: lanaren notifikazio email zerrenda (hutsik 
> bezeroan)
> ELKARBACKUP_CLIENT_TOTAL_SIZE: bezeroaren tamaina guztira (KB-etan)
> ELKARBACKUP_JOB_TOTAL_SIZE: lanaren tamaina guztira (KB-etan)
> ELKARBACKUP_JOB_RUN_SIZE: lan exekuzio honetan kopiatutako fitxategien 
> tamaina (KB-etan)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/22#issuecomment-85222853>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es
