### ISSUE TITLE
Stretch package

### ISSUE THREAD

**Issue by Rudloff** [elkarbackup/elkarbackup#220]
Hello,
Now that Debian Stretch is stable, are you planning to publish a package for it? (I think the main change is that PHP was updated to 7.0).

**Comment by xezpeleta** [comment]
Hi @Rudloff 

The current package for Ubuntu 16.04 is totally compatible with Debian Stretch, so we don't need to publish a new version.

I updated our APT repository so you can use the following address in your /etc/apt/sources.list.d/elkarbackup.list

```yaml
# Filename: /etc/apt/sources.list.d/elkarbackup.list
deb http://elkarbackup.org/apt/debian stretch main
```

Keep in mind that in Debian Stretch mysql-server (mariadb-server) installation do not ask for a password for root user. You need to configure it for instance using the `mysql-secure-installation` command.

- [ ] TODO: we have to update the [installation help](https://github.com/elkarbackup/elkarbackup/wiki/Installation#debian-jessie-80)

Thanks!

**Comment by Rudloff** [comment]
elkarbackup 1.2.5-php7 indeed works perfectly on Stretch, thanks!
