### ISSUE TITLE
Parameters, Settings and User Preferences

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#236]
I suggest a new way to organize the different configuration options:

## Settings
Stored in the database. Managed by the admin user from the UI.
  - Max log age
  - Quota warning level
  - URL prefix
  - Disable background
  - Scripts directory
  - SSH keys directory
  - Max parallel jobs

## User preferences
Stored in the database. Managed by each user.
  - Language
  - Records per page
  - Change password

## Parameters
Stored in the parameters.yml. Not managed from the UI.
  - database_driver: pd_mysql
  - database_host: localhost
  - database_port: null
  - database_name: elkarbackup
  - database_user: elkarbackup
  - database_password: mypassword
  - mailer_transport: smtp
  - mailer_host: smtp.myorganization.com
  - mailer_user:
  - mailer_password:

**Comment by adrianles** [comment]
I don't think the values in parameters.yml are supposed to change dynamically so not managing them from the UI is probably a good idea.
 
> Define the infrastructure-related configuration options in the app/config/parameters.yml file.
 
from the Symfony [best practices](http://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration)

**Comment by xezpeleta** [comment]
After a period of inactivity I'm here again trying to implement this idea. As we're currently [upgrading to Symfony 3.4](https://github.com/elkarbackup/elkarbackup/tree/feature-symfony34) I thought it could be the ideal moment to move some parameters to the database.

The idea is to use a service which could be called from everywhere (controller, twig templates...):

```php
# Example1: getting a setting (url prefix) from the Controller using a service
$this->get('settings')->getUrlPrefix();
```

```twig
{# Example2: getting a setting (url prefix) from a twig #}
{{ settings.getUrlPrefix() }}
```

Now, how to store the settings in the database?

A simple (and ugly) way comes to mind is to create an entity with *parameters.yml* structure:

```php
/**
 * @ORM\Entity
 */
class Settings
{
    private $urlPrefix;
    private $quotaWarningLevel;
    //...

    // getters / setters
    // ...
}
```

The service will query always the same Settings entity (the only one, id=1) and the settings form will update always that same entity.

Do you have any better alternative?

@adrianles

**Comment by adrianles** [comment]
I agree that some parameters should stay in the parameters.yml file and not be managed using the interface.

As for the parameters stored in the database, creating an entity with many properties will output a single row wilth many columns in the database.
What about creating an entity representing one generic parameter? We could design it with two properties, the ID and the value. The ID would be a unique string and the value would be a string representing the desired value in JSON.

```php
/**
 * @ORM\Entity
 */
class Setting
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $value;

    /**
     * @return mixed
     */
    public function getValue()
    {
        return json_decode($this->value, true);
    }

    /**
     * @param mixed $value
     */
    public function setValue($value): void
    {
         $this->value = json_encode($value);
    }
}
```

This way we can represent every setting in a single row.
The problem might be to choose the correct lenght of the varchar in the database.
In the service we can use constants with the IDs for every parameter and make public methods to get the each value.


```php
class SettingService
{
    const SETTING_ID_URL_PREFIX = 'url_prefix';

    //constructor

    public function getUrlPrefixValue(): string
    {
        return $this->getSetting(SettingService::SETTING_ID_URL_PREFIX)->getValue();
    }

    private function getSetting(string $id): Setting
    {
         return $this->em->find(Setting::class, $id);
    }

    public function setUrlPrefix(string $urlPrefix): void
    {
        $setting = $this->getSetting(SettingService::SETTING_ID_URL_PREFIX);
        $setting->setValue($urlPrefix);
        $this->em->persist($setting);
    }
}
```

What do you think of this aproach?

Cons:
- We cannot set the value in each attribute of the entity (but we can do it in the service)
- We have to keep parsing and decoding from and to Json
- Even if we don't have a big entity class, we will have a big service class

Pros

- We can add more parameters in the future without creating a monster Setting class
- Desing looks a little bit cleaner

**Comment by xezpeleta** [comment]
Your approach is for sure more elegant that my ugly solution :sweat_smile:

If I'm not wrong, you're encoding/decoding the value so that we could set any type of value (string, integer, boolean). I didn't think of that option!

I'll give it a try! I'll keep you updated! Thank you very much!!!

**Comment by adrianles** [comment]
> If I'm not wrong, you're encoding/decoding the value so that we could set any type of value (string, integer, boolean).

Exactly! We can even store arrays if needed.

I was wondering is "name" is a better name than "id" for the Setting unique identifying attribute since it's common to refer to it as the parameter name.

**Comment by elacunza** [comment]
I think we should do 2 separate things:

1. Move "Preferences" (which are user preferences) and "Change password" from the current engine menu to a User profile menu. We must decide what to do with logout buttón (I like it being 1st level...)
2. Rework "Manage parameters" and parameters.yaml following something along the lines @adrianles proposed, so that parameters.yaml just contains DB connection parameters (and then evaluate whether move that to .env.local...)

I you agree, we can create to enhacement issues.

**Comment by xezpeleta** [comment]
I agree, that would be great

**Comment by elacunza** [comment]
I think we can close this now that we have created enhacement issues.
