### ISSUE TITLE
Error saving parameters on a Centos 7

### ISSUE THREAD

**Issue by santxus** [elkarbackup/elkarbackup#237]
Hi 

I have a issue, I'm using Centos 7 and the problem is when i try to change something in the manage parameters . I can not save my preferences, see screenshot attached.

Is strange because i can change root password and email fine. I've tried in two different servers with mysql 5.6 and 7.1 . Another thing is that i can see disable background all the time in the errors, but i don't select this option 

![1](https://user-images.githubusercontent.com/29946498/27906941-74975c64-623d-11e7-89ff-77c139e97e40.png)
![2](https://user-images.githubusercontent.com/29946498/27906942-749d3670-623d-11e7-9ec9-616e4c02fd17.png)

Thank you guys for your job

**Comment by antton** [comment]
Hi @santxus 

Can you check if your parameters.yml

/etc/elkarbackup/parameters.yml

Has the following parameters:

# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: XXX
    database_user: XXX
    database_password: XXX
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: 
    mailer_password: 
    locale: en
    secret: secret
    database_path: null
    upload_dir: /var/spool/elkarbackup/uploads
    backup_dir: /backups
    public_key: /var/lib/elkarbackup/.ssh/id_rsa.pub
    max_log_age: P1Y
    tmp_dir: /tmp
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
    url_prefix: /elkarbackup
    disable_background: false
    mailer_from: null
    tahoe_active: false
    home: /var/lib/elkarbackup

**Comment by santxus** [comment]
Hi mate

# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: elkarbackup
    database_user: elkarbackup
    database_password: XXXX
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fba546d6ab6abc4a01391d161772a14e093c7aa2
    database_path: null
    upload_dir: /var/spool/elkarbackup/uploads
    backup_dir: /var/spool/elkarbackup/backups
    public_key: /var/lib/elkarbackup/.ssh/id_rsa.pub
    max_log_age: P1Y
    tmp_dir: /tmp
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
    url_prefix: null
    disable_background: false
    mailer_from: null
    tahoe_active: false
    home: /var/lib/elkarbackup

This is my file, is locate in /usr/local/elkarbackup/app/config/parameters.yml.

Can i change my parameters here instead of the website?

**Comment by antton** [comment]
Yes you can, but then as you can read here:
https://github.com/elkarbackup/elkarbackup/wiki/FAQ

I've changed 'parameters.yml' but it doesn't work

After editing 'parameters.yml' you must clear the cache:

/usr/share/elkarbackup/app/console cache:clear

**Comment by santxus** [comment]
I edited my file but i don't see Mailer from in my file. Another thing i can not clear the cache because elkarbackup is not existing in cache folder.
I tried to generate the key, i can see in the logs that is successful but the button is not changing to download.

Owner of parameters.yml is apache : apache and permission 664

**Comment by xezpeleta** [comment]
Hi, instead of executing clear:cache command, can you try deleting all the content of app/cache directory?

Thanks

**Comment by santxus** [comment]
Hi Xabi

I deleted all the contetn from /usr/local/elkarbackup/app/cache and now i dont have access to the website, i have error 500. I tried to restart httpd and database but still not working

**Comment by xezpeleta** [comment]
Can you check your permissions?

```
getfacl /usr/local/elkarbackup/app/cache
```

Thanks

**Comment by santxus** [comment]
# file: usr/local/elkarbackup/app/cache
# owner: root
# group: root
user::rwx
group::rwx
other::--x

**Comment by xezpeleta** [comment]
Did you change/create that directory? There is something strange, the installation scripts changes the permissions to the cache directory.

Try to run again the bootstrap.sh script:

```sh
cd /usr/local/elkarbackup/
./bootstrap.sh
```

**Comment by xezpeleta** [comment]
You also should check the logs (app/logs). Can you see any error?

**Comment by santxus** [comment]
I'm going to delete the VM and creating again the next week. I will follow
centos 7 instructions for the website I will keep your updated. Thanks guys

2017-07-07 13:24 GMT+01:00 Xabi <notifications@github.com>:

**Comment by santxus** [comment]
Hi guys

Again i just reinstall this software in Centos 7 with the same result, I try in Ubuntu and is working perfectly.

Obviously I tried to remove all the content in Cache folder but the same error.

**Comment by antton** [comment]
We would have to check centos to fix this kind of bugs.

As soon as I take time I will do it and let you know.

Sorry for that.

Antton

**Comment by santxus** [comment]
Thank you for your job, is great !

**Comment by muaddiib** [comment]
CentOS 7
/etc/elkarbackup/ not exist (i make symlink)
/usr/share/elkarbackup/ not exist (symlink from /usr/loca/elkarbackup)
/var/lib/elkarbackup/.ssh/ not exist (symlink from /usr/loca/elkarbackup/keys/)

The script stopped working on CentOS completely.

**Comment by elacunza** [comment]
We're removing support for script-based installation con Centos in upcoming v1.4.0. I suggest you change to docker image, which will be much easier to maintain and upgrade.

Thanks
