### ISSUE TITLE
Elkarbackup stuck / big amount of data

### ISSUE THREAD

**Issue by spysz** [elkarbackup/elkarbackup#240]
Hi people ;-)

Right now I have 1.2.6 version but this problem from this:
https://github.com/elkarbackup/elkarbackup/issues/221 still occurs.

Shortly before end the job, the job has state RUNNING. 

Log:
`[2017-07-22 09:05:20] BnvWeb.ERROR: Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.1_19.cfg" Weekly 2>&1 failed. Diagnostic information follows: {"source":"RunJobCommand","link":"/client/1/job/19"} [2017-07-22 09:05:20] BnvWeb.ERROR: Exception An exception occurred while executing 'SELECT t0.description AS description_1, t0.id AS id_2, t0.name AS name_3, t0.isClientPre AS isClientPre_4, t0.isJobPre AS isJobPre_5, t0.isClientPost AS isClientPost_6, t0.isJobPost AS isJobPost_7, t0.lastUpdated AS lastUpdated_8 FROM Script t0 INNER JOIN JobScriptPost ON t0.id = JobScriptPost.script_id WHERE JobScriptPost.job_id = ?' with params [19]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away running command {"command":"elkarbackup:run_job","client":"1","job":"19"}: {"source":"TickCommand","link":"/client/1/job/19"} [2017-07-22 09:05:20] BnvWeb.ERROR: Exception running queued commands: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away {"source":"TickCommand"}`

Any idea how to resolve this problem in the last release of elkarbackup?

Thank you!

Regards,
Simon

**Comment by xezpeleta** [comment]
Hi @spysz 

What's your Linux distribution/version?
Can you check your _mysql.ini_ ?

```
wait_timeout
max_allowed_packet
```

Maybe you can retry with a higher value

**Comment by antton** [comment]
Hi!

It looks like if you modify wait_timeout parameter you shold change as well interactive_timeout.

Check the following forum threat.

https://stackoverflow.com/questions/33250453/how-to-solve-general-error-2006-mysql-server-has-gone-away

Antton

**Comment by spysz** [comment]
Hi,

I use Debian 9.0 / stretch. 

So, I added to: /etc/mysql/mariadb.conf.d/50-server.conf this line:
`[mysqld]
max_allowed_packet      = 256M
wait_timeout            = 28800
interactive_timeou      = 28800`

Do you think that it should work now?

p.

**Comment by antton** [comment]
No we don't! That's what we need to check ;)

Let us know!

Antton

**Comment by spysz** [comment]
Yes, right! 

So, I will check this. But due to low network between elkarbackup and machine which I want to backup it may take at least 24h. 

I will inform you as soon as possible. 

Regards,
Simon

**Comment by antton** [comment]
Thanks!

Antton

**Comment by spysz** [comment]
Hi. 

Unfortunately, I don't have very good news. The jobs was stuck again very shortly before end. 
Any sugestions?

Regards,
Simon

**Comment by antton** [comment]
Morning Simon!

The same mysql error on the log files?

Let us know.

Antton

**Comment by spysz** [comment]
Hi,

The same error as previous:

`[2017-07-26 08:04:06] BnvWeb.ERROR: Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.6_19.cfg" Hourly 2>&1 failed. Diagnostic information follows:   {"source":"RunJobComma
nd","link":"/client/6/job/19"}  
[2017-07-26 08:04:07] BnvWeb.ERROR: Exception An exception occurred while executing 'SELECT t0.description AS description_1, t0.id AS id_2, t0.name AS name_3, t0.isClient
Pre AS isClientPre_4, t0.isJobPre AS isJobPre_5, t0.isClientPost AS isClientPost_6, t0.isJobPost AS isJobPost_7, t0.lastUpdated AS lastUpdated_8 FROM Script t0 INNER JOIN
 JobScriptPost ON t0.id = JobScriptPost.script_id WHERE JobScriptPost.job_id = ?' with params [19]:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away runni
ng command {"command":"elkarbackup:run_job","client":"6","job":"19"}:  {"source":"TickCommand","link":"/client/6/job/19"}  
[2017-07-26 08:04:07] BnvWeb.ERROR: Exception running queued commands: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away {"source":"TickCommand"} `

Hm, just to be sure in 100%:

`max_allowed_packet      = 256M
wait_timeout            = 28800
interactive_timeout     = 28800
`
I added to this options connectio_timeout = 28800 and I will try again. 
Should I change something in php.ini for apache? 

p.

**Comment by antton** [comment]
You don't need to modify anything in your php.ini or even apache configuration.

Look at your sentence that your write wrong the connection_timeout you forget the n at the end of the word connection ;)

Take care!

Antton

**Comment by spysz** [comment]
Hi,

I know, but in config file is correct. Ok, so I added this option and now I am checking. I will let you know.

p.

**Comment by spysz** [comment]
OK. So far it is working. :)

Regards,
Simon

**Comment by antton** [comment]
We will take a note on the wiki ;)

Cheers!

Antton

**Comment by varuzam** [comment]
Maybe, it is better option to connect to Mysql when it is needed instead of keeping the connection during backup. It will resolve the problem.
