### ISSUE TITLE
If job fails, post script is not executed

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#241]
Just noticed that if a job fails, its post script is not executed.

This is a problem if pre script does a mount and post must do an umount.

**Comment by elacunza** [comment]
This may also be another problem.

It seems, that sometimes when checking pre and post scripts in a job and saving the job, the post script is not correctly saved. I'll be doing more tests and will report back.

**Comment by xezpeleta** [comment]
Hi @elacunza 

> Just noticed that if a job fails, its post script is not executed.
> This is a problem if pre script does a mount and post must do an umount.

That behavior is intended. Rsnapshot cmd_postexec works in a similar way:

https://github.com/rsnapshot/rsnapshot/blob/master/rsnapshot-program.pl#L6754

However, what you say makes sense to me. As opposed to Rsnapshot, in ElkarBackup we can read the ELKARBACKUP_STATUS envar from our script to check if the job finished correctly.

**Comment by xezpeleta** [comment]
I'm closing this issue. It has been included as a configurable option (post_on_pre_fail: true) in PR #273
