### ISSUE TITLE
Import / export settings to xml/text (something git likes)

### ISSUE THREAD

**Issue by fredleb** [elkarbackup/elkarbackup#243]
A lot of my jobs are pretty similar to one another and cut and paste can hide problems. I also use elkarbackup via docker in several instances... It quickly becomes tedious to copy lines from a quickly lost scratch file into a web interface.

It would be helpful to be able to import and export clients and jobs via text, yml, xml files, something that can be kept in git.

Otherwise: great job !

**Comment by fredleb** [comment]
It would also help when reporting bugs !

**Comment by elacunza** [comment]
This may be related to #260 too

**Comment by elacunza** [comment]
Could be part of a CLI program that uses new API projected for v1.6.0

**Comment by elacunza** [comment]
@uanabitarte  is working on this in https://github.com/elkarbackup/elkarbackup-api-cli
