### ISSUE TITLE
Downloading a file from a backup limited by system RAM

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#246]
Just noticed the following:
- Elkarbackup running in a 512MB RAM VM
I tryed to download (restore) a 500MB TGZ from a backup job, but it failed.

Apache/PHP logs say
PHP Fatal error:  Out of memory (allocated 473694208) (tried to allocate 458236775 bytes) in /usr/share/elkarbackup/app/bootstrap.php.cache on line 1543, referer: http://elkarbackup/client/2/job/8/backup/view//Daily.0/

Increasing VM's RAM to 1GB made it.

We should change this one-file-download logic so that it works the same way as TGZ downloads.

**Comment by xezpeleta** [comment]
> We should change this one-file-download logic so that it works the same way as TGZ downloads.

What do you mean? What is the best solution in your opinion?

**Comment by elacunza** [comment]
Ah I see, what a bad description, my fault! :)

The TGZ file I downloaded was a single file backed up by elkarbackup, not a TGZ file created to download all the files in a job.

Currently the logic to download a single file of a backup job, and the logic to download the generated TGZ file for all files in a job is different. The former is limited by system RAM, the later not.

I suggest we should use for both cases the not-limited-by-RAM method.

**Comment by xezpeleta** [comment]
Thanks, it will be fixed on v1.2.7
