### ISSUE TITLE
Paso de la tarea a Inactivo

### ISSUE THREAD

**Issue by jaymami** [elkarbackup/elkarbackup#247]
Hola amigos,

He detectado que cuando pasas una tarea a inactiva el valor de limite de quota se pone a 0.

Saludos,
Josep

**Comment by xezpeleta** [comment]
Hola @jaymami 

¿Puedes confirmarme el valor de cuota que tienes configurado?

He podido reproducir el bug que comentas, pero únicamente si especifico una cuota menor de 1GB. ¿Puedes confirmarlo?

Gero arte

**Comment by xezpeleta** [comment]
No he podido reproducir el problema en la versión actual. Ni siquiera con cuotas inferiores a 1GB.

Por lo tanto, de momento cierro esta incidencia.
