### ISSUE TITLE
how can restore?

### ISSUE THREAD

**Issue by ang3lx** [elkarbackup/elkarbackup#248]
Hello
I've setting up server and clients.. but if I would restore, how can I do it?
There are commands to use from shell to restore a backup?

thanks!

**Comment by xezpeleta** [comment]
Hi @ang3lx 

Sorry for the delay in replying. You have basically two options to restore your data from ElkarBackup:

1. Using the web UI, you can browse your backups with the "Restore" button. You can download a file or a directory to your computer.
2. Using the CLI, you can access to the storage volume / directory (by default it's "/var/spool/elkarbackup/backups"). Then, you can copy use your preferred method to restore your data to other server: rsync, scp, sftp, etc...

Thanks
