### ISSUE TITLE
Error in log is truncated

### ISSUE THREAD

**Issue by Rudloff** [elkarbackup/elkarbackup#250]
Hello,

I'm using elkarbackup 1.2.6-php7 on Debian 9.1.

One of my backup fails for some reason and the error log seems to be truncated so I can't see the error.

Here is one of the e-mails I received:
```
Client | Job | Time | Level | Message
-- | -- | -- | -- | --
local | www | 2017-09-18 21:05:56 | ERROR | Command "/usr/bin/rsnapshot" -V -c "/tmp/rsnapshot.1_2.cfg" sync 2>&1 failed. Diagnostic information follows:  Setting locale to POSIX "C" echo 27314 > /tmp/rsnapshot.0001_0002.pid /usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded \     --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats --exclude=phpdoc-cache-* \     --exclude=/home/pierre/www/archi-wiki/images/** \     --exclude=platforms/android/build/ --exclude=.sass-cache/ \     --exclude=node_modules/ --exclude=smarty/compile/ \     --exclude=popcorn-desktop/cache/ --exclude=popcorn-desktop/build/ \     --exclude=mfc/cache/ --exclude=m
local | www | 2017-09-18 21:05:56 | ERROR | Client "1", Job "2" error.
local | www | 2017-09-18 21:05:56 | ERROR | FAIL

**Comment by Rudloff** [comment]
I tried to delete the backup folder and restart the backup from scratch but I still get a truncated error for this specific job.
Is there any way to get the full rsnaphot output?

**Comment by xezpeleta** [comment]
Hi @Rudloff 

Sorry for the delay. This is a "collateral damage" caused by a fix introduced in the last version. Long output log was causing problems with MySQL: https://github.com/elkarbackup/elkarbackup/issues/221#issuecomment-311935529

We'll take a look to this. The best option could be to have a complete log in a logfile, but not in the DB.

Meanwhile, I suggest you to debug your issue running the Rsnapshot command manually with that [job config](https://github.com/elkarbackup/elkarbackup/wiki/FAQ#is-there-a-way-to-see-the-generated-rsnapshot-configuration-file).

Thanks

**Comment by Rudloff** [comment]
Thanks for the tip about the config, it's pretty useful.

However, when I run `rsnapshot sync` manually with this config file it works without any error:
```
Number of files: 717,349 (reg: 582,827, dir: 114,896, link: 19,625, special: 1)
Number of created files: 141 (reg: 124, dir: 15, link: 2)
Number of deleted files: 3 (reg: 2, dir: 1)
Number of regular files transferred: 589
Total file size: 26,262,966,040 bytes
Total transferred file size: 446,984,422 bytes
Literal data: 446,984,422 bytes
Matched data: 0 bytes
File list size: 3,079,695
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 471,426,627
Total bytes received: 2,276,145

sent 471,426,627 bytes  received 2,276,145 bytes  1,478,011.77 bytes/sec
total size is 26,262,966,040  speedup is 55.44
touch /media/pierre/Backup/elkar//0001/0002/.sync/ 
rm -f /tmp/rsnapshot.0001_0002.pid 
/usr/bin/logger -p user.info -t rsnapshot[22175] /usr/bin/rsnapshot -V -c \
    rsnap.config sync: completed successfully 
```
So I'm a bit confused.

**Comment by Rudloff** [comment]
Duh, I wasn't running it with the elkarbackup user. Running rsnaphost with the correct revealed a permission issue.

**Comment by xezpeleta** [comment]
I'm glad.

I'm gonna keep this issue open until we fix the truncated log problem

**Comment by xezpeleta** [comment]
#257
