### ISSUE TITLE
/bin/rm: cannot remove files/directories

### ISSUE THREAD

**Issue by fredleb** [elkarbackup/elkarbackup#251]
All of my jobs fail with the same error:
Example 1:
`Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.1_5.cfg" Daily 2>&1 failed. Diagnostic information follows: /bin/rm: cannot remove '/var/spool/elkarbackup/backups/0001/0005/Daily.4/home/http/owncloud/panda/lib/dokuwiki.git/.git/branches': Permission denied /bin/rm: cannot remove '/var/spool/elkarbackup/backups/0001/0005/Daily.4/home/http/owncloud/panda/lib/dokuwiki.git/.git/hooks/applypatch-msg.sample': Permission denied /bin/rm: cannot remove '/var/spool/elkarbackup/backups/0001/0005/Daily.4/home/http/owncloud/panda/lib/dokuwiki.git/.git/hooks/commit-msg.sample': Permission denied `

But it looks liks:
`dr-xr-xr-x 1 105 110    0 Feb 23  2015 branches` (size 0 maybe the problem ?)
`-r-xr-xr-x 6 105 110 452 Feb 23  2015 applypatch-msg.sample` (not size 0...)

Example 2
`Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.1_6.cfg" Daily 2>&1 failed. Diagnostic information follows: /bin/rm: cannot remove '/var/spool/elkarbackup/backups/0001/0006/Daily.4/var/lib/nfs/rpc_pipefs/cache': Permission denied /bin/rm: cannot remove '/var/spool/elkarbackup/backups/0001/0006/Daily.4/var/lib/nfs/rpc_pipefs/gssd/clntXX/gssd': Permission denied /bin/rm: cannot remove '/var/spool/elkarbackup/backups/0001/0006/Daily.4/var/lib/nfs/rpc_pipefs/gssd/clntXX/info': Permission denied`

`prw------- 6 105 110  0 Oct  7 12:18 gssd`
`-r-------- 1 105 110  0 Aug 18 17:07 info`

I use elkarbackup inside the docker and my backup data are on the host system (arch + btrfs)

I first thought their was a owner problem, but docker output says the elkarbackup user and groups are created with these IDs.

Then I thought it could have something to do with some targets being of size 0 but the command fails on files with a non zero size too.

Any idea ?

**Comment by fredleb** [comment]
OK I have found some answer:

https://github.com/rsnapshot/rsnapshot/issues/160

But then I really don't know how to solve it using elkarbackup in a docker...

**Comment by xezpeleta** [comment]
Hi @fredleb 

Can you check if you have the right permissions on your backup storage?

https://github.com/elkarbackup/elkarbackup/wiki/FAQ#restore-button-is-disabled-or-it-doesnt-work-i-have-an-error-404-not-found

**Comment by fredleb** [comment]
Hi,

Well I guess that's the problem: because nobody has write permission on some files (remote and resulting storage), rm can only remove the files if run by root...

But I guess this is a problem for all sysadmin who will want to backup a full system : in the docker, because the rsnapshot is run as a non-privileged user, these files cannot be handled...

One solution would be to run rsnapshot as root or via sudo, but:

- is that possible from elkarbackup ?

- what are the security risks then ?

**Comment by xezpeleta** [comment]
> Well I guess that's the problem: because nobody has write permission on some files (remote and resulting storage), rm can only remove the files if run by root...

Why do you have some files without write permissions? Are you using custom Rsync args? Did you run your backup manually from CLI instead of web interface?

Thanks

PD: I'm using an external NFS storage without problems, with the right permissions (acl's enabled).

**Comment by fredleb** [comment]
My systems are all running arch linux.

On all of the systems running a NFS 4 server I have this file:
`-r-------- 1 root root 0 Oct 10 13:27 /var/lib/nfs/rpc_pipefs/gssd/clntXX/info`

The following case looks like a user mistake, but still, it should backup and restore I guess:
`dr-xr-xr-x  2 http http   4096 Feb 23  2015 branches` (in /home/http/owncloud/panda/lib/dokuwiki.git/.git)

I am not using custom rsync args except -x

I only used the web interface.

So the backup is correct: it reflects exactly what is on the machine. But these permissions make it impossible to remove the file after.

That's gonna be hard to solve really. Running the rm as root is a bit drastic and I am not sure it is possible at all without runing rsnapshot as root too, which is even worse...

A shame that rsnapshot is in perl, I would have had a look too...

**Comment by xezpeleta** [comment]
Are you mounting your NFS from your ElkarBackup container or from your arch linux host?

**Comment by fredleb** [comment]
I am not using NFS at all in that context.

The servers I back up run an NFS server.

The backup is made on a local (to the elkarbackup server) partition.

**Comment by fredleb** [comment]
rsnapshot is no longer developed so I will switch to another solution. You may close this issue if you wish.

**Comment by antton** [comment]
It looks like, but rsync even has it last update 4 years now and still it works like a charm. Let us know which solution you choose and we will try to have a look as well!

**Comment by parreitu** [comment]
SMTP with username and password
