### ISSUE TITLE
future of rsnapshot

### ISSUE THREAD

**Issue by m-osmani** [elkarbackup/elkarbackup#252]
hello,

after reading https://github.com/rsnapshot/rsnapshot/issues/191 I am worried that rsnapshot will be dead in future.

do you have an opinion ?

**Comment by xezpeleta** [comment]
Hi @m-osmani 

We're aware of Rsnapshot current status. Even so, we think it's not all that bad:
- Rsnapshot is a useful software tool and it's very stable. We don't need a lot of improvements every year to continue using it.
- A similar example could be Rsync: last stable version is from 2015. Anyway, it's still a powerful tool and it will continue to be.
- Rsnapshot has a wide users community. They're still contributing to the project (last commit was september 7th)
