### ISSUE TITLE
Requested feature: ensure storage is online and is writeable

### ISSUE THREAD

**Issue by vassiskansa** [elkarbackup/elkarbackup#253]
Hi,
i've an issue with queue.
Seems that my backup server has problems with one mounted partition. When this problems appear, and many backup jobs run, the queue stops.
See screenshot attached.
![2017-10-15 11_39_43-elkarbackup](https://user-images.githubusercontent.com/13942399/31583573-93f55e2a-b19e-11e7-8781-3a25783a7197.png)

To restart job i must enter with ssh and launch them manually.
Thank you.

**Comment by xezpeleta** [comment]
Hi @vassiskansa 

ElkarBackup needs a working backup storage. If it fails, the backup process will probably fail too. That's why you had these problems.

I'll keep this issue open as an enhancement idea for a future update.

Thanks

**Comment by vassiskansa** [comment]
Yes, I know... but the queue rest in "Queued", not in "Error", and I had to restart by hand from the command line.

**Comment by xezpeleta** [comment]
Ok, we will check that forcing an unmount in a testing update. We'll keep you updated.

Thanks!!

**Comment by vassiskansa** [comment]
Caution. My resource was not completely disassembled but the system could not write (eg. I / O error). For tests maybe it would be better to check that user elkarbackup can write in?!?
Thank you too!

**Comment by Igortxete7** [comment]
Hello @vassiskansa 
I have made a simple test removing write permissions and Elkarbackup correctly solves the issue.
Could you give me more details about your problem?
For example if rsnapshot is on execution when the error happens or if it has some error.

Thank you!
