### ISSUE TITLE
Quest about Elkarbackup regular working

### ISSUE THREAD

**Issue by vassiskansa** [elkarbackup/elkarbackup#254]
Hi,
I would need a clarification on the basic operation of elkarbackup. I read the various faqs but did not find the answer. I set this default policy: Daily -> Mon to Sat, 6 copies + Weekly -> only Sun, 4 copies.
I started backing up last week on Wednesday. Since no backup has been made last Sunday, does the weekly need to have a complete daily cycle to be performed or is there another problem?
Thank you.

**Comment by xezpeleta** [comment]
There must be another error. Elkarbackup (Rsnapshot) will start first from the lowest backup level (Daily). So if it didn't create Daily.0, probably something is not well configured.

**Comment by vassiskansa** [comment]
In practice I found myself in this situation: on Sunday morning storage was unmounted, so I fix the problem and I restart jobs, but backup continued to create Daily.0 as I would have to create Weekly.0 as it was Sunday. Right?

**Comment by xezpeleta** [comment]
First of all, it will need to have previous level backups (all of them), as it will use your oldest Daily (Daily.5 in your example) to create your first Weekly.0

I would wait one week to check if everything is working well.

**Comment by vassiskansa** [comment]
Okay, maybe that's how I thought. Can we keep the tread open until next Monday?

**Comment by xezpeleta** [comment]
Sure!

Tell us if it's working well :)

**Comment by vassiskansa** [comment]
Hi xezpeleta,
I don't know if you have already read my newer post?
https://github.com/elkarbackup/elkarbackup/issues/201
It's possible to have a chat support with you?

**Comment by xezpeleta** [comment]
Hi @vassiskansa , at the moment I'm really busy and I would prefer to continue to use Github Issues. We will try to help you as soon as I can.

On the other hand, ElkarBackup does not currently support preserving files ownership, as the only way to do that is to run Rsnapshot as root. You can try to do it following these advices from other Elkarbackup users, but we can't help you with that, sorry.

Thanks

**Comment by vassiskansa** [comment]
Hi @xezpeleta , thank you for reply. I've tried to run elkarbackup cron as root but it doesn't work for me, as i've just described in #201 post...

**Comment by xezpeleta** [comment]
Sorry, as I said before, that's not currently supported by Elkarbackup
