### ISSUE TITLE
 Añadir parametro 'rsync -T' en configuracion de ElkarBackup

### ISSUE THREAD

**Issue by jesusgascon** [elkarbackup/elkarbackup#255]
Hola buenas,

En la Wiki del proyecto comentan aqui la opcion de añadir '-T' como parametro de rsync en Ubuntu/Debian   [https://github.com/elkarbackup/elkarbackup/wiki/Performance](https://github.com/elkarbackup/elkarbackup/wiki/Performance)  para mejorar el rendimiento.

En esta url puede ver la configuración [http://127.0.0.1/elkarbackup/client/1/job/1/config](http://127.0.0.1/elkarbackup/client/1/job/1/config) pero no cambiarla. Se puede modificar esta configuración de ElkarBackup para añadir este parámetro de rsync? 

Otra opcion es crear un alias de 'rsync' con este parámetro ya puesto por defecto, pero se podría hacer en ElkarBackup directamente?

Saludos

_____

Good morning,

In the wiki of the project,it's talked about the option to add '-T' as parameter of rsync in Ubuntu/Debian https://github.com/elkarbackup/elkarbackup/wiki/Performance in order to improve the performance.

In this url you can see the configuration  http://127.0.0.1/elkarbackup/client/1/job/1/config but not change it. It is possible to modify this configuration of ElkarBackup to add this parameter of rsync?

Other option could be to create an alias of 'rsync' with this parameter put it by default, but could be done in Elkarbackup directly?

Looking forward to hearing from you

Best regards,

**Comment by xezpeleta** [comment]
Hi @jesusgascon 

Yes you can use your custom Rsync parameters from the web UI:

`Client configuration - Advanced - Rsync short args`
