### ISSUE TITLE
Rsync output on log entries on default Debian 9 installation

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#257]
Debian 9
Elkarbackup 1.2.6-php7

This is a installation from scratch, done last week.

We're seeing full rsync output in Logs view on web interface.

I have checked rsnapshotconfig.txt.twig template, and verbose is 2 and loglevel 3, which seems correct and should not output rsync output...

**Comment by elacunza** [comment]
Just checked against a non-verbose elkarbackup installation with same debian9 and elkarbackup packages.

Rsync and rsnapshot packages are equal:
rsync 3.1.2-1
rsnapshot 1.4.2-1

Yet, the old installation is not verbose but the new one is.

**Comment by launtony** [comment]
+1 :) I have the same problem on the log errors send by email :)

**Comment by xezpeleta** [comment]
@elacunza if the job fails, it outputs the full rsync log. That's why the output was limited to 500 characters on v1.2.6 as a vital workaround to avoid MySQL errors...

Can you check if your `BackupRunningCommand.php` is the good one?

```sh
$ md5sum src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php
d63e50a88ff142252cddd14ec156fbff  src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php
```

**Comment by elacunza** [comment]
Yes, it is the one you say.

We have changed rsnapshotconfig.txt.twig file loglevel to 2 (was 3) to fix this.

**Comment by xezpeleta** [comment]
So should we change it to 2 by default?

**Comment by elacunza** [comment]
I don't see that param has been changed lately, so the real issue must be elsewhere. Also, that file is a template, not a config file...

Maybe the 500 char limit introduced in v1.2.6 is not working correctly?

**Comment by elacunza** [comment]
Ok, looking at the code, I think the problem is that we're capturing the output directly to a PHP string. That limit's the captured output size to PHP's memory_limit; if rsync output is larger, then php process will crash.

I think we should do one of:
* Redirect output to a file, then read that file (first/list 500 chars, whatever)
* Change output log level to 2, but maintain the file log level at 3. Then parse file log levels for details if necessary.

I don't really think we need the log of all rsynced files in elkarbackup web interface, and that info wasn't showing in previous versions?

**Comment by elacunza** [comment]
Sorry for the mess.

What I don't understand yet, is why I get the long output in the new Debian 9/Elkarbackup 1.2.6 server, but not in the old upgraded to Debian9/Elkarbackup 1.2.6 .

log in upgraded server:
Command "/usr/bin/rsnapshot" -V -c "/tmp/rsnapshot.5_9.cfg" sync 2>&1 succeeded with output: Number of files: 9 (reg: 7, dir: 2) Number of created files: 1 (reg: 1) Number of deleted files: 0 Total transferred file size: 25,871,969 bytes

log in new server:
Command "/usr/bin/rsnapshot" -V -c "/tmp/rsnapshot.1_1.cfg" sync 2>&1 succeeded with output: Setting locale to POSIX "C" echo 25251 > /tmp/rsnapshot.0001_0001.pid /usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded \ --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats --rsh=/usr/bin/ssh -o \ BatchMode=yes -o StrictHostKeyChecking=no \ root@ficheros.cliente.local:/srv/datos1/grupos/congresos \ /var/spool/elkarbackup/backups/0001/0001/.sync/. receiving incremental file list [...STRIPPED LOTS OF FILES AND DIRECTORIES...] Number of files: 100,414 (reg: 92,615, dir: 7,799) Number of created files: 8 (reg: 7, dir: 1) Number of regular files transferred: 20 Total file size: 261,233,967,770 bytes Total transferred file size: 5,666,840 bytes Literal data: 1,172,648 bytes Matched data: 4,494,192 bytes File list size: 2,379,936 File list generation time: 0.001 seconds File list transfer time: 0.000 seconds Total bytes sent: 29,710 Total bytes received: 4,771,093 sent 29,710 bytes received 4,771,093 bytes 110,363.29 bytes/sec total size is 261,233,967,770 speedup is 54,414.64 touch /var/spool/elkarbackup/backups/0001/0001/.sync/ rm -f /tmp/rsnapshot.0001_0001.pid /usr/bin/logger -p user.info -t rsnapshot[25251] /usr/bin/rsnapshot -V -c \ /tmp/rsnapshot.1_1.cfg sync: completed successfully Number of files: 100,414 (reg: 92,615, dir: 7,799) Number of created files: 8 (reg: 7, dir: 1) Number of regular files transferred: 20 Total file size: 261,233,967,770 bytes Total transferred file size: 5,666,840 bytes Literal data: 1,172,648 bytes Matched data: 4,494,192 bytes File list size: 2,379,936 File list generation time: 0.001 seconds File list transfer time: 0.000 seconds Total bytes sent: 29,710 Total bytes received: 4,771,093 sent 29,710 bytes received 4,771,093 bytes 110,363.29 bytes/sec total size is 261,233,967,770 speedup is 54,414.64 touch /var/spool/elkarbackup/backups/0001/0001/.sync/ rm -f /tmp/rsnapshot.0001_0001.pid /usr/bin/logger -p user.info -t rsnapshot[25251] /usr/bin/rsnapshot -V -c \ /tmp/rsnapshot.1_1.cfg sync: completed successfully

**Comment by xezpeleta** [comment]
Auch, ok. Now I see:

When a job ends successfully, we're capturing some data from the output to Elkarbackup log (Number of files, Number of created files, etc). We use only that specific information from the output to summarize the job. Well, that's at least the expected behaviour, aka your "upgraded server".

BUT if for some reason we can't parse any of these values, then the full output will be redirected to the Elkarbackup log.

1-2 years ago we added "-V" to rsnapshot command and "--stats" to rsync_long_args so we could obtain more information from rsnapshot command as number of created files, deleted files, etc.

As you said, even if we can easily fix this bug to avoid the full log, we can still have problems in the future if the php process crash due to memory limit.

So the best solution could be to create a temporary log file. If the job ends successfully, we use it to obtain all the stats and then we delete it. If the job fails, we can store it somewhere as it can help for debugging.

**Comment by elacunza** [comment]
Ok, I think I understand now, there are really 2 issues:

1. If rsnapshot output is very long, we hit PHP memory_limit and process crashes. This happened on our first run.

This problem must be fixed limiting rsnapshot output to stdout/stderr . We found that we can achieve this changing rsnapshot config parameter "loglevel 3" to "loglevel 2". Docs say that config affects the log file output, but it seems that as there isn't any log file in the configuration, then affects stdout/stderr verbosity.

We should explore uncommenting logfile value and setting it for example to /var/log/elkarbackup/rsnapshot.log (this file should be logrotated) or maybe some file with client-job ids.

This should leave us with "verbose 2" level in rsnapshot stdout/stderr, which should be short enough for our purposes? Also we would have long output for debug/etc in the associated logfile.

2. When command is sucessful, script enters  elkarbackup/src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php:216 , if we fail data parsing on the output, all the output is logged, and not the regular short stats message.

To fix the second issue, we can look at why the parsing is not working. Also, we may just write to DB log the last N rows of output, those that usually have the stats info?

**Comment by xezpeleta** [comment]
I've enabled rsnapshot logfile but apparently it doesn't include the rsync stats or any useful error information.

Apparently the best way to get that information is redirecting the command's output to a file. Example:

```php
# if sync first is enabled...
$commands[] = sprintf('"%s" -V -c "%s" sync > /tmp/rsnapshot-%s-%s.log 2> /dev/null', $rsnapshot, $confFileName, $clientid, $jobid);
# ...
```
- If it success, we can read the stats from the last 20 lines of that file (improving the current parsing code)
- If it fails, we can try to find the exact error message so the user would see a clear error: host not found, connection dropped, permission issues etc
