### ISSUE TITLE
Mensaje de error no aporta información sobre el problema real ocurrido cuando falla rsync

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#26]
Cuando falla el comando rsync, la información que se aporta no sirve para diagnosticar el problema. Indica el fichero temporal que se ha usado para invocar rsnapshot pero no sirve de ayuda; sería interesante que cuando se detecte que el comando ha fallado se adjunte los contenidos del fichero temporal de rsnapshot para poder reproducir el problema y hacer un diagnóstico más fácilmente.

servidor2   Share personales    2013-11-21 21:00:04     ERROR  
Command "/usr/bin/rsnapshot" -c "/tmp/rsnapshot.1_2.cfg" sync 2>&1 failed. Diagnostic information follows: Unexpected remote arg: servidor2.intranet.illargi.com::personales rsync error: syntax or usage error (code 1) at main.c(1232) [sender=3.0.9] ---------------------------------------------------------------------------- rsnapshot encountered an error! The program was invoked with these options: /usr/bin/rsnapshot -c /tmp/rsnapshot.1_2.cfg sync ---------------------------------------------------------------------------- ERROR: /usr/bin/rsync returned 1 while processing servidor2.intranet.illargi.com::personales
servidor2   Share personales    2013-11-21 21:00:05     ERROR  
Client "1", Job "2" error.
servidor2   Share personales    2013-11-21 21:00:05     ERROR   FAIL

**Comment by xezpeleta** [comment]
Se me ocurren dos posibles acciones:
* En el mensaje de error, convertir "/tmp/rsnapshot.1_2.cfg" en un link, que apunte hacía la dirección `http://*/job/2/config`
* Probar a subir el parametro `verbose` de RSnapshot para ver si obtenemos más detalles del error de RSync

**Comment by xezpeleta** [comment]
#257

**Comment by xezpeleta** [comment]
A partir de la v1.2.7 se muestra información de debug cuando una tarea falla.
