### ISSUE TITLE
API for everything 

### ISSUE THREAD

**Issue by flix444** [elkarbackup/elkarbackup#260]
Hi, 
a API for add a new client or everything else  would be great.
Because automate tool could use the api. 

regads Felix

**Comment by xezpeleta** [comment]
I agree. It's in the roadmap.

Thanks!

**Comment by adrianles** [comment]
What are we looking for here?

I guess these should be the entities we could aim for:
- Users
- Clients
- Jobs
- Policies
- Scripts

Should we start with the user management? I'm willing to give it a try. What do you think @xezpeleta ?

**Comment by xezpeleta** [comment]
That would be great! We only need a little push to start.

I have some questions about where to start, etc. I may contact you!

**Comment by metzgerd** [comment]
Return status (OK, Failed, ...) of all jobs / per job. This can be used by monitoring systems. (zabbix, nagios, ...)

Also what I'm doing is to touch a file (with pre job command) on the host and check if the timestamp on the backup folder has changed. May be a api could report the timestamp of a file on the backup.

**Comment by avekrivoy** [comment]
@elacunza is there a way right now to automate addition of new server through command line/ adding config files?

**Comment by elacunza** [comment]
We are working on it:
- #493 
- #494
- #498 
- github.com/elkarbackup/ansible-collection-elkarbackup

Master branch has some REST API right now, we're working on the rest.

**Comment by elacunza** [comment]
#493 is finished in master and includes automatic tests thanks to @uanabitarte !
We won't be working on #494 as it doesn't seem very usell.
We have CLI command in development in https://github.com/elkarbackup/elkarbackup-api-cli
Closing this as done, will be released in v2.1.0
