### ISSUE TITLE
Docker image upgrade

### ISSUE THREAD

**Issue by launtony** [elkarbackup/elkarbackup#265]
I have a question :) When the version 1.2.7 is available with the docker image ?

Thanks a lot :)

**Comment by xezpeleta** [comment]
Hi @launtony 

I've just added version 1.2.7 to the repository.

**Comment by launtony** [comment]
Yes I know but if I restart my docker I will get the latest version 1.2.7 ?

**Comment by xezpeleta** [comment]
Good question. To be honest I didn't test the update process in Docker. So, if you are using it in production and you want to update, please don't forget to do the backup of the persistent data (db and files).

Anyway, if you can wait until I test it I can guide your through the update process.

**Comment by launtony** [comment]
Yes I can wait :) In the docker you called the apt repository but on this I don't see the 1.2.7 version :/ Only 1.2.6 and 1.2.5
