### ISSUE TITLE
Upgrade to Symfony 3.4

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#271]
Our current version 2.8 is arriving to the end of life (2018/2019). We should consider upgrading to a newer LTS version sometime this year.

What do you think? Is it safer to upgrade to 3.4 or should we jump directly to 4.4? :fearful: 

![image](https://user-images.githubusercontent.com/1846038/36498290-2303d66e-173e-11e8-875a-18107f2119b5.png)

![image](https://user-images.githubusercontent.com/1846038/36497218-f8bb2db0-173a-11e8-8175-5e23ab35391d.png)

**Comment by adrianles** [comment]
I have not migrated any project yet from 2.x to 3.4 so I have no real feedback but

If we really want to make the change before the support for the 2.8 is gone then the 4.4 is out of the question.
2.8 -> End of Maintenance = 11/2018
4.4 -> Feature Freeze        = 09/2019

Also, every time you browse in the Symfony documentation for the version 4 the following message is shown:
> You are browsing the Symfony 4 documentation, which changes significantly from Symfony 3.x. If your app doesn't use Symfony 4 yet, browse the Symfony 3.4 documentation.

Not sure if that is a factor though

**Comment by xezpeleta** [comment]
I see. So then it's clear! v3.4 !

**Comment by xezpeleta** [comment]
I've created the branch  `feature-sym34-271`, so that we can start working in the migration to Symfony 3.4.

Our first goal, before jumping to 3.4, is to remove all the deprecated messages we get in the current version. Any help is welcome!

**Comment by xezpeleta** [comment]
## Update

After a period of inactivity we're here again working on the upgrade

https://github.com/elkarbackup/elkarbackup/tree/feature-symfony34

We already have a working version. But there are still some details to fix.

**Comment by elacunza** [comment]
This is finally done in master, thanks to @uanabitarte
