### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#275]
Hej guys

need some assistance again. I tried to run a backup job but it fails. 

![grafik](https://user-images.githubusercontent.com/19992865/37255281-58efa892-254a-11e8-83f5-99e290c75402.png)

I suggest an authentication issue. So I checked the setup.

On source server the key has been placed in /root/.ssh/authorized_keys. On the backup server I switched to _elkarbackup_ user and entered the following

```
ssh root@server
```
but unfortunately the source server asks for _root's_ password. But it should connecting without being prompted for the password, right? What did I miss to do?

Your assistance is highly appreciated.

Thank you so much

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

> but unfortunately the source server asks for root's password. But it should connecting without being prompted for the password, right? What did I miss to do?

That's it. If you are not able to connect via SSH  (without password), it's probably caused by an incorrect configuration, a wrong copypaste or wrong permissions in your _authorized_keys_ file...

**Comment by nephilim75** [comment]
I doublechecked the key file on source server and recreated it. The source server is running Debian 9 (stretch). Could it be related to the sshd_config file? It looks different to Debian 8.

```
elkarbackup@pcf-backup:/home/pi$ ssh root@sub.domain.de
Permission denied (publickey).
```

Can you see something wrong in the log beneath?

```
elkarbackup@pcf-backup:/home/pi$ ssh root@cloud.osteopathie-merrett.de -v
OpenSSH_6.7p1 Raspbian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to sub.domain.de [2a01:****:e163:****:ba27:ebff:****:****] port 22.
debug1: Connection established.
debug1: identity file /var/lib/elkarbackup/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/elkarbackup/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Raspbian-5+deb8u3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4p1 Raspbian-10+deb9u2
debug1: match: OpenSSH_7.4p1 Raspbian-10+deb9u2 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr umac-64-etm@openssh.com none
debug1: kex: client->server aes128-ctr umac-64-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA dd:e2:**:e7:af:70:**:51:c0:**:82:4d:**:cd:93:6c
debug1: Host 'sub.domain.de' is known and matches the ECDSA host key.
debug1: Found key in /var/lib/elkarbackup/.ssh/known_hosts:1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /var/lib/elkarbackup/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Trying private key: /var/lib/elkarbackup/.ssh/id_dsa
debug1: Trying private key: /var/lib/elkarbackup/.ssh/id_ecdsa
debug1: Trying private key: /var/lib/elkarbackup/.ssh/id_ed25519
debug1: No more authentication methods to try.
Permission denied (publickey).
elkarbackup@pcf-backup:/home/pi$
```

Hope there is a hint in it?

Kind regards
//neph

**Comment by antton** [comment]
This is your why!!

https://mike632t.wordpress.com/2017/07/03/configuring-ssh-on-debian-stretch/

Antton

**Comment by xezpeleta** [comment]
Hi @nephilim75 

Remember that the _authorized_keys_ file must have 0600 permissions and the correct ownership. You can also check connecting from your own computer to the server using SSH keys. Does it work?

Finally, I recommend you to use `ssh-copy-id` instead of making the changes manually.

**Comment by antton** [comment]
Are ssh root@cloud.osteopathie-merrett.de and  ssh root@sub.domain.de the same server machine?

Ca you try connecting giving explicit the id_rsa file:
ssh -i /var/lib/elkarbackup/.ssh/id_rsa root@server

can you check if the know_hosts is not your problem? 
Removing all the entries inside the file /var/lib/elkarbackup/.ssh/known_hosts

Check permissions as @xezpeleta said in your remote server.

And sorrry for my previous comment It was a wrong answer (I already delete).

**Comment by nephilim75** [comment]
Hi

des, it is the same. But I made a mistake by missing to anonymize the server address. Would you please edit your post, I did the same with mine. Thank you.

I am on a business trip right now and I will check every provided hint coming weekend. I will let you know my findings.

Kind regards
//neph

**Comment by nephilim75** [comment]
Hello

here my findings:

Server, that should be backed up:

```
root@pcf-cloud:~/.ssh# ls -alF
total 12
drwxr-xr-x 2 root root 4096 Apr  8 08:36 ./
drwx------ 4 root root 4096 Feb 21 19:33 ../
-rw------- 1 root root  416 Mar 12 11:31 authorized_keys
root@pcf-cloud:~/.ssh#
```

in _/etc/ssh/sshd_config_ I have the following enabled:

```
PermitRootLogin without-password
PubkeyAuthentication yes
```

<br />

On EB server:

- first I deleted all entries from /var/lib/elkarbackup/.ssh/known_hosts
- then I tried to copy the key as advised in your previous post

This is the result:

```
elkarbackup@pcf-backup:~/.ssh$ ls -alF
total 16
drwxr-xr-x 2 elkarbackup elkarbackup 4096 Apr  8 08:36 ./
drwxr-xr-x 4 elkarbackup elkarbackup 4096 Aug 10  2017 ../
-rw------- 1 elkarbackup elkarbackup 1679 Aug 10  2017 id_rsa
-rw-r--r-- 1 elkarbackup elkarbackup  416 Aug 10  2017 id_rsa.pub
-rw-r--r-- 1 elkarbackup elkarbackup    0 Apr  8 08:48 known_hosts
elkarbackup@pcf-backup:~/.ssh$ ssh-copy-id -i id_rsa.pub root@sub.domain.de
The authenticity of host 'sub.domain.de (91.4.233.161)' can't be established.
ECDSA key fingerprint is dd:e2:83:e7:af:70:12:51:c0:18:82:4d:59:cd:93:6c.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@sub.domain.de's password:
```

Still not working... :-(

Kind regards
//neph

**Comment by xezpeleta** [comment]
I don't think this is a Elkarbackup issue. I suggest you to try logging from another computer. From my previous comment:

> Remember that the authorized_keys file must have 0600 permissions and the correct ownership. You can also check connecting from your own computer to the server using SSH keys. Does it work?

**Comment by nephilim75** [comment]
Well, I tested it from my laptop. Created a key pair and added the public key to the source server. Then I tried to access the source server. It worked perfectly fine. No password prompts are coming up.

Therefore I think my _sshd_config_ on source server is ok and _authorized_keys_ file is fine as well. I will check the key pair on EB server again.

Two questions:
1. The key pair of EB will be created in this location: `/var/lib/elkarbackup/.ssh/`, right?
2. And it will be freshly re-created by the option menu in EB UI, once it got deleted from above location, right?

Kind regards
//neph

**Comment by xezpeleta** [comment]
> The key pair of EB will be created in this location: /var/lib/elkarbackup/.ssh/, right?
> And it will be freshly re-created by the option menu in EB UI, once it got deleted from above location, right?

Yes, that's it. By the way, I've realized there is a mistake in your previous comment:

```bash
elkarbackup@pcf-backup:~/.ssh$ ssh-copy-id -i id_rsa.pub root@sub.domain.de
The authenticity of host 'sub.domain.de (91.4.233.161)' can't be established.
ECDSA key fingerprint is dd:e2:83:e7:af:70:12:51:c0:18:82:4d:59:cd:93:6c.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@sub.domain.de's password:
```

In the SSH command you need to specify the private key (**_id_rsa_**) instead of the public one (**_id_rsa.pub_**):

```
ssh -i /var/lib/elkarbackup/.ssh/id_rsa root@your_host
```

**Comment by nephilim75** [comment]
Hej hej,

at the end I got it working. I reinstalled the server from scratch and then it was working fine. Thank you so much for your support and efforts.

Just one question left related to that issue. For the very first login attempt there is coming up a "proceed question":

```
pi@pcf-backup:~ $ ssh root@server
The authenticity of host 'server (2003:e7:****:f900:***:bfce:**:***)' can't be established.
ECDSA key fingerprint is e7:83:90:2a:b2:e8:3a:2e:4f:be:42:53:03:a3:f5:4c.
Are you sure you want to continue connecting (yes/no)? yes
```

I need actively to confirm with `yes` to proceed. Is there a way around? I need to have it working without beeing prompted for that confirmation.

Kind regards
//neph

**Comment by xezpeleta** [comment]
> I need actively to confirm with yes to proceed. Is there a way around? I need to have it working without beeing prompted for that confirmation.

Elkarbackup handles it by default, avoiding the strict host key checking during the backup job.

**Comment by elacunza** [comment]
I don't think we should use our issue tracker for things like this; much less for attending unrelated questions...

**Comment by nephilim75** [comment]
> I don't think we should use our issue tracker for things like this; much less for attending unrelated questions...

I see this different. When I try to create a backup job which is not running because this step (actively confirm with yes) needs to be done first on console, that would be an issue and should be handled here.

> Elkarbackup handles it by default, avoiding the strict host key checking during the backup job.

I will check tonight. Thank you so much. I will let you know.

Kind regards
//neph

**Comment by elacunza** [comment]
Hi Neph,

El 17/04/18 a las 09:43, nephilim75 escribió:
>
>     I don't think we should use our issue tracker for things like
>     this; much less for attending unrelated questions...
>
> I see this different. When I try to create a backup job which is not 
> running because this step (actively confirm with yes) needs to be done 
> first on console, that would be an issue and should be handled here.
>
The issue has a vague subject "Authentication issue", you originally 
reported " the source server asks for /root's/ password", and now you're 
reporting an unrelated problem "For the very first login attempt there 
is coming up a "proceed question":"; but you did it on the command line, 
not from Elkarbackup - so for now there is no elkarbackup issue.

If you have that problem with Elkarbackup, please report it in another 
issue, and properly describe how to reproduce please. That way you help 
us, because we won't have issues that are not bugs or improvements in 
our bugtracker, so that we can attend them better.
>
>     Elkarbackup handles it by default, avoiding the strict host key
>     checking during the backup job.
>
> I will check tonight. Thank you so much. I will let you know.
>
For any comment and questions that you're not quite sure are an 
Elkarbackup bug, but somehow are related to elkarbackup, just post on 
the mailing list.

Thanks a lot!!!
Eneko

-- 

Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943569206
Astigarraga bidea 2, 2º izq. oficina 11; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by nephilim75** [comment]
Hello

ok, I will follow this guide in the future.

Thank you for your assistance.

Kind regards
//neph
