### ISSUE TITLE
rsync error - backup works

### ISSUE THREAD

**Issue by kdpawson** [elkarbackup/elkarbackup#276]
I've setup Elkarbackup on an existing server that is running rsnapshot fine. When I add a client and job it backs up the data however it reports an error and marks the job as fail.

The error from the logs is:
Command failed: [unknown error] rsync error: syntax or usage error (code 1) at main.c(1348) [sender=3.1.1]\n/usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: ERROR: /usr/bin/rsync returned 1 while processing root@server1.local:/etc\ntouch /backupdata/elkarbackup/0001/0001/Hourly.0/\nrm -f /tmp/rsnapshot.0001_0001.pid\n/usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: ERROR: /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: completed, but with some errors

The server and client machines are Ubuntu 16.04 and as mentioned above I'm running a manual rsnapshot job which works perfectly. I want to implement Elkar Backup to make it easier for other administrators who have little Linux cli experience.

I also noticed the job will not at all if I don't included this extra rsync long args:
+rsync_long_args=--rsync-path="sudo rsync"

Thanks
Keith

**Comment by xezpeleta** [comment]
Hi @kdpawson 

What is your Elkarbackup version? Do you see any detailed log in `/var/log/elkarbackup/jobs` directory?

> I also noticed the job will not at all if I don't included this extra rsync long args:
> +rsync_long_args=--rsync-path="sudo rsync"

I guess you want to use `sudo rsync` to preserve the ownership. Currently the possibility to preserve the ownership is not supported in Elkarbackup. However apparently there is a workaround to do that: https://github.com/elkarbackup/elkarbackup/issues/201

**Comment by kdpawson** [comment]
Hi and thanks for you quick response.

Version is 1.2.7 and I've installed it from the repo based on the instructions from the documentation site: https://docs.elkarbackup.org/en/installation.html 

I'm not that concerned about preserving ownership, although it would be a nice thing to have. More concerned about getting backups. The reason I have used the rsync long args show above is that if I don't have that setting the backup won't even start and the logs are saying it's a permission issue. If I add it, the backup at least runs. I'm now using a non-root user to do the backup as that's what I do with the manual rsnapshot configuration and just give that user sudo access via config in visudo file on the client server.

Logs from /var/log/elkarbackup/jobs see below from a recent backup job:
`[2018-03-16T22:46:03] /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: started
[2018-03-16T22:46:03] Setting locale to POSIX "C"
[2018-03-16T22:46:03] echo 19977 > /tmp/rsnapshot.0001_0001.pid
[2018-03-16T22:46:03] /usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats +rsync_long_args=--rsync-path=sudo rsync --rsh=/usr/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=no user@server.local:/etc /backupdata/elkarbackup/0001/0001/Hourly.0/.
[2018-03-16T22:46:03] Unexpected remote arg: user@server1.local:/etc
[2018-03-16T22:46:03] rsync error: syntax or usage error (code 1) at main.c(1348) [sender=3.1.1]
[2018-03-16T22:46:03] /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: ERROR: /usr/bin/rsync returned 1 while processing user@server.local:/etc
[2018-03-16T22:46:03] touch /backupdata/elkarbackup/0001/0001/Hourly.0/
[2018-03-16T22:46:03] rm -f /tmp/rsnapshot.0001_0001.pid
[2018-03-16T22:46:03] /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: ERROR: /usr/bin/rsnapshot -c /tmp/rsnapshot.1_1.cfg Hourly: completed, but with some errors
`
Thanks for your help.

**Comment by xezpeleta** [comment]
> The reason I have used the rsync long args show above is that if I don't have that setting the backup won't even start and the logs are saying it's a permission issue

Ok, let's start from here. It should work with the default configuration. Can you create a new client just with the minimum configuration?
- Client-> host: user@server1.local
- Job-> path: /etc

What's the log output now?

**Comment by xezpeleta** [comment]
> I'm now using a non-root user to do the backup as that's what I do with the manual rsnapshot configuration and just give that user sudo access via config in visudo file on the client server

I see, so your user doesn't have permissions to read `/etc` directory but it has permissions to execute `sudo rsync`. That's why you're setting up this as rsync-path...

After adding `--rsync-path="sudo rsync"` in Cilent->Advanced-> Rsync long args, you can check the resulting rsnapshot configuration with the following URL: `https://elkarbackup.local/client/1/job/1/config`

**Comment by kdpawson** [comment]
I tried a default config on a different client and without the sudo rsync I get a heap of permission errors which is to be expected I guess.
rsnapshot config is attached.
[rsnapshotconfig.txt](https://github.com/elkarbackup/elkarbackup/files/1819288/rsnapshotconfig.txt)

Thanks
Keith

**Comment by xezpeleta** [comment]
If you check the configuration file you will realize what's the mistake:

```
rsync_long_args	--delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats  +rsync_long_args=--rsync-path="sudo rsync"
```

You only need to add `--rsync-path="sudo rsync"`. Remove +rsync_long_args from the string.

**Comment by kdpawson** [comment]
Oops I'm sorry to have wasted your time, I've copied and pasted that from my manual rsnapshot config file.

All good now, just test the backups and added another to be sure and all working as it should.

Many thanks for your help.
