### ISSUE TITLE
Error despues de actualizar a Ubuntu 18.10

### ISSUE THREAD

**Issue by jesusgascon** [elkarbackup/elkarbackup#277]
Hola,

Tengo corriendo Elkarbackup en Ubuntu 17.10 64 bits. 

Después de actualizar a la versión 18.04 de Ubuntu, no logro conectar a Elkarbackup, accediendo a través de http://127.0.0.1/elkarbackup/

En una instalación limpia de Ubuntu 18.04,en donde he puesto Elkarbackup, si que funciona sin problemas, pero no en la version 17.10 que ha pasado a las 18.04.

Al intentar conectarme a la dirección de Elkarbackup, me muestra este mensaje

> 
> <?php
> 
> use Symfony\Component\ClassLoader\ApcClassLoader;
> use Symfony\Component\HttpFoundation\Request;
> 
> $loader = require_once __DIR__.'/../app/bootstrap.php.cache';
> 
> // Enable APC for autoloading to improve performance.
> // You should change the ApcClassLoader first argument to a unique prefix
> // in order to prevent cache key conflicts with other applications
> // also using APC.
> /*
> $apcLoader = new ApcClassLoader(sha1(__FILE__), $loader);
> $loader->unregister();
> $apcLoader->register(true);
> */
> 
> require_once __DIR__.'/../app/AppKernel.php';
> //require_once __DIR__.'/../app/AppCache.php';
> 
> $kernel = new AppKernel('prod', false);
> $kernel->loadClassCache();
> //$kernel = new AppCache($kernel);
> 
> // When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter
> //Request::enableHttpMethodParameterOverride();
> $request = Request::createFromGlobals();
> $response = $kernel->handle($request);
> $response->send();
> $kernel->terminate($request, $response);

Hay algún log, en donde pueda ver donde puede estar el problema? Apache esta corriendo sin problemas en la version 18.04.

Elkabup parece estar corriendo, pero no me muestra la pagina web:

> oot@Zapus:/home/jesus# /etc/init.d/elkarbackup-tahoe-lafs  status
> ● elkarbackup-tahoe-lafs.service - LSB: Tahoe-LAFS node for ElkarBackup
>    Loaded: loaded (/etc/init.d/elkarbackup-tahoe-lafs; generated)
>    Active: active (exited) since Fri 2018-03-16 11:55:06 CET; 1h 24min ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 16158 ExecStop=/etc/init.d/elkarbackup-tahoe-lafs stop (code=exited, status=0/SUCCESS)
>   Process: 16193 ExecStart=/etc/init.d/elkarbackup-tahoe-lafs start (code=exited, status=0/SUCCESS)
> 
> mar 16 11:55:06 Zapus systemd[1]: Starting LSB: Tahoe-LAFS node for ElkarBa…p...
> mar 16 11:55:06 Zapus systemd[1]: Started LSB: Tahoe-LAFS node for ElkarBackup.
> Hint: Some lines were ellipsized, use -l to show in full.

Un saludo

**Comment by xezpeleta** [comment]
Prueba a eliminar la cache:

```sh
rm -fR /usr/share/elkarbackup/app/cache/*
```

Y accede de nuevo vía web. ¿Sigue saliendo el mismo texto?

Si es así, busca en los errores de apache a ver si tienes más información (dentro del directorio `/var/log/apache2/`).

**Comment by jesusgascon** [comment]
He limpiado la cache y continua igual.

Al resestear apache2, veo estos errores en /var/log/apache2:

**more  elkarbackup-ssl.error.log**
[Fri Mar 16 13:48:03.855964 2018] [ssl:warn] [pid 26777] AH01909: elkarbackup:443:0 server certificate does NOT include an ID which matches the server name
[Fri Mar 16 13:48:03.863323 2018] [ssl:warn] [pid 26778] AH01909: elkarbackup:443:0 server certificate does NOT include an ID which matches the server name


**more  error.log**
[Fri Mar 16 13:48:03.767959 2018] [mpm_prefork:notice] [pid 25993] AH00169: caught SIGTERM, shutting down
[Fri Mar 16 13:48:03.865350 2018] [mpm_prefork:notice] [pid 26778] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Fri Mar 16 13:48:03.865384 2018] [core:notice] [pid 26778] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 16 13:48:03.868849 2018] [:error] [pid 26780] avahi_entry_group_add_service_strlst("elkarbackup") failed: Invalid host name
[Fri Mar 16 13:48:03.870782 2018] [:error] [pid 26780] avahi_entry_group_add_service_strlst("elkarbackup") failed: Invalid host name

Saludos

**Comment by jesusgascon** [comment]
Solucionado,

No era problema de elkarbackup sino de PHP.

Volver a re configurar PHP y ya funciona todo de nuevo (https://ayesh.me/Ubuntu-PHP-7.2)

Gracias y un saludo.
