### ISSUE TITLE
Parar una tarea de backup en ejecución

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#28]
Ahora mismo no tenemos opción de detener una tarea de backup una vez que ha comenzado. Podríamos hacerlo por consola matando el proceso rsync, pero no hay forma de hacerlo desde el interfaz.

Sería interesante que en la pantalla principal, en la zona donde se visualizan las tareas, tuviéramos un botón que nos permitiera parar la tarea cuando estuviera en estado de ejecución.

En estos casos, entiendo que lo correcto sería ejecutar después los POST scripts que pudiera tener configurados.

**Comment by xezpeleta** [comment]
Añadido nuevo comando **stop_job** para abortar la ejecución de rsnapshot/rsync:

```sh
/usr/share/elkarbackup/app/console elkarbackup:stop_job <clientId> <jobId>
```

Solo falta añadir un botón en el panel principal que llame a este comando.

**Comment by xezpeleta** [comment]
Nota para mi mismo:
Hay que dejar claro que abortar una tarea puede conllevar pérdida de datos.

Si es posible, habría que añadir alguna comprobación al código para evitar abortar la tarea justo cuando esté en el momento de la rotación.

**Comment by xezpeleta** [comment]
En el PR #127 se ha añadido un botón en la ventana principal de Jobs que permite abortar la tarea.

Todavía queda pendiente:
* Añadir un mensaje de advertencia y revisar que no se aborte la tarea en fase de rotación https://github.com/elkarbackup/elkarbackup/issues/28#issuecomment-97202659
* Intentar que el mismo comando saque de la cola de ejecución a un job que este en estado "queued"

**Comment by elacunza** [comment]
This is implemented so closing the issue
