### ISSUE TITLE
pre script error

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#280]
Hej guys

sorry to bother you again. I found a warning in my overview and checked logs for this. Here is what I got:

```
Job "1" pre script "MySqlDumpAllDatabases.sh" execution failed. Diagnostic information follows: Warning: Permanently added 'sub.domain.de,IP.AD.DR.E.SS' (ECDSA) to the list of known hosts. [INFO] TMP directory /tmp/ebmysqldump doesn't exist. Creating... ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO) ERROR:
```

I am using MariaDB on the server at sub.domain.de. Could this be the reason for that error? Any idea to get rid of this?

Thank you in advance.

Kind regards
//neph

**Comment by elacunza** [comment]
This is not an elkarbackup issue, bug nor wish; please do not use our bug tracker for requesting help with problems like this.

Thanks

**Comment by elacunza** [comment]
This is not an elkarbackup issue, bug nor wish; please do not use our bug tracker for requesting help with problems like this.

Thanks

**Comment by nephilim75** [comment]
Hej

why not? The script you provide generates this error during backup procedure within EB? What else is this then an error? If this is not related to EB or its script, what is this related instead?

Your help is appreciated.

Thanks in advance.

Kind regards
//neph

**Comment by elacunza** [comment]
Sorry, we don't ship a script called "MySqlDumpAllDatabases.sh" with elkarbackup?

**Comment by nephilim75** [comment]
Hej hej

I found it here: [https://github.com/elkarbackup/elkarbackup-scripts](https://github.com/elkarbackup/elkarbackup-scripts) and it was subtitled with _"Official ElkarBackup scripts"_.

![grafik](https://user-images.githubusercontent.com/19992865/38880478-1fa19cec-4266-11e8-8bd7-92eabf8a5605.png)

Now this script creates a `Warning` in device overview and an error in log section. 

![grafik](https://user-images.githubusercontent.com/19992865/38880673-94922a6c-4266-11e8-91a5-7d8486a50d43.png)

Therefore I thought it is reported in the correct manner. For me it is related to ElkarBackup and to the corresponding bug tracker.

In the repo itself there is no option to open issues as there was in the past. That's why I reported it in the way I did.

Kind regards
//neph

**Comment by nephilim75** [comment]
Hello

> What distribution is running on that server?

It is a Debian 9 server.

> neph, did you read https://github.com/elkarbackup/elkarbackup-scripts/blob/master/MySqlDumpAllDatabases/README.md ?

Yes, I did.

Anyhow, I got it fixed meantime. Here are the steps I took:

The error log indicates an authentication issue [ERROR 1045]. Then I tried to dump the database with user and password:

```
ssh root@server "mysqldump -u [user] -p[password] dbname > dbname.sql"
```

This worked perfectly fine. Then I decided to adapt the [script](https://github.com/elkarbackup/elkarbackup-scripts/blob/master/MySqlDumpAllDatabases/MySqlDumpAllDatabases.sh). Line 23 I commented out and line 24 I removed the #. I found the script in `/var/spool/elkarbackup/uploads`.

From
```
MYSQLCNF=/etc/mysql/debian.cnf
#MYSQLCNF=/root/.my.cnf
```
to
```
#MYSQLCNF=/etc/mysql/debian.cnf
MYSQLCNF=/root/.my.cnf
```

That's it. Backup of databases are working fine now.

Thank you so much for all your assistance. Again. :-)

Kind regards
//neph
