### ISSUE TITLE
Supported Device List.

### ISSUE THREAD

**Issue by pizu** [elkarbackup/elkarbackup#287]
Hi,

Is is possible to know the list of supported devices? Such as Cisco/Fortigate/F5 etc..

Thanks.

**Comment by xezpeleta** [comment]
Hi @pizu 

Currently, you can back up any server/device if it has SSH and Rsync installed. Alternatively, you could use a custom pre-client level script to copy the config files with your own tool...

**Comment by pizu** [comment]
Hi @xezpeleta 

Thanks For Your reply.

Will do some tests.

Thanks.
