### ISSUE TITLE
new parameters missing in parameters.yml and parameters.yml.dist

### ISSUE THREAD

**Issue by igorbga** [elkarbackup/elkarbackup#289]
The new parameters max_parallel_jobs and post_on_pre_fail parameters that are required in order to work with the new parallel job execution feature are missing in parameters.yml and parameters.yml.dist .

Although those are created in the installation .deb they should also be present in both mentioned parameters for 2 reasons:

- Developers installing elkarbackup manually should have the 2 parameters
- Those files, especially the .dist one, are the config templates that should have all the required parameters.

By the way, no symfony project should probably include the parameters.yml in the code repo, it should be deleted and ignored but that's a story for another issue.

**Comment by xezpeleta** [comment]
> Although those are created in the installation .deb they should also be present in both mentioned parameters

I agree.

> By the way, no symfony project should probably include the parameters.yml in the code repo, it should be deleted and ignored but that's a story for another issue.

It's totally related with the previous one.

If we keep the _parameters.yml_ file updated with the new 2 params, Debian/Ubuntu upgrade process will detect the file change and it will ask the user to take a decision: whether to keep the old version or to use the new one (a template with default values, loosing user's parameters so the connection to the DB will fail).

We'd probably fix all things together:

- Do not include _parameters.yml_ in the repository
- Remove _parameters.yml_ from Debian package `conffiles` etc...
- Update _parameters.yml.dist_

I will do some tests to check the upgrade process.

Thanks!!
