### ISSUE TITLE
how to config elkarbackup to support rsync daemon mode?

### ISSUE THREAD

**Issue by m2acgi** [elkarbackup/elkarbackup#299]
In some environments, I would like to use the rsync daemon instead of rsync ssh because of the more efficient transfer of rsync daemons. However, I did not find a description in the wiki. I need help. 

Thanks.

**Comment by xezpeleta** [comment]
Hi @m2acgi 

You can add a Rsync server host with the following URL format: `<ip-address>:`

You have an example of a Windows host with Rsync daemon in the [documentation](https://docs.elkarbackup.org/en/add-windows-clients.html)

**Comment by m2acgi** [comment]
@xezpeleta 
Thank u.

Then how to pass the 'secrets file' parameter to rsync with elkarbackup web?

**Comment by xezpeleta** [comment]
You don't need the rsyncd.secret file in Elkarbackup. Elkarbackup (Rsnapshot) will pull the data from the clients using one of those methods:

- Client with SSH daemon + Rsync tool installed
- Client with Rsync daemon

So in Elkarbackup web UI you only need to set up the correct URL depending on the method you choose. Elkarbackup will connect to the clients and will gather all the data using RSnapshot.

**Comment by m2acgi** [comment]
Do you mean 'anonymous rsync' of Rsync daemon ?

If so, how to ensure the security of it?

**Comment by xezpeleta** [comment]
You can specify the user (`user@host:`) if you want.

Take a look to the Rsnapshot [FAQ](http://rsnapshot.org/faq.html) if you need more details about.

**Comment by ffabreti** [comment]
I've seen Rsnapshot FAQ, nothing there.
 
With Windows client running cwRsync, there is no authentication like in Linux client.

I mean, when Elkarbackup connects to Linux client it authenticates using Elkarbackup's private key.

I don't see this happening on cwRsync, since I never copied Elkarbackup's public key to the Windows client, and it connects without any authentication.

I'm using `user@windows-machine:`  URL

Only line of defense is setting Server IP in cwRsync config to only permit connections from there.

Really hope I'm doing something wrong.

**Comment by elacunza** [comment]
Hi Fernando,

El 17/5/19 a las 14:27, Fernando escribió:
>
> I've seen Rsnapshot FAQ, nothing there.
>
> With Windows client running cwRsync, there is no authentication like 
> in Linux client.
>
> I mean, when Elkarbackup connects to Linux client it authenticates 
> using Elkarbackup's private key.
>
> I don't see this happening on cwRsync, since I never copied 
> Elkarbackup's public key to the Windows client, and it connects 
> without any authentication.
>
> I'm using |user@windows-machine:| URL
>
> Only line of defense is setting Server IP in cwRsync config to only 
> permit connections from there.
>
> Really hope I'm doing something wrong.
>
I think you're using rsync protocol, not SSH like in Linux. Just 
configure authentication in rsync.conf :
https://linux.die.net/man/5/rsyncd.conf

Look at "auth users" and "secrets file".

Cheers
Eneko

-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943569206
Astigarraga bidea 2, 2º izq. oficina 11; 20180 Oiartzun (Gipuzkoa)
www.binovo.es
