### ISSUE TITLE
Nuevas variables de entorno para los scripts

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#30]
En algunos scripts tal vez sea necesario el envíar alguna notificación por email. Teniendo en cuenta que al definir la tarea se le asigna un propietario (el cual ya tiene un email), e incluso se pueden añadir más direcciones de email a las que enviar las alertas, propongo añadir las siguientes variables de entorno: 

ELKARBACKUP_OWNER_EMAIL: con la dirección del dueño de la tarea
ELKARBACKUP_RECIPIENT_LIST: con el conjunto de direcciones configuradas para recibir alertas para la tarea.

**Comment by xezpeleta** [comment]
Kaixo @parreitu begiratzen egon naiz eta jabearen email helbidea errez atera daiteke (gutxienez level=JOB denean). Hurrengo bertsiorako jarriko dut.
