### ISSUE TITLE
PHP7.2 support: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#302]
I'm testing current Elkarbackup dev version with `PHP 7.2`. I get the following critical error when I submit any form:

```
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: 
"Warning: count(): Parameter must be an array or an object that implements Countable" at 
/app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 738 
```

**Comment by xezpeleta** [comment]
I confirm it works well with *PHP 7.1*. So I think we should:

 - [ ] Advise users (in docs) that Elkarbackup requires PHP>=5.3 <7.2
 - [ ] Upgrade to Symfony 3.4 #271  (after the upcoming release)

**Comment by vagheladev** [comment]
thanks

**Comment by victor1sql** [comment]
Hello, I am encountering this same error when I run PHP 7.3.1 and Symfony 3.4.  Is there a resolution for this?  Please advise.

Thanks,

 in vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php at line 723  -

            // The $cascadedGroups property is set, if the "Default" group is
            // overridden by a group sequence
            // See validateClassNode()
            $cascadedGroups = count($cascadedGroups) > 0
                ? $cascadedGroups
                : $groups;

at RecursiveContextualValidator ->validateGenericNode (object(OrderedHashMap), object(Form), '000000005a9571fc0000000061d15f74:Symfony\\Component\\Form\\Form:children', object(PropertyMetadata), 'children', array('Default'), null, 1, object(ExecutionContext))
in vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php at line 590  +

**Comment by nazeerhacker560** [comment]
> Hello, I am encountering this same error when I run PHP 7.3.1 and Symfony 3.4. Is there a resolution for this? Please advise.
> 
> Thanks,
> 
> in vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php at line 723 -
> 
> ```
>         // The $cascadedGroups property is set, if the "Default" group is
>         // overridden by a group sequence
>         // See validateClassNode()
>         $cascadedGroups = count($cascadedGroups) > 0
>             ? $cascadedGroups
>             : $groups;
> ```
> 
> at RecursiveContextualValidator ->validateGenericNode (object(OrderedHashMap), object(Form), '000000005a9571fc0000000061d15f74:Symfony\Component\Form\Form:children', object(PropertyMetadata), 'children', array('Default'), null, 1, object(ExecutionContext))
> in vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php at line 590 +

By the way  Please do you solved the problem?

**Comment by elacunza** [comment]
We must check that with symfony 3.4 these warnings disappear, and if so, close this as fixed.

**Comment by elacunza** [comment]
Forms work without warnings after #444 and #449

**Comment by gandimohammad** [comment]
> > مرحبًا ، أواجه نفس الخطأ عندما أقوم بتشغيل PHP 7.3.1 و Symfony 3.4. هل يوجد قرار لهذا؟ يرجى تقديم النصيحة.
> > شكرا،
> > في vendor / symfony / symfony / src / Symfony / Component / Validator / Validator / RecursiveContextualValidator.php في السطر 723 -
> > ```
> >         // The $cascadedGroups property is set, if the "Default" group is
> >         // overridden by a group sequence
> >         // See validateClassNode()
> >         $cascadedGroups = count($cascadedGroups) > 0
> >             ? $cascadedGroups
> >             : $groups;
> > ```
> > 
> > 
> > في RecursiveContextualValidator -> validateGenericNode (كائن (OrderedHashMap) ، كائن (نموذج) ، '000000005a9571fc0000000061d15f74: Symfony \ Component \ Form \ Form: children' ، object (PropertyMetadata) ، 'children' ، المصفوفة ('Default') ، null ، 1 ، كائن (ExecutionContext)) 
> > في بائع / symfony / symfony / src / Symfony / مكون / Validator / Validator / RecursiveContextualValidator.php في السطر 590 +
> 
> بالمناسبة من فضلك هل حللت المشكلة؟



> > Hello, I am encountering this same error when I run PHP 7.3.1 and Symfony 3.4. Is there a resolution for this? Please advise.
> > Thanks,
> > in vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php at line 723 -
> > ```
> >         // The $cascadedGroups property is set, if the "Default" group is
> >         // overridden by a group sequence
> >         // See validateClassNode()
> >         $cascadedGroups = count($cascadedGroups) > 0
> >             ? $cascadedGroups
> >             : $groups;
> > ```
> > 
> > 
> > at RecursiveContextualValidator ->validateGenericNode (object(OrderedHashMap), object(Form), '000000005a9571fc0000000061d15f74:Symfony\Component\Form\Form:children', object(PropertyMetadata), 'children', array('Default'), null, 1, object(ExecutionContext))
> > in vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php at line 590 +
> 
> By the way Please do you solved the problem?

Change to this code

$cascadedGroups = null !== $cascadedGroups && \count($cascadedGroups) > 0 ? $cascadedGroups : $groups;
