### ISSUE TITLE
Change copyrepository.sh

### ISSUE THREAD

**Issue by silvaguilherme** [elkarbackup/elkarbackup#303]
Hi
I need to change the copyrepository.sh because I need to use the rsync -u parameter to do incremental backup.
How could I do that?

**Comment by xezpeleta** [comment]
Hi @silvaguilherme 

The copyrepository.sh script is generated using a twig template: https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Resources/views/Default/copyrepository.sh.twig

You'll probably need to clean the cache after changing the file: (`cd /usr/share/elkarbackup && php app/cache clear:cache`)

Thanks

**Comment by adrianles** [comment]
most likely `php app/cache clear:cache --env=prod`

**Comment by silvaguilherme** [comment]
I changed the file, but when I tried clean the cache, I receveid the error:
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "clear" namespace.

**Comment by xezpeleta** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.
