### ISSUE TITLE
Save on small screens

### ISSUE THREAD

**Issue by ich92** [elkarbackup/elkarbackup#314]
The save button on smaller screens is not pressable.
The explanation for the Job is in front of the save button.

**Comment by xezpeleta** [comment]
Hi @ich92 

What kind of device are you using? Can you send us a screenshot?

Thanks

**Comment by ich92** [comment]
I use Safari and iPhone 7+

**Comment by elacunza** [comment]
@ich92 Is this a problem yet with current iOS and Safari?

**Comment by elacunza** [comment]
More than 2 years without activity -> closing
