### ISSUE TITLE
Error on backup Command failed: [unknown error]

### ISSUE THREAD

**Issue by kovalroma** [elkarbackup/elkarbackup#316]
``` Command failed: [unknown error] /usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats --rsh=/usr/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=no elkarbackup@LOCAL_IP:/home/elkarbackup/onlyoffice /usr/storage//0007/0065/.sync/.\nWARNING: Some files and/or directories in elkarbackup@LOCAL_IP:/home/elkarbackup/onlyoffice only transferred partially during rsync operation\ntouch /usr/storage//0007/0065/.sync/\nrm -f /tmp/rsnapshot.0007_0065 (...) ```

What's wrong ?

**Comment by xezpeleta** [comment]
Hi @kovalroma 

What Linux distribution & version are you using? Rsnapshot version?

There should be a more detailed output from Rsync, but I've detected that in some environments  the rsync verbose output doen't work as expected.

Thanks

**Comment by xezpeleta** [comment]
It could be due to vanished files. Dot you see a debug log file ?

**Comment by elacunza** [comment]
More than 2 years without activity -> closing
