### ISSUE TITLE
Docker dev version issues

### ISSUE THREAD

**Issue by gpulido** [elkarbackup/elkarbackup#317]
Hello,
I'm running the docker version with development that is using the 1.3 beta. and I'm having some issues:
- The docker image doesn't properly expose the elkarbackup config folders so any change to the parameters (for example the url prefix) is reset after each container reload.
- Some of my jobs are returning "finished with errors" in the log panel, but I can't access any detail information.
- The installation folder inside the container is different than in the documentation.
- I can't access the config for the rsnapshot adding the /config to the job url

This is just the issues that I have found. The app is great and I hope you will release the 1.3 soon!
Let me know if I can test or help.

**Comment by xezpeleta** [comment]
Please, report docker related issues in [elkarbackup-docker](https://github.com/elkarbackup/elkarbackup-docker) repository
