### ISSUE TITLE
NFS storage: autofs with custom configuration not working in v1.3.0

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#318]
After upgrading to Elkarbackup v1.3.0, I cannot configure the NFS storage location because the `host` field is disabled.

(Probably) the reason is: I changed the autofs configuration file when I upgraded to Debian Stretch:

```ini
# It wont work afer Wheezy to Jessie upgrade
#/net	-hosts vers=3
# Changed to:
/net /etc/auto.net --timeout=60
#
# Include /etc/auto.master.d/*.autofs
#
+dir:/etc/auto.master.d
```

**Comment by xezpeleta** [comment]
I changed my autofs configuration _/etc/auto.master_:

```ini
/net    -hosts
```

Now everything works as expected. Anyway, we should take into account that users can now use the _/etc/auto.master.d/*.autofs_  custom configuration files instead of modifying the default file.

**Comment by elacunza** [comment]
Xabi, can you check this in a newly installed Debian 10 to see if 2.0.0 is affected?

**Comment by xezpeleta** [comment]
Yes, this is not an issue. We can close it.
