### ISSUE TITLE
Users with limited access

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#32]
Tras crear un usuario nuevo y hacer login con el, al ir a Users->Show, da error:

Oops! An Error Occurred
The server returned a "403 Forbidden"
[...]

**Comment by xezpeleta** [comment]
Issue reopened. We'd like to revert this modification to have users with limited access to some clients. Instead, we'll add option to create more admin users.

If i'm not wrong, @antton is currently working on that.
