### ISSUE TITLE
Error after upgrading to 1.3.0

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#320]
Hello,

I've upgraded my Elkarbackup and now I'm getting Doctrine errors:  Column not found: 1054 Unknown column 'c0_.state' in 'field list'" 

Could you give some advice ?

`[2018-10-03 08:05:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT c0_.description AS description_0, c0_.id AS id_1, c0_.isActive AS isActive_2, c0_.name AS name_3, c0_.url AS url_4, c0_.quota AS quota_5, c0_.sshArgs AS sshArgs_6, c0_.rsyncShortArgs AS rsyncShortArgs_7, c0_.rsyncLongArgs AS rsyncLongArgs_8, c0_.state AS state_9, c0_.maxParallelJobs AS maxParallelJobs_10, c0_.data AS data_11, c0_.owner_id AS owner_id_12 FROM Client c0_ WHERE c0_.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ORDER BY c0_.id ASC' with params ["1", "2", "4", "13", "14", "16", "17", "19", "20", "21", "22", "24", "25", "26", "27", "28", "29", "30", "31", "32"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.state' in 'field list'" at /usr/share/elkarbackup/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT c0_.description AS description_0, c0_.id AS id_1, c0_.isActive AS isActive_2, c0_.name AS name_3, c0_.url AS url_4, c0_.quota AS quota_5, c0_.sshArgs AS sshArgs_6, c0_.rsyncShortArgs AS rsyncShortArgs_7, c0_.rsyncLongArgs AS rsyncLongArgs_8, c0_.state AS state_9, c0_.maxParallelJobs AS maxParallelJobs_10, c0_.data AS data_11, c0_.owner_id AS owner_id_12 FROM Client c0_ WHERE c0_.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ORDER BY c0_.id ASC' with params [\"1\", \"2\", \"4\", \"13\", \"14\", \"16\", \"17\", \"19\", \"20\", \"21\", \"22\", \"24\", \"25\", \"26\", \"27\", \"28\", \"29\", \"30\", \"31\", \"32\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.state' in 'field list' at /usr/share/elkarbackup/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.state' in 'field list' at /usr/share/elkarbackup/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.state' in 'field list' at /usr/share/elkarbackup/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-10-03 08:05:47] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
`

**Comment by xezpeleta** [comment]
Hi @parreitu 

First of all, do you have the output of the `apt-upgrade` command? Could you first check if the upgrade process finished well?

Please, send us the output of the following command too:

```sh
/usr/share/elkarbackup/app/console doctrine:migrations:status
```

**Comment by parreitu** [comment]
`PHP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle/Command/TickCommand.php on line 150`

**Comment by xezpeleta** [comment]
Hi @parreitu 

What PHP version do you have installed in your server?

**Comment by parreitu** [comment]
An old version: PHP 5.4.45

**Comment by xezpeleta** [comment]
Short answer: bad news, you need at least PHP 5.5.

Long version: even though Symfony 2.8 supports PHP 5.3.9, latest code included in Elkarbackup v1.3.0 require PHP 5.5

We should add this info in the documentation.

**Comment by parreitu** [comment]
Now I'm upgrading Linux in the Elkarbackup machine.

Which is the recommended procedure to re-run the upgrade once I've a supported version of PHP ?

Thanks !!

**Comment by xezpeleta** [comment]
I bet it will be running after the upgrade. However, if I'm wrong you can always reinstall elkarbackup package with apt.
