### ISSUE TITLE
Document: decreasing idle time between tick commands below 1 minute causes problems

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#325]
Currently _"Tick"_ command is executed by CRON every minute. That's the default configuration in Ubuntu/Debian packages.

Using Elkarbackup [docker image](https://hub.docker.com/r/elkarbackup/elkarbackup/) I've decreased that idle time to 10 seconds (which helps me a lot testing/debugging issues).

The "_enqueue now_" function works great and the backup starts in 10 seconds. However, the **scheduled jobs will be executed multiple times each one** in some situations (specially with short jobs).

It makes sense; when tick command is executed the scheduler will query for pending jobs at 9:00 (for instance). If it ends before 9:01, it will repeat the same query and it will enqueue the same jobs again.

I don't think it's necessary to change the current behaviour (is there any easy solution?). But it might be interesting to document it, as someone could repeat the same error.

**Comment by elacunza** [comment]
We should document that decreasing the tick cronjob execution period below 1 min is not supported and can cause these issues.

**Comment by elacunza** [comment]
Putting a notice in cron file should be enough, really.

**Comment by xezpeleta** [comment]
I agree

**Comment by elacunza** [comment]
In fact, cron doesn't accept executions below 1 min... so we should update de FAQ that is the only place where console's elkarbackup:tick command is referenced.

**Comment by uanabitarte** [comment]
I added a note in the question that reference elkarbackup:tick command in [FAQ](https://github.com/elkarbackup/elkarbackup/wiki/FAQ)

**Comment by elacunza** [comment]
Thanks for improving the FAQ @uanabitarte
