### ISSUE TITLE
CentOS7: installation and startup

### ISSUE THREAD

**Issue by HeOpuHaMeH9I** [elkarbackup/elkarbackup#334]
Installing on Centos 7 following guide.

```
[Mon Oct 22 00:18:58.978279 2018] [:error] [pid 7921] [client xxx.xxx.xxx.xxx:44270] PHP Warning:  SessionHandler::write(): open(/usr/local/elkarbackup/app/sessions/sess_m2k1e8ec3lrbm74fh9k08jn3o5, O_RDWR) failed: Permission denied (13) in /usr/local/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 77
```
permissions right after installation 
```
[root@st01 tmp]# ls -ld /usr/local/elkarbackup/app/sessions/
drwxrwxr-x+ 2 root root 6 Oct 22 00:18 /usr/local/elkarbackup/app/sessions/
[root@st01 tmp]# getfacl /usr/local/elkarbackup/app/sessions/
getfacl: Removing leading '/' from absolute path names
# file: usr/local/elkarbackup/app/sessions/
# owner: root
# group: root
user::rwx
user:root:rwx
user:elkarbackup:rwx
user:nginx:rwx
group::r-x
mask::rwx
other::r-x
default:user::rwx
default:user:root:rwx
default:user:elkarbackup:rwx
default:user:nginx:rwx
default:group::r-x
default:mask::rwx
default:other::r-x
```

please help to overcome permissions mess

**Comment by xezpeleta** [comment]
Hi @HeOpuHaMeH9I 

To be honest we didn't test the last version in Centos. Anyway, we're preparing new RPM installer which should solve this issue. We'll keep you updated.

Thanks

**Comment by HenryRc0** [comment]
Hi @HeOpuHaMeH9I 

On CentOS 7 selinux is enabled by default.
You can check by executing "getenforce" -> should be Enforcing
Do you see anything related within /var/log/audit/audit.log
If yes - try "setenforce 0"
If this solves your issue post the part from audit.log maybe I can help.

Henry

**Comment by HeOpuHaMeH9I** [comment]
@HenryRc0 it's in disabled state already since host os setup...

**Comment by elacunza** [comment]
We have decided not to support CentOS with native package unless someone contributes that support. Upgrade path is docker image. Thanks.
