### ISSUE TITLE
Long running job blocks execution of short scheduled jobs.

### ISSUE THREAD

**Issue by HenryRc0** [elkarbackup/elkarbackup#336]
Hi, 

a long running job blocks the execution of short scheduled jobs even if it is allowed to execute more
jobs in parallel. 

Example: 
Within parameters: Max parallel jobs is 5
5 jobs are configured with a policy to be executed every hour (redologs from databases)
1 job is configured with a policy to be executed on a daily basis (online/offline backup of a database)
The job which is doing the online/offline backup runs for about 3 hours.
While the job is running the tick command adds the 5 jobs correctly to the queue (status queued), but
they aren´t executed. Only after the long running job is finished all 5 hourly based jobs are started 
(in parallel). 
Therefor 2 hourly backups aren´t executed. 

Henry

**Comment by xezpeleta** [comment]
Hi @HenryRc0 

Did you solve your issue?

**Comment by HenryRc0** [comment]
No I didn´t solve the issue. 
#336 is the same as #335 - for some reason I don´t know it I posted it twice 
sorry for the noice
