### ISSUE TITLE
How does elkarbackup deal with connection loss? Could it be improved?

### ISSUE THREAD

**Issue by lukas-mertens** [elkarbackup/elkarbackup#337]
Does Elkarbackup pick up the job again, when I shut down my PC while it's syncing? 
One job seems to be running according to the webinterface but my rsync-server has zero cpu usage. 
If it doesn't pick up the connection again, that could be an important feature in my opinion. 

My suggestion would be that the server could try to ping every client with jobs in the queue every 5min for example. When the client of the first job in the queue isn't available anymore it should start another job until the client is available again. 

I am sure this was asked and answered before, but I wasn't able to find any information. If elkarbackup already handles connection loss, it would be nice to add it to the docs, so that users know they don't have to worry about shutting down their clients during sync.

**Comment by xezpeleta** [comment]
> Does Elkarbackup pick up the job again, when I shut down my PC while it's syncing?

No

> One job seems to be running according to the webinterface but my rsync-server has zero cpu usage.
> If it doesn't pick up the connection again, that could be an important feature in my opinion.

Elkarbackup uses Rsnapshot which includes the configuration option `rsync_numtries NUM`.

```
# Number of rsync re-tries. If you experience any network problems or
# network card issues that tend to cause ssh to fail with errors like
# "Corrupted MAC on input", for example, set this to a non-zero value
# to have the rsync operation re-tried.
#
#rsync_numtries 0
```

Maybe we could add this option.

> My suggestion would be that the server could try to ping every client with jobs in the queue every 5min for example. When the client of the first job in the queue isn't available anymore it should start another job until the client is available again.

If I'm not wrong, increasing the `max_parallel_jobs` to 2 (in Parameters) would solve that.

> I am sure this was asked and answered before, but I wasn't able to find any information. If elkarbackup already handles connection loss, it would be nice to add it to the docs, so that users know they don't have to worry about shutting down their clients during sync.

No, nobody asked that before, probably because most of us are using Elkarbackup to back up servers.

If you want to back up clients, you could trigger backups on-demand as alternative: https://github.com/elkarbackup/elkarbackup/wiki/FAQ#remotely-job-execution

Note that this will run only the lowest retain level.

**Comment by lukas-mertens** [comment]
Ok, good to know how it works. Remotely triggering the job wouldn't work for me though. Sometimes I use my PC only for a few minutes and I have got some huge folders that need at least an hour to sync. A solution where elkarbackup picks up the previously started job again would be nice. I would help with a Pull Request, but at the moment I don't have the time to get myself familiar with the codebase. 

Currently I use a raspberry pi with an external harddrive that runs elkarbackup inside a docker container. I am going to add a small lcd screen that displays remaining harddrive capacity, job status etc. I created a repo that contains a rpi-compatible fork of elkarbackup+docker if someone wants to build a similar setup: https://github.com/lukas-mertens/elkarbackup-rpi

**Comment by xezpeleta** [comment]
Hi @lukas-mertens 

Just out of curiosity, what distro do you use in you RPi? Did you change the docker files to make it compatible with RPi?

Thanks

**Comment by lukas-mertens** [comment]
I am using a standard raspbian image. To make elkarbackup compatible with the pi I replaced all dependencies without builds for ARM-Processors with similar packages with ARM-Support.

**Comment by xezpeleta** [comment]
Ok, as alternative to Docker you can use the our standard DEB package in RPi.

**Comment by xezpeleta** [comment]
Hi @lukas-mertens 

It won't be implemented as you want, sorry. Elkarbackup is basically a web UI for Rsnapshot and Rsnapshot does not support continuing a previously failed job like you think. The host must be available at least for the "sync" stage ("_Sync first_" option in Elkarbackup). That's a mandatory requirement.

I gave your some alternatives, but apparently don't fit your needs. So, you probably need to design your own solution.

**Comment by lukas-mertens** [comment]
Ok. I will try to develop something myself then, thank you anyways! I thought there might be a hope that you already implemented something, which is why I asked ;)
