### ISSUE TITLE
Queue status not (always) updated

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#338]
Sometimes, if I check the status page during my scheduled backup, I see all the jobs queued, nothing running. Client status is READY.

![status_onlyqueued_1](https://user-images.githubusercontent.com/1846038/47389110-2f703280-d714-11e8-963f-1f781655881c.png)

If I check the log file, I see that actually the first backup job is running. So the status information is not being updated correctly.

However, it happens randomly. Same scheduled backup, some minutes later, shows the status page correctly:

![image](https://user-images.githubusercontent.com/1846038/47389201-6fcfb080-d714-11e8-9ee8-f5c3c4225acd.png)

**Comment by xezpeleta** [comment]
More info about this mysterious issue:

- It's 21:00. I have 29 jobs QUEUED. Max parallel job set to 1
- Current running job (according to the logs) is not in the Queue status. It's just been deleted from the queue and I can't see its status. But according to the logs it's running and it ends all OK.
- First item in queue is actually the next one to be run
- 12 min. later: some jobs ended. Now there are 21 jobs in the queue, and now yes it works as expected: first job is RUNNING and the rest of items are QUEUED.

**Comment by xezpeleta** [comment]
News: it might be related to the pagination. I've realized it shows the info correctly when the job list fits in one page.

**Comment by elacunza** [comment]
Have you seen this issue lately, @xezpeleta ?

**Comment by xezpeleta** [comment]
No, you can close it if you want
