### ISSUE TITLE
Environment variables not working in Docker

### ISSUE THREAD

**Issue by Bondeau** [elkarbackup/elkarbackup#339]
Hello,

Since the version 1.3.1 of Elkarbackup, the script execution don't know more the following enviroment variables :  
    ELKARBACKUP_LEVEL: possible values are JOB or CLIENT
    ELKARBACKUP_EVENT: possible values are PRE or POST
    ELKARBACKUP_URL: the value is the full URL of the job or client
    ELKARBACKUP_ID: the numeric job id or client id
    ELKARBACKUP_PATH: the full path of the snapshot root (only available in job scripts)
    ELKARBACKUP_STATUS: The output status of rsnapshot for post job scripts, -1 if pre scripts have failed, -2 if rsnapshot has been skipped, always 0 otherwise
    ELKARBACKUP_CLIENT_NAME: client name
    ELKARBACKUP_JOB_NAME: job name (empty in client)
    ELKARBACKUP_OWNER_EMAIL: job owner's email address (empty in client)
    ELKARBACKUP_RECIPIENT_LIST: job recipients email addresses (empty in client)
    ELKARBACKUP_CLIENT_TOTAL_SIZE: current client disk usage (in KB)
    ELKARBACKUP_JOB_TOTAL_SIZE: current job disk usage (in KB, empty in client)
    ELKARBACKUP_JOB_RUN_SIZE: data size backed up this run (in KB, empty in client)
    ELKARBACKUP_CLIENT_STARTTIME: client backup start timestamp (only available in client scripts)
    ELKARBACKUP_CLIENT_ENDTIME: client backup end timestamp (only available in post client scripts)
    ELKARBACKUP_JOB_STARTTIME: job backup start timestamp (only available in job scripts)
    ELKARBACKUP_JOB_ENDTIME: job backup end timestamp (only available in post job scripts)
    ELKARBACKUP_SSH_ARGS: advanced arguments for ssh conection

Is it be normal ?

**Comment by xezpeleta** [comment]
@Bondeau just to be sure, are you using docker elkarbackup with docker?

**Comment by Bondeau** [comment]
Yes, I'm using the docker version.
The environnement variables worked with 1.2.7 docker version.

**Comment by xezpeleta** [comment]
Yes, I've just discovered it's a problem related with sudo. I'll fix it as soon as possible.

Thanks

**Comment by xezpeleta** [comment]
I'm recreating a new image: https://hub.docker.com/r/elkarbackup/elkarbackup/builds/

**Comment by xezpeleta** [comment]
@Bondeau can you try the latest build (1.3.1-1)?

Thanks

**Comment by Bondeau** [comment]
Thank you very much for your responsiveness. 

I will test it tomorrow.

**Comment by Bondeau** [comment]
It works well now.
Thank you a lot for your work guys.
The tool is really good !
