### ISSUE TITLE
All clients stuck in status "NOT READY"

### ISSUE THREAD

**Issue by ccolic** [elkarbackup/elkarbackup#344]
Hi there

I recently installed the new version of Elkarbackup (v1.3.1) and added all of my clients that I want to backup.
I added some jobs and assigned the default policy.

If I select some of the jobs or clients in the "Jobs" page and click "Enqueue now", the backup jobs will show up as "Queued" and then start.
But if I don't do that, the jobs don't run daily like they should. In the "Status" page, all of my clients are in the status "NOT READY". If I leave them, they will be in this status for some days, without any backup running

The status page with all of my clients in status "NOT READY": 
![2018-11-05 13_43_35-windows 10 beta](https://user-images.githubusercontent.com/12933716/47998880-00d55d00-e101-11e8-907a-a201b5dc95df.png)

One of the clients:
![2018-11-05 13_43_35-windows 10 beta](https://user-images.githubusercontent.com/12933716/47998942-311cfb80-e101-11e8-8146-3eb1956895f3.png)

One of the jobs of that same client: 
![2018-11-05 13_46_40-windows 10 beta](https://user-images.githubusercontent.com/12933716/47998969-4560f880-e101-11e8-97e0-c68f4da417bc.png)

The log is just filled with "Nothing scheduled to run".

Why do my backups not run and why are my clients stuck in status "NOT READY?"

Thanks

**Comment by xezpeleta** [comment]
Hi @ccolic 

"Not ready" is just the initial status of a client. You have more information here: https://docs.elkarbackup.org/docs/backup-status.html

Did you try with the default policy and without any script?

**Comment by ccolic** [comment]
Hi

But why are all of my clients stuck in this initial status?

This one client is the only one with the pre-script active. All other clients should run without pre- or post-script.

**Comment by ccolic** [comment]
This problems seems to have fixed itself. After waiting some more days to see if it works, all the clients now run their specified schedules just as they should.

I didn't change anything, so I don't know what to tell you guys
