### ISSUE TITLE
Post job scripts failed: The "-1" option does not exist

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#345]
I provoked a pre job script error on purpose. Unexpectedly, the run_post_job_scripts function execution failed with the following log output:

```
elkarbackup_1  | [2018-11-05 23:10:41] BnvWeb.ERROR: Job "1" PRE script "willfail" execution failed. Diagnostic information follows:   {"source":"RunPreJobScriptsCommand","link":"null/client/1/job/1"}  
elkarbackup_1  | [2018-11-05 23:10:41] BnvWeb.ERROR: Pre job scripts failed: aborting job {"source":"StatusReport","link":"null/client/1/job/1"}  
elkarbackup_1  | 
elkarbackup_1  |                                                           
elkarbackup_1  |   [Symfony\Component\Console\Exception\RuntimeException]  
elkarbackup_1  |   The "-1" option does not exist.                         
elkarbackup_1  |                                                           
elkarbackup_1  | 
elkarbackup_1  | elkarbackup:run_post_job_scripts [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> <job> [<status>]
elkarbackup_1  | 
elkarbackup_1  | [2018-11-05 23:10:41] BnvWeb.ERROR: Post job scripts failed! {"source":"StatusReport","link":"null/client/1/job/1"}  
elkarbackup_1  | [2018-11-05 23:10:41] BnvWeb.INFO: There are no POST scripts to run for this client. {"source":"RunPostClientScriptsCommand","link":"null/client/1"}
```

**Comment by AndrewPaglusch** [comment]
I know this is an old issue, but I'm running into the exact same problem.

I have a pre-job script that backs up databases on the remote server. I intentionally caused it to fail in order to test my post-job script (which will send me an alert if a backup fails). I would have expected my post-job script to be run and send me an alert about the failed backup, but instead I get the following in the logs:

```
[2020-06-12 16:07:51] BnvWeb.INFO: There are no PRE scripts to run for this client. {"source":"RunPreClientScriptsCommand","link":"null/client/6"}
[2020-06-12 16:08:05] BnvWeb.ERROR: Job "6" PRE script "Deploy Client Scripts" execution failed. Diagnostic information follows:  RESULTS WILL BE SAVED TO /scripts/docker01/results_1591996072.log {"source":"RunPreJobScriptsCommand","link":"null/client/6/job/6"}
[2020-06-12 16:08:05] BnvWeb.ERROR: Pre job scripts failed: aborting job {"source":"StatusReport","link":"null/client/6/job/6"}


  [Symfony\Component\Console\Exception\RuntimeException]
  The "-1" option does not exist.


elkarbackup:run_post_job_scripts [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> <job> [<status>]

[2020-06-12 16:08:05] BnvWeb.ERROR: Post job scripts failed! {"source":"StatusReport","link":"null/client/6/job/6"}
[2020-06-12 16:08:06] BnvWeb.INFO: There are no POST scripts to run for this client. {"source":"RunPostClientScriptsCommand","link":"null/client/6"}
[2020-06-12 16:08:06] BnvWeb.INFO: OK {"source":"StatusReport","link":"null/client/6"}
```

**Comment by elacunza** [comment]
To be clear here, we expect the post script to execute always, even if pre-script or job fail, right?

**Comment by xezpeleta** [comment]
> To be clear here, we expect the post script to execute always, even if pre-script or job fail, right?
Yes, I think that's the most intuitive behaviour.

I've just realized that we talked about this question long ago:

https://groups.google.com/g/elkarbackup-users/c/-V7pD6f0oh4

**Comment by elacunza** [comment]
I'm not very comfortable changing the behavior in a point release.
Maybe we can document the current behavior and change it in a future release (1.4.0 o later)?

**Comment by xezpeleta** [comment]
I agree. Definitely it's not a urgent change.

**Comment by elacunza** [comment]
We should change this for 2.0.0 release.

**Comment by elacunza** [comment]
Just found that we have a parameter for this: 
"Do post script on pre script failure" in "Manage parameters" menu.

Description is:
Execute post scripts on pre scripts failure
If a job pre script fails its post scripts will be executed depending on this parameter. 

It was add in #286 PR as part of the new job scheduler. (15 May 2018 ...)
Having this option (default value seems checked in a new install) makes this issue fixed right?
