### ISSUE TITLE
Problems with permissions

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#346]
Hi

I don't understand why, but for the last days we can't use the web interface of Elkarbackup.

When we try to login, nothing happens, and the login page does not load. As we can see in the log, something happens with the permissions of some files

`# tail -f /var/log/apache2/elkarbackup.error.log
[Fri Nov 09 08:34:37.090375 2018] [:error] [pid 17839] [client 10.23.38.170:36320] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/log/elkarbackup/prod.log" could not be opened: failed to open stream: Permission denied in /var/cache/elkarbackup/prod/classes.php:6013\nStack trace:\n#0 /var/cache/elkarbackup/prod/classes.php(5951): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/cache/elkarbackup/prod/classes.php(6122): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/cache/elkarbackup/prod/classes.php(6412): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /var/cache/elkarbackup/prod/classes.php(6517): Monolog\\Logger->addRecord(500, 'Uncaught PHP Ex...', Array)\n#4 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(89): Monolog\\Logger->critical('Uncaught PHP Ex...', Array)\n#5 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(45): Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener->logException(Object(UnexpectedValueExce in /var/cache/elkarbackup/prod/classes.php on line 6013`

The question is that we have not changed nothing during the last weeks, so I don't understand which could be the reason. 

Also, I'm getting cron errors

`/usr/share/elkarbackup/app/console elkarbackup:tick`

`PHP Warning:  rename(/usr/share/elkarbackup/app/logs/tmp-c0045j0152.log,/usr/share/elkarbackup/app/logs/jobs/c45j152_20181109055228_1.log): Permission denied in /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle/Command/RunJobCommand.php on line 325
PHP Warning:  rename(/usr/share/elkarbackup/app/logs/tmp-c0040j0137.log,/usr/share/elkarbackup/app/logs/jobs/c40j137_20181109073055_1.log): Permission denied in /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle/Command/RunJobCommand.php on line 325`

I've cleared the cache 
`# rm -fR /var/lib/elkarbackup/sessions/*`
`# rm -fR /var/cache/elkarbackup/*`
`# /usr/share/elkarbackup/app/console cache:clear --env=prod`
`# /usr/share/elkarbackup/app/console assetic:dump --env=prod`

but the problem remains. Happily Elkarbackup is running and is able to make the backups

Additional info:

`# /usr/share/elkarbackup/app/console --version`
`Symfony version 2.8.11 - app/prod`

`# cat /etc/debian_version`
`9.5`

`# getfacl /var/log/elkarbackup/`
`getfacl: Eliminando '/' inicial en nombres de ruta absolutos`
`# file: var/log/elkarbackup/`
`# owner: elkarbackup`
`# group: root`
`user::rwx`
`user:www-data:rwx`
`user:_apt:rwx`
`user:elkarbackup:rwx`
`group::r-x`
`mask::rwx`
`other::r-x`
`default:user::rwx`
`default:user:www-data:rwx`
`default:user:_apt:rwx`
`default:user:elkarbackup:rwx`
`default:group::r-x`
`default:mask::rwx`
`default:other::r-x`

`# getfacl /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle`
`getfacl: Eliminando '/' inicial en nombres de ruta absolutos`
`# file: usr/share/elkarbackup/src/Binovo/ElkarBackupBundle`
`# owner: root`
`# group: root`
`user::rwx`
`group::r-x`
`other::r-x`

Thanks !!

`

**Comment by parreitu** [comment]
Hi
Finally I've solved the problem changing the permissions of BnvLog.log and prod.log from 644 to 664

The question is: Are these the default permissions ? I would like to know what has happened  ...

Thanks.

**Comment by elacunza** [comment]
I see those permissions on our main elkarbackup server, yes.
