### ISSUE TITLE
Ubuntu elkarbackup keeps asking for update

### ISSUE THREAD

**Issue by kdpawson** [elkarbackup/elkarbackup#347]
Running Ubuntu 16.04 and was about to perform an upgrade to 18.04, however there is an update for elkarbackup that keeps asking to update and so I can't continue with the 18.04 upgrade. It reports "Please install all available updates for your release before upgrading."

I run the following:
sudo apt update
sudo apt upgrade

The following packages will be upgraded:
  elkarbackup
1 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/8,315 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Preconfiguring packages ...
(Reading database ... 123006 files and directories currently installed.)
Preparing to unpack .../elkarbackup_1.3.1-php7_all.deb ...
Unpacking elkarbackup (1.3.1-php7) over (1.3.1-php7) ...
Processing triggers for systemd (229-4ubuntu21.10) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up elkarbackup (1.3.1-php7) ...
Using /etc/elkarbackup/parameters.yml configuration ok
DB seems to be ready
Adding missing parameters as required
Delete cache content
Update DB
Create root user
Clean cache
Dump assests
Invalidate sessions

If I run "sudo apt update" again is still reports an update for elkarbackup - any ideas?

Elkarbackup is running and working fine.

**Comment by xezpeleta** [comment]
Hi @kdpawson 

Did you try "apt -f install" ?

Thanks

**Comment by kdpawson** [comment]
Yeah I did actually, forgot to mention that. Also tried removing and re-installing. Maybe I should try removing and purging? But I don't want to lose settings etc.

Thanks

**Comment by adrianles** [comment]
This also happens to @igorbga in ubuntu 16.04

**Comment by kdpawson** [comment]
I ended up removing the Elkar sources in /etc/apt/sources.list.d/ running update and finally running the OS upgrade "sudo do-release-upgrade"

Once that was completed I re-enabled the sources with the bionic version e.g. "deb http://elkarbackup.org/apt/ubuntu bionic main"

Switched to PHP7.2 and all good again!
Thanks
