### ISSUE TITLE
[Request] Supporting of S3 Amazon

### ISSUE THREAD

**Issue by Power2All** [elkarbackup/elkarbackup#350]
Is there any plans for supporting instead locally saving the files, to apply it to a S3 bucket ?
Would be very handy to forward all the data to a S3 Amazon bucket.
As I have it right now, I first sync it locally, and have a crontab doing a aws-cli sync action to sync the local data with the S3 bucket data, but would be nice if Elkar would support natively S3 Amazon :)

**Comment by elacunza** [comment]
Currently, this can be done using docker image and a persistent volume on S3 (for example with Kubernetes), or having elkarbackup installed on a virtualization platform with S3 bucket support for virtual disks.

We don't intend to support S3 buckets directly in the near future.
