### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#352]
Hello all

tried to run a backup job with pre-script. The logfile provide this information:

```
2019-01-14 19:14:04 | ERROR | RunPreJobScriptsCommand |   | Job "1" PRE script "MySqlDumpAllDatabases.sh" execution failed. Diagnostic information follows:  sudo: unable to execute /var/spool/elkarbackup/uploads/0002.script: No such file or directory |   | /client/1/job/1
```

I understand it this way, that the script doesn't exist, but I can see the script in mentioned location:

```
pi@nextcloud-bkp:/var/spool/elkarbackup/uploads $ ls -alF
total 12
drwxr-xr-x 2 www-data    www-data    4096 Jan 14 19:04 ./
drwxr-xr-x 4 elkarbackup elkarbackup 4096 Jan 14 18:48 ../
-rwxr-xr-x 1 www-data    www-data    3280 Jan 14 19:04 0002.script*
pi@nextcloud-bkp:/var/spool/elkarbackup/uploads $
```

Any idea how to get it fixed?

Kind regards
//neph

**Comment by jwag59** [comment]
I don't know elkarbackup at all well, but have you tried changing the ownership of the script to elkarbackup. Currently it is owned by www-data and perhaps the sudo is changing to user elkarbackup to run the script.

**Comment by nephilim75** [comment]
> I don't know elkarbackup at all well, but have you tried changing the ownership of the script to elkarbackup. Currently it is owned by www-data and perhaps the sudo is changing to user elkarbackup to run the script.

Changed ownership. DId not solve the issue.

> Can you try with a simple script? Do you have the same error?

It worked, BUT...

The new script was saved as UNIX script (LF). That was why it was working.

Then I converted the database script from Windows format (CR+LF) into UNIX (LF) and it worked as well. So, it wasn't an permission issue, it was caused by wrong format.

Thank you.

kind regards
//neph
