### ISSUE TITLE
Centos 7 Update

### ISSUE THREAD

**Issue by lebrongoat** [elkarbackup/elkarbackup#354]
We're currently on 1.2.7 Elkar Version on a Centos 7. We've followed the wiki procedure to install and everything is fine. What is the procedure to update Elkar version to the latest and mantain all data?
Do we have to follow the wiki install guide again or something else?

**Comment by vruiz2019** [comment]
Hello I have installed elkarbackup with Centos 7, php 7. 0.33 and Mariadb and deactivated selinux, in the installation everything worked apparently well.

The problems have occurred in the processes that run in background or automated.

I did not run the ssh key generation from the options menu, nor did the backupp tasks run alone, they only work if I launch them from the command line.
Os dejo mi parameters.yml por si sirve de algo

 database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: elkarbackup
    database_user: elkarbackup
    database_password: elkarbackup
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fba546d6ab6abc4a01dd1d161772a14e093c7aa2
    database_path: null
    upload_dir: /var/spool/elkarbackup/uploads
    public_key: /var/lib/elkarbackup/.ssh/id_rsa.pub
    max_log_age: P1Y
    tmp_dir: /tmp
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
    url_prefix: null
    disable_background: false
    mailer_from: null
    tahoe_active: false
    home: /var/lib/elkarbackup
    max_parallel_jobs: 1
    post_on_pre_fail: true

**Comment by elacunza** [comment]
We have decided not to support CentOS with native package unless someone contributes that support. Upgrade path is docker image. Thanks.
