### ISSUE TITLE
Backup Job Blocked

### ISSUE THREAD

**Issue by vruiz2019** [elkarbackup/elkarbackup#355]
Hello, I have a problem with elkarbackup, the jopbs that I am launching do not run alone, neither in programmed nor in running now, I have launched the /usr/local/elkarbackup/app/console  elkarbackup:tick
 command and with this released manually they seem to be working, now I have been blocked in a job and I can not move forward even though I gave it to abort it has stayed in abort
In the console I have this log

-----ERROR: Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined offset: 5 in /usr/local/elkarbackup/src/Binovo/ElkarBackupBundle/Command/TickCommand.php:443
Stack trace:
#0 /usr/local/elkarbackup/src/Binovo/ElkarBackupBundle/Command/TickCommand.php(443): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined offse...', '/usr/local/elka...', 443, Array)
#1 /usr/local/elkarbackup/src/Binovo/ElkarBackupBundle/Command/TickCommand.php(269): Binovo\ElkarBackupBundle\Command\TickCommand->processJobState(Object(Binovo\ElkarBackupBundle\Entity\Queue))
#2 /usr/local/elkarbackup/src/Binovo/ElkarBackupBundle/Command/TickCommand.php(96): Binovo\ElkarBackupBundle\Command\TickCommand->processQueueElements(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/local/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(259): Binovo\ElkarBackupBundle\Command\TickCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/local/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(863): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /usr/local/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Binovo\ElkarBackupBundle\Command\TickCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/local/elkarbackup/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(92): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /usr/local/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/local/elkarbackup/app/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#9 {main}[2019-02-18 10:47:07] translation.WARNING: Translation not found. {"id":"Exception running queued commands: %exceptionmsg%","domain":"BinovoElkarBackup","locale":"en"} 

Thank you very much for the help

**Comment by elacunza** [comment]
What linux distro? How did you install Elkarbackup?

**Comment by elacunza** [comment]
Closing after 1 month waiting reporter input
