### ISSUE TITLE
Backup job failed

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#356]
Hello guys,

need some assistance. One of my backup jobs is failing. Error log returns:

```
Command failed: [unknown error] rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]\n/usr/bin/rsnapshot -c /tmp/rsnapshot.1_3.cfg sync: ERROR: /usr/bin/rsync returned 11 while processing root@sub.domain.de:/media/usbhdd-a/nextcloud\ntouch /media/usbhdd-a/backups/0001/0003/.sync/\nrm -f /tmp/rsnapshot.0001_0003.pid\n/usr/bin/rsnapshot -c /tmp/rsnapshot.1_3.cfg sync: ERROR: /usr/bin/rsnapshot -c /tmp/rsnapshot.1_3.cfg sync: completed, but with some errors
```

Any idea what it means and how I can get it fixed?

Kind regards
//neph

PS: What does this feature mean?

![grafik](https://user-images.githubusercontent.com/19992865/52991109-85778d00-340b-11e9-9dca-094f7a61261f.png)

**Comment by elacunza** [comment]
Just look at rsync return value 11 for an explanation.

The red disk is the storage space display. Red is almost full or full.
