### ISSUE TITLE
Stuck on large job

### ISSUE THREAD

**Issue by mchlrv** [elkarbackup/elkarbackup#362]
I'm trying to backup a large storage server but it seems to be stopping after a few GB's (between 10 - 55 GB).

When checking the job log (tmp-c0001j0001.log) is show there is no disk space left on the devices:
> [2019-03-15T15:28:35] rsync: write failed on "/backup/0001/0001/.sync/proc/kcore": No space left on device (28)
[2019-03-15T15:28:38] rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]

However when I check the available disk space there is plenty:
> [root@backup10 logs]# df -h /backup/
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/VG1-backup  917G   11G  860G   2% /backup

Although it is not consuming any disk space it keeps utilizing the network at the maximum throughput:
>NET | eth0     97% | pcki  161198 | pcko   33923 | sp 1000 Mbps | si  978 Mbps | so 9533 Kbps

**Comment by elacunza** [comment]
This is very old, maybe a delete file was open by another process. Please send new mail if the issue persists.
