### ISSUE TITLE
Ignoring Policy Excludes

### ISSUE THREAD

**Issue by mchlrv** [elkarbackup/elkarbackup#363]
In my default policy I've stated to ignore the following paths:
>/tmp/
/proc/
/sys/
/dev/

However when the backup runs it just backups these paths:
>[root@backup10 logs]# ls -alF /backup/0001/0001/.sync/ | grep -i proc
drwxrwxr-x 205 elkarbackup elkarbackup  4096 Mar 15 15:28 proc/

Looking at the config of this job it also does not state an exclude for these paths.

**Comment by elacunza** [comment]
Can you reproduce this on latest version 1.3.3?

**Comment by elacunza** [comment]
Closing after 1 month waiting reporter input
