### ISSUE TITLE
Centos 7 , process not run

### ISSUE THREAD

**Issue by vruiz2019** [elkarbackup/elkarbackup#364]
Scheduled tasks are not executed and pass to queued, if I manually launch them they remain queued, and the only way to execute them is from the console with the command "console elkarbackup: tick"

It is executed in Centos 7, PHP 7.1, MariaDB 5.5 and Selinux deactivated

Can anybody help me

**Comment by HenryRc0** [comment]
The command "console elkarbackup:tick" should be executed by cron every minute.

The content of my crontab file in /etc/cron.d looks like this:
* * * * *       elkarbackup            /opt/elkarbackup/app/console elkarbackup:tick

Do you have such a file with this content?

**Comment by HenryRc0** [comment]
The above funny symbols should be five *

**Comment by vruiz2019** [comment]
300/5000
It is true, I have more machines with the karbackup and they work without problems, checking the logs I have seen the following log
[2019-03-21 09:40:01] BnvWeb.INFO: Nothing scheduled to run. {"source": "TickCommand"}


But in any machine I have put in cron that task manually, this is normal?

Thank you very much for your reply

**Comment by vruiz2019** [comment]
I have reviewed /etc/crond.d/elkarbackup and found the file with its lines,

* * * * *               elkarbackup     /usr/local/elkarbackup/app/console elkarbackup:tick
0 0 * * 1               elkarbackup     /usr/local/elkarbackup/app/console tahoe:renew_leases

But checking the cron logs these are not running, others that I have in cron if

**Comment by HenryRc0** [comment]
Not even errors in the cron logs?

**Comment by vruiz2019** [comment]
Mar 21 08:55:24 [localhost] crond[32031]: (root) BAD FILE MODE (/etc/cron.d/elkarbackup)

**Comment by vruiz2019** [comment]
* * * * * elkarbackup /usr/local/elkarbackup/app/console elkarbackup:tick
0 0 * * 1 elkarbackup /usr/local/elkarbackup/app/console tahoe:renew_leases

I have copied the lines to the cron of / etc / crontab and it works but with the cron.d cron it does not work

**Comment by vruiz2019** [comment]
Sorry 

`* * * * * elkarbackup /usr/local/elkarbackup/app/console elkarbackup:tick
0 0 * * 1 elkarbackup /usr/local/elkarbackup/app/console tahoe:renew_leases
`

**Comment by HenryRc0** [comment]
Check file permissions on /etc/cron.d/elkarbackup - shoud be:  -rw-r--r--.
if not try chmod 0644 /etc/cron.d/elkarbackup

**Comment by vruiz2019** [comment]
You were in the certain, the permissions of the file were bad, the strange thing is that they are not changed by me ...

**Comment by HenryRc0** [comment]
It wasn´t me either ;-)

**Comment by vruiz2019** [comment]
Thanks Friend

**Comment by HenryRc0** [comment]
you are welcome

**Comment by vruiz2019** [comment]
I've been doing it by hand for 3 weeks ...
