### ISSUE TITLE
Permissions on restore

### ISSUE THREAD

**Issue by q5616417** [elkarbackup/elkarbackup#365]
Hello,
on the linux machine I'd like to backup, I've created a user 'backup' which is allowed to perform rsync, rsnapshot and mkdir with sudo. This user connects via ssh  from elkarbackup to the machine which I want to backup. In the webinterface of elkarbackup, I've set the rsync long args --rsync-path="sudo rsync" --fake-super. Backup works fine, but when I try to restore, I got a permission error, that mkdir ist not allowed for that backup user. So, I've put "sudo mkdir $1" in a script in the users home directory anp added this to the beginning of the PATH-variable in the .ssh/environment file. Now, I get another error, I am stuck with at the moment:

BnvWeb.ERROR: Error message rsync: failed to set times on "<folder>": Operation not permitted (1) rsync: recv_generator: mkdir "<folder>/<subfolder>" failed: Permission denied (13) *** Skipping any contents from this failed directory *** 

The last one is repeated for each subfolder.

Any idea how I can successfully do a restore of the folder structure?

Best regards 

Thomas

**Comment by elacunza** [comment]
The user you use for backup, should have write permission on destination for restore to work properly.
I don't really like this way of restoring, better download the backup and put it in the correctly place by hand.
