### ISSUE TITLE
PostScript does not work

### ISSUE THREAD

**Issue by q5616417** [elkarbackup/elkarbackup#366]
Hello,
I wrote a postScript, that does not work. I'like to move a directory after backup is done and then create a new (empty) one with the same name. Output is: 

> Job "1" POST script "myscript" execution failed. Diagnostic information follows: mkdir: cannot create directory ‘/my/directory’: No such file or directory 

When I execute the script directly on the client, it works as expected. If Elkarbackup executes it, it gives this error.
I connect to the client as "backup@myclient". When I execute the script directly at the client, I do is user "backup"

Why can't Elkarbackup execute the script? To which location does Elkarbackup temporarily copy the script, so that I can troubleshoot it?

Best regards

Thomas

**Comment by elacunza** [comment]
Hi,

El 28/3/19 a las 13:07, q5616417 escribió:
>
> Hello,
> I wrote a postScript, that does not work. I'like to move a directory 
> after backup is done and then create a new (empty) one with the same 
> name. Output is:
>
>     Job "1" POST script "myscript" execution failed. Diagnostic
>     information follows: mkdir: cannot create directory
>     ‘/my/directory’: No such file or directory
>
> When I execute the script directly on the client, it works as 
> expected. If Elkarbackup executes it, it gives this error.
> I connect to the client as "backup@myclient". When I execute the 
> script directly at the client, I do is user "backup"
>
> Why can't Elkarbackup execute the script? To which location does 
> Elkarbackup temporarily copy the script, so that I can troubleshoot it?
>
You must take into account that post-script is run on Elkarbackup host, 
not in job host. If you want to execute orders in a job's host, then use 
ssh with the desired commands, then test calling the script from within 
Elkarbackup host with elkarbackup user.

Cheers
Eneko

-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943569206
Astigarraga bidea 2, 2º izq. oficina 11; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by q5616417** [comment]
Ok, good to know, thank you for your help :)
