### ISSUE TITLE
PostgreSQL backup

### ISSUE THREAD

**Issue by rolishv** [elkarbackup/elkarbackup#367]
Hello!

I have set up elkarbackup server on my linux machine, I managed to add some linux and windows clients and everything seems to be working fine.

I have a problem doing PostgreSQL backup using this script:
https://github.com/elkarbackup/elkarbackup-scripts/blob/master/backup-postgresql/backup-postgresql.sh#L57

I am getting this error:

Job "3" PRE script "PG Dump Script" execution failed. Diagnostic information follows: sudo: unable to execute /var/spool/elkarbackup/uploads/0003.script: No such file or directory |   | /client/3/job/3
-- | -- | --

Of course the file is there on my backup server, right beside other scripts with the same permissions. But for some reason it can't run.

**Comment by rolishv** [comment]
The problem seems to be in this line of the rsnapshot .conf file:

cmd_preexec
/usr/bin/env ELKARBACKUP_LEVEL="JOB" ELKARBACKUP_EVENT="PRE" ELKARBACKUP_URL="root@*.*.*.*:/tmp/pgsql" ELKARBACKUP_ID="3" ELKARBACKUP_PATH="/backup/PGSQL/0003/0003" ELKARBACKUP_STATUS="0" sudo "/var/spool/elkarbackup/uploads/0003.script" 2>&1

**Comment by elacunza** [comment]
There seems to be some problem with the file. What distro? Can you send the result of "ls -l /var/spool/elkarbackup/uploads/0003.script" ?

**Comment by elacunza** [comment]
Closing as reporter isn't providing info after a month

**Comment by Abdull** [comment]
@rolishv

We had the same problem of `sudo: unable to execute /var/spool/elkarbackup/uploads/0003.script: No such file or directory` with a post job script.

In our case it happened because the script file we uploaded was formatted incorrectly with Windows newlines.

Converting the script file to Linux newlines resolved the issue.
