### ISSUE TITLE
jquery-1.12.0.min.js is misssing in CentOS7 installation

### ISSUE THREAD

**Issue by FireGrace** [elkarbackup/elkarbackup#368]
Issue is similar to #360 .
----
Problem:

After following instructions for CentOS7 at [elkar wiki](https://docs.elkarbackup.org/docs/installation.html), application ended up missing:
`jquery-1.12.0.min.js` at `/usr/local/elkarbackup/web/js/jquery/`.

It results in elkar being unable to add new clients via web-interface.
Putting jquery manually resolves the issue. No further errors in the logs.

----
Possible cause:
s restricted network. I can't download jquery directly. 
If so, than offline installation of elkar application is not possible.

----
To be honest, i do not know how elkar gets jquery into `/usr/local/elkarbackup/web/js/jquery/`, in the first place, and should be this issue be resolved at all.

**Comment by elacunza** [comment]
We have decided not to support CentOS with native package unless someone contributes that support. Upgrade path is docker image. Thanks.
