### ISSUE TITLE
CentOS7: SELlinux context is not persistent, after installation

### ISSUE THREAD

**Issue by FireGrace** [elkarbackup/elkarbackup#369]
I am aware of  issue #334 .
It clearly states, that persistent selinux policy changes are planned in future rpm release.
----
Problem:
After rerboot, apache user is unable to access files at `/usr/local/elkarbackup`,
All funtionality is lost. No related error message is displayed to user, from the web-browser.

----
Cause:
[eb-installer.sh](https://github.com/FireGrace/elkarbackup/blob/master/install/eb-installer.sh) at lines 452-454, uses chcon command, to set Selinux context. This change does not persist after reboot.

----
Solution:
Use `semanage fcontext` construct instead, followed with `restorecon -R /usr/local/elkarbackup`.

Solution have some problems in itself:

It introduces new dependency `policycoreutils-python` package for `semanage` command.
It introduces new dependency `policycoreutils` package for `restorecon` command.
Also Wiki needs to be updated.

**Comment by elacunza** [comment]
We have decided not to support CentOS with native package unless someone contributes that support. Upgrade path is docker image. Thanks.
