### ISSUE TITLE
Cambiar pantalla Edit client: borrar sección para editar tareas

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#37]
La pantalla actual de edición de cliente y tareas es un poco larga, y la parte de tareas queda un poco "mezclada". Propongo mejorarla de la siguiente forma:

- Crear en la actual dos pestañas
  * La primera será la que se muestre por defecto, con los datos del cliente
  * La segunda tendrá las tareas del cliente. Al estar separada de los datos de cliente, podemos hacer el listado más ancho (ya que no estamos usando la zona de ayuda), para intentar que cada tarea ocupe menos espacio vertical. 

No sé si tiene mucho sentido que podamos editar algunos campos de las tareas en el listado; por ejemplo la descripción o el elemento del que hacer backup no los pondría como editables (poco probable que sea necesaria una edición masiva).

**Comment by xezpeleta** [comment]
Tras hablarlo con @parreitu @alfredobz y JL Goitiz estamos todos de acuerdo en eliminar definitivamente el bloque inferior de tareas en la ventana "Edit client"

Depende de las prioridades, en un futuro podríamos implementar la funcionalidad de cambio de políticas de forma masiva (desde Policies). De momento ninguno de nosotros la hemos tenido que usar y no la vemos como crítica.

**Comment by elacunza** [comment]
Yo también lo veo OK.

On 26/03/15 20:37, Xabi wrote:
>
> Tras hablarlo con @parreitu <https://github.com/parreitu> @alfredobz 
> <https://github.com/alfredobz> y JL Goitiz estamos todos de acuerdo en 
> eliminar definitivamente el bloque inferior de tareas en la ventana 
> "Edit client"
>
> Depende de las prioridades, en un futuro podríamos implementar la 
> funcionalidad de cambio de políticas de forma masiva (desde Policies). 
> De momento ninguno de nosotros la hemos tenido que usar y no la vemos 
> como crítica.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/37#issuecomment-86685782>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es
