### ISSUE TITLE
Installation fais on Ubuntu 19.04 - installation fails due to MySql Password

### ISSUE THREAD

**Issue by Aesculapius** [elkarbackup/elkarbackup#376]
Installing Elkerbackup on Ubuntu 19.04, everything seems to go well until you try to visit the webpage, serving you an error-500 page on both http and https. The logs don't reveal much, but scrolling back to the installation lines on ssh gives the answer:

During the installation process, it is adviced to run 'mysql_secure_installation'. In there I chose the second option (medium) as required password strength.

But during the later installation of elkerbackup, it tries to create a user with much simpler password, thus fails to do so (mysql prohibits) and thus installation doesn't succeed.

Going to try now to lower the password requirements, then install elkerbackup and then change the ass requirements back.

Maybe the default password should be a bit more complex?

**Comment by 3c2b2ff5** [comment]
Isolved this issue. Please refer to [solve Mysql authentication problem](https://github.com/elkarbackup/elkarbackup/issues/377#issuecomment-526386614)

**Comment by Aesculapius** [comment]
Great, my (imho simpler solution) of starting with a simple password and upgrade it to a complex one later on, also works great :)
