### ISSUE TITLE
PHP Warning from doctrine ORM

### ISSUE THREAD

**Issue by karimba32** [elkarbackup/elkarbackup#381]
Hi,
Fresh install on elkarbackup from debian repos as per docs, however, once i enabled email settings i now get an email every minute with:

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2624
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2653

Seems there's some update to the doctrine/orm packages but don't know how to upgrade them.

Cheers

**Comment by karimba32** [comment]
can these emails be stopped at least then? 
45000+ in the mail queue

**Comment by parreitu** [comment]
Searching in Google, you can find lots of references to similar issues, most of them referred to symfony and PHP7.3, for example this: 

[https://stackoverflow.com/questions/54184707/warning-continue-targeting-switch-is-equivalent-to-break-did-you-mean-to-u](https://stackoverflow.com/questions/54184707/warning-continue-targeting-switch-is-equivalent-to-break-did-you-mean-to-u)

Could you try the solutions that they propose ?

**Comment by adrianles** [comment]
Since the warnings come from a third party's bundle, we should check if there is an available update for the bundle. Doctrine will likely have a php7.3 compatible version for the bundle.

**Comment by elacunza** [comment]
The issue here is PHP 7.3 . @karimba32 what distro is yours with this issue?

**Comment by elacunza** [comment]
I assume this is Debian 10, so assign milestone that I think will fix this.

**Comment by elacunza** [comment]
We're shipping doctrine/orm 2.7 in master/1.4.0, this should be fixed.
