### ISSUE TITLE
Step by step guide for docker

### ISSUE THREAD

**Issue by andrewfer000** [elkarbackup/elkarbackup#386]
I cant seem to find a good quick start guide for docker. If someone knows where one is or if one could be made that would be great because on Debian 10 it is impossible to install it because of PHP mysql-client errors

**Comment by andrewfer000** [comment]
https://github.com/elkarbackup/elkarbackup/wiki/DevelopmentEnvironment

Is this one good? I dont think so because I keep gettng
elkarbackup_1  | MySQL is unavailable - sleeping

**Comment by xezpeleta** [comment]
Hi @andrewfer000 

All Docker related doc is here: https://hub.docker.com/r/elkarbackup/elkarbackup/
