### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by cyberfarer** [elkarbackup/elkarbackup#387]
I have recently setup this software and I am evaluating. So far so good other than email notifications are not sent. I am using SMTP with a known good SMTP relay. Cron errors are emailed indicating the issue is not between my server and the email relay. 

I do not see any logging indicating an error. Where may I get more detailed logs and can I increase verbosity or is there a debug option?

Thank you.

**Comment by parreitu** [comment]
Hello
It's a bug that we are trying to solve now https://github.com/elkarbackup/elkarbackup/issues/340

**Comment by cyberfarer** [comment]
Thank you.
