### ISSUE TITLE
PID de tarea que no desaparece

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#39]
Aupa !!

Alguna que otra vez nos ha pasado que por alguna razón una tarea no ha podido concluir y el PID de proceso no se borra como es debido. Esto provoca que en la siguiente programación de la tarea esta no se pueda ejecutar. 

Este sería una ejemplo de una tarea que no se ha ejecutado en los últimos días por esta misma razón.

root@ElkarBackup:~# ls -la  /tmp/rsnapshot.0019_0053.pid
-rw-r--r-- 1 elkarbackup elkarbackup 5 ene 23 03:36 /tmp/rsnapshot.0019_0053.pid

**Comment by jaymami** [comment]
Hola amigos,

Tengo recientemente instalada vuestra aplicación y en alguna de mis primeras pruebas se me ha reproducido este mismo error. Tal y como comentáis se ha producido cuando durante la copia el usuario ha apagado el PC.

Saludos!
Josep
