### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by cyberfarer** [elkarbackup/elkarbackup#392]
Not really an issue, but a discussion.

Does anyone use encryption to protect their backups and if yes, what and how?

Full disk encryption is not an option for me as that train has left the station. I have experimented with ecyrptfs but I found the 'du -ks' process initiated by elkarbackup at the end of a sync took an extraordinary long period of time. So long, it would eventually "fail" the backup. I am wondering if anyone else has a better solution?

Thanks.

**Comment by elacunza** [comment]
We use cryptsetup to create a loopback encrypted device and mount it on /var/spool/elkarbackup/backups in some installations. It works well for us.
