### ISSUE TITLE
Installation fails on CentOS 7 with MySQL 8 and PHP 7.3

### ISSUE THREAD

**Issue by GeorgeGedox** [elkarbackup/elkarbackup#398]
I'm searching for an open-source backup solution for my server. I've stumbled upon this project that seems to be quite active, the trouble is that after around 10 tries to install this I gave up.

This project doesn't appear to support current versions of mysql and php, I've fixed some of the problems by downgrading to PHP 7.2 and creating the database and user manually but I still get this error
```
[Doctrine\DBAL\Exception\DriverException]
  An exception occured in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client



  [PDOException]
  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client



  [PDOException]
  PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]

```

Which tells me, along with the way the installer expects to create a mysql user via `GRANT` that mysql 8 is not supported. Any plans to support it? I would downgrade to 5.7 but I'm stuck with other applications requiring this version of mysql.

**Comment by xezpeleta** [comment]
The _caching_sha2_password_ authentication method will only be supported in PHP 7.4+. So, if you cannot downgrade to MySQL 5, you have two options:

### Configure MySQL 8 with legacy password authentication

```ini
#mysqld.cnf
[mysqld]
default-authentication-plugin=mysql_native_password
```

### Use 'mysql_native_password' for elkarbackup db user:

```sql
ALTER USER 'username'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
```

More info here: https://github.com/elkarbackup/elkarbackup/issues/377#issuecomment-526386614

> My work around was to create elkarbackup user in mysql and set the password with mysql_native_password and grant all privileges first and then install Elkarbackup.
> 
>     creating user syntax has changed as well, so with GRANT ALL the user cannot be created any more, so basically these are two steps now. First create the user and then gant privileges.
> 
> There definitely be more things to test, but these are the issues I had until now.

**Comment by GeorgeGedox** [comment]
I managed to install it on another server with older software and now I have working install, yet I have another problem so I'll close this issue and open a new one.
