### ISSUE TITLE
Marcar con otro color las ejecuciones de tareas con scripts fallidos

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#4]
En estos momentos un error en un pre-script de una tarea no queda marcado como error en la vista principal de tareas. 

Cierto es que rsnapshot tampoco tiene en cuenta estos errores, es decir, no suponen que la tarea de copia se deje de realizar, pero estaría bien que elkarbackup de alguna forma gestionara esa situación.

Como propuesta, se me ocurren dos opciones complementarias:

- Por un lado una alerta tipo warning que se envíe por email
- Por otro lado, mostrar la situación de forma visible en la vista principal, marcando la tarea con color amarillo.

**Comment by xezpeleta** [comment]
Cuando un script falla, el sistema de alertas por email funciona correctamente (ver nota final)

Tiene razón Peio: en el panel principal el estado del último backup aparece como "OK" (color verde). Debería aparecer por ejemplo como "WARNING" (color naranja).

A priori parece un cambio fácil. En teoría en el registro del último log podemos buscar scripts fallidos:

![con-error](https://cloud.githubusercontent.com/assets/1846038/6683227/9d3dcb50-cc83-11e4-993a-45866f96b35c.png)


A tener en cuenta:
- Para considerarse un error en el script, este debe terminar con un estado diferente de 0 (ej: exit 1)
- En la tarea es imprescindible tener configurado: nivel de alerta -> avisos/warnings o superior
