### ISSUE TITLE
Post script selection does not save on saving a new job

### ISSUE THREAD

**Issue by GeorgeGedox** [elkarbackup/elkarbackup#400]
Create a new job under a client, fill out the details, check a pre script and a post script to run, click save.

Expected behavior: All the job data should be correct, 1 script should run in pre, 1 in post
Actual behavior: Only the pre script runs

If you open the newly created job and go to post scripts you'll see the script is not checked but now if you check it and save it, it'll work.

**Comment by elacunza** [comment]
I think I found this issue sometime. Will try to reproduce and fix.
