### ISSUE TITLE
Elkharbackup POST JOB	ABORTING

### ISSUE THREAD

**Issue by Samirlinux** [elkarbackup/elkarbackup#402]
hi

Operations pending on this POST JOB [mode] Image of operations
  [https://f.top4top.io/p_1482qoggx1.jpg](url)

What is the solution

**Comment by GeorgeGedox** [comment]
Your script may be stuck, check to see if it's running using `top` or `htop`, it must be running under the elkarbackup user so it's easy to spot.

If the script is not there then you have the same bug that I have, that the jobs suddenly stop and the queue gets stuck and the log throws `unexpected offset` all the time, if that's the case then there is no fix.

**Comment by elacunza** [comment]
@Samirlinux @GeorgeGedox are you seeing this issue yet?

**Comment by GeorgeGedox** [comment]
> 
> 
> @Samirlinux @GeorgeGedox are you seeing this issue yet?

I have moved away to other backup solutions due to the slow updates and lack of communication from the developer, seems like this project has been abandoned

**Comment by elacunza** [comment]
Thanks, closing the issue thus.
