### ISSUE TITLE
Emails received are false and wrong warning

### ISSUE THREAD

**Issue by sgregori** [elkarbackup/elkarbackup#403]
As described at PR: https://github.com/elkarbackup/elkarbackup/pull/388

Every day, received 2 emails per job, and the info received was not true ( not a real error ), example:

MAIL 1:
```
10.0.0.13 | www | 2019-12-01 17:47:11 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 00:55:28 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 11:01:24 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 11:43:59 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 14:26:18 | ERROR | Job execution failed!
```

MAIL 2:
```
10.0.0.13 | www | 2019-12-01 17:47:11 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 00:55:28 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 11:01:24 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 11:43:59 | ERROR | Job execution failed!
10.0.0.13 | www | 2019-12-02 14:26:18 | ERROR | Job execution failed!
```

At web interface, same client, same job:
```
2019-12-03 01:58:29 | INFO | StatusReport |   | OK
2019-12-03 01:58:02 | INFO | RunJobCommand |   | Command succeeded.

2019-12-02 19:06:16 | INFO | StatusReport |   | OK
2019-12-02 19:05:53 | INFO | RunJobCommand |   | Command succeeded.

2019-12-01 11:55:05 | INFO | StatusReport |   | OK
2019-12-01 11:53:12 | INFO | RunJobCommand |   | Command succeeded.

2019-11-30 02:46:07 | INFO | StatusReport |   | OK
2019-11-30 02:45:52 | INFO | RunJobCommand |   | Command succeeded.
```

Seems that the notification queue has mixed the job results and creates wrong emails.

Thanks.

**Comment by sgregori** [comment]
Any news about this ? 

Thanks.

**Comment by sgregori** [comment]
Excuse me @parreitu any news about this bug ?

Sorry for the inconvenances and thank you.

**Comment by sgregori** [comment]
RIP elkarbackup.

Definetively searching for elkarbackup alternative, because seems that this project is dead.

BTRBK works fine for our BTRFS filesystems.

**Comment by parreitu** [comment]
The project is not dead, but at the moment I don't have time to invest in it. You are free to find another backup solution or to try to help us solving the problems you find.

**Comment by elacunza** [comment]
@sgregori are you yet having this issue or did you migrate?

**Comment by sgregori** [comment]
> @sgregori are you yet having this issue or did you migrate?

I disabled email notifications, because i can check one time per month the logs via website.

I'm using also another backup solution named BTRBK that works fine if your all servers are using BTRFS. 

Thanks for your interest.

**Comment by sgregori** [comment]
> @sgregori are you yet having this issue or did you migrate?

I disabled email notifications, because i can check one time per month the logs via website.

I'm using also another backup solution named BTRBK that works fine if your all servers are using BTRFS. 

Thanks for your interest.

**Comment by elacunza** [comment]
As there haven't been more reports like this, and reporter has workaround, closing.

**Comment by elacunza** [comment]
Thanks!
