### ISSUE TITLE
Docker image: script upload shows "500 Internal Server Error"

### ISSUE THREAD

**Issue by DesertRider** [elkarbackup/elkarbackup#404]
Hi,

I'm using the docker image 1.3.1 under a Rasperry Pi and I've been able to create a few jobs for 2 clients and run them without problems.

Now I'm trying to add a script (the one supplied in the documentation page to remove duplicates files) but I have this error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

I've check that the binding of /app/upload is working fine (docker bash, going to the directory and creating the script there). No problem.

Docker logs shows this (part of the apache's log file):
(...) "POST /script HTTP/1.1" 500 733 "http://localhost:8000/script/new (..)

Anyone have a guess on this one? Maybe a log file I could dig?

(This is the first time I open an issue on any software... please bear with me!)

**Comment by e1z0** [comment]
chmod 777 script dir will help for a moment, but it needs further fix, there are a lot of problems with permissions. Someone needs to implement environment variables UID and GID for docker...

**Comment by AndrewPaglusch** [comment]
Run this on the docker host to fix permissions on the uploads directory, which is where scripts are uploaded to.
```
chown -R 33:33 uploads
```

**Comment by elacunza** [comment]
I just tested this on master and script upload works OK, will be fixed in 1.4.0 if it wasn't before.
