### ISSUE TITLE
Upgrade from Ubuntu 18.04 to 20.04 Elkarbackup not running anymore

### ISSUE THREAD

**Issue by FezziFezzino** [elkarbackup/elkarbackup#407]
Hi there,

first of all, I know, never touch a running system... well, I did... :(
After the full upgrade, everything on the machine is running fine, except Elkarbackup...
I am a complete newbie and have no clue where to touch... or perhaps it is better to setup Elkarbackup completely new and ditch the existing backups ... 

When I type in my browser MyIP/elkarbackup the following shows up:

`unregister(); $apcLoader->register(true); */ require_once __DIR__.'/../app/AppKernel.php'; //require_once __DIR__.'/../app/AppCache.php'; $kernel = new AppKernel('prod', false); $kernel->loadClassCache(); //$kernel = new AppCache($kernel); // When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter //Request::enableHttpMethodParameterOverride(); $request = Request::createFromGlobals(); $response = $kernel->handle($request); $response->send(); $kernel->terminate($request, $response); `

Any chance to fix this issue? or better do a complete new installation? Can I somewhere secure the existing setup if?

Thx a lot for taking your time to look in to that issue and I look forward to hear from you..

Cheers from lock down Phuket/Thailand

**Comment by adrianles** [comment]
That looks like a dump of the file [app.php].(https://github.com/elkarbackup/elkarbackup/blob/996f91550923477c400b8816fa4277d0644e85a3/web/app.php#L14)

**Comment by FezziFezzino** [comment]
Yeah... but can't fix it... Get a 404 when http://myip/elkarbackup/app.php/login
I am too inexperienced to fix that... before I mess up more a will install it new.. :(
Thx anyway for the hint...

**Comment by FezziFezzino** [comment]
Hmm... it's getting strange for me...  New installed Ubuntu 20.04 LTS Minimal Installation
Did the complete setup as described for 18.04 (in assumption it is the same for the new 20.04 LTS)

And get a long list of errors presented... When going to the  http://myip/elkarbackup/app.php/login I get a Internal Server Error presented:
`Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. `

Does Elkarbackup even run under the new 20.04 LTS?
Anyone any ideas, pls let me know... I am clueless ... :(

Here the errors during installation:

`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the ma
nual that corresponds to your MySQL server version for the right syntax to use n
ear 'IDENTIFIED BY 'elkarbackup'' at line 1
Configure parameters
Adding missing parameters as required
Delete cache content
Update DB
PHP Warning:  count(): Parameter must be an array or an object that implements C
ountable in /usr/share/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjec
tion/Configuration.php on line 628
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 272
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 275
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 281
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 287
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 296
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 314
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 319
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine
/ORM/UnitOfWork.php on line 2636
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine
/ORM/UnitOfWork.php on line 2665
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995

                                                                                
                                                 
  [Doctrine\DBAL\Exception\ConnectionException]                                 
                                                 
  An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 
'elkarbackup'@'localhost' (using password: YES)  
                                                                                
                                                 

                                                                                
                 
  [Doctrine\DBAL\Driver\PDOException]                                           
                 
  SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'localhost' (using
 password: YES)  
                                                                                
                 

                                                                                
                 
  [PDOException]                                                                
                 
  SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'localhost' (using
 password: YES)  
                                                                                
                 

doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no
-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURAT
ION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--
verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] 
[--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

Create root user
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine
/ORM/UnitOfWork.php on line 2636
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine
/ORM/UnitOfWork.php on line 2665

                                                                                
                                                 
  [Doctrine\DBAL\Exception\ConnectionException]                                 
                                                 
  An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 
'elkarbackup'@'localhost' (using password: YES)  
                                                                                
                                                 

                                                                                
                 
  [Doctrine\DBAL\Driver\PDOException]                                           
                 
  SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'localhost' (using
 password: YES)  
                                                                                
                 

                                                                                
                 
  [PDOException]                                                                
                 
  SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'localhost' (using
 password: YES)  
                                                                                
                 

elkarbackup:create_admin [--reset] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose
] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--proc
ess-isolation] [-e|--env ENV] [--no-debug] [--] <command>

Clean cache
PHP Warning:  count(): Parameter must be an array or an object that implements C
ountable in /usr/share/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjec
tion/Configuration.php on line 628
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 272
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 275
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 281
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 287
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 296
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 314
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/zendframework/zend-code/s
rc/Reflection/MethodReflection.php on line 319
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine
/ORM/UnitOfWork.php on line 2636
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean
 to use "continue 2"? in /usr/share/elkarbackup/vendor/doctrine/orm/lib/Doctrine
/ORM/UnitOfWork.php on line 2665
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
PHP Notice:  Trying to access array offset on value of type null in /usr/share/e
lkarbackup/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser
.php on line 995
Dump assests
Invalidate sessions
Warning: The home dir /var/lib/elkarbackup you specified already exists.
Adding system user `elkarbackup' (UID 127) ...
Adding new group `elkarbackup' (GID 134) ...
Adding new user `elkarbackup' (UID 127) with group `elkarbackup' ...
The home directory `/var/lib/elkarbackup' already exists.  Not copying from `/et
c/skel'.
adduser: Warning: The home directory `/var/lib/elkarbackup' does not belong to t
he user you are currently creating.
Generating public/private rsa key pair.
Your identification has been saved in /var/lib/elkarbackup/.ssh/id_rsa
Your public key has been saved in /var/lib/elkarbackup/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Automatically generated key f
or elkarbackup.
The key's randomart image is:
+---[RSA 3072]----+
|             ..o |
| 
|         .o*.=o o|
|         .o.=====|
|          .=*X@EO|
+----[SHA256]-----+
No module matches rewrite
No module matches ssl
Processing triggers for systemd (245.4-4ubuntu3) ...
Processing triggers for libapache2-mod-php7.4 (7.4.3-4ubuntu1) ...
Processing triggers for php7.4-cli (7.4.3-4ubuntu1) ...
`

**Comment by elacunza** [comment]
We have two different issues here, first is that on upgrade there isn't PHP module in apache2 (I would say it's not an elkarbackup issue with the info we have). The second one seems an issue installing elkarbackup in Ubuntu 20.04 LTS; please report a new issue for Ubuntu 20.04 LTS support if you continue to reproduce the problem (note that Ubuntu 18.04 LTS is good and secure to use until at least 23.04 ;)

**Comment by FezziFezzino** [comment]
Hi again,
decided already to run it on Ubuntu 18.04.5 LTS as long as it is good and secure.
However, would be nice if the distro could be upgraded without getting in to trouble with the Elcarbackup installation.
Love that backup solution, really appreciate your development.
Thx for getting back to me and I will report if I find the time to do a test installation with Ubuntu 20.04 LTS and Elcarbackup

**Comment by elacunza** [comment]
Ubuntu 20.04  wasn't really supported/tested. We're deciding whether to continue releasing deb packages or just release docker image only (in elkarbackup-users Google group). Will keep this open unless we decide whether to continue releasing deb packages.

**Comment by FezziFezzino** [comment]
Ok, understood. Just joined the group you mentioned.
Keep up the good work, thank you.
