### ISSUE TITLE
Automatisation, industrialisation

### ISSUE THREAD

**Issue by FlorianCcj** [elkarbackup/elkarbackup#413]
Is there a way to use elkarbackup with automatisation tools, for example I create a new vm with ansible and I want to add a job to back-up the data. I already install the client with ansible also and my last manual action is to add it job and machine in the gui ... is there a way to add it with ... an api ? a cli ? or anything else.

Thanks

**Comment by elacunza** [comment]
There isn't any currently, but it would be quite interesting. Are you interested in developing such a CLI/API and PR? If so I'd be willing to review it.

**Comment by elacunza** [comment]
This was requested/planned in #260 , I'm closing this for being newer.
