### ISSUE TITLE
Not respecting change in rsnapshotconfig.txt.twig

### ISSUE THREAD

**Issue by onicniepytaj** [elkarbackup/elkarbackup#416]
Hi, yesterday I apt upgraded elkarbackup and it overwrote all my configs. I restored most of my things already but when I change /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle/Resources/views/Default/rsnapshotconfig.txt.twig file it is not respecting it. not even after a reboot. 

I have to change the ssh_args in that file from -o BatchMode=yes into -o BatchMode=no
After the change it's still the same:

/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded --stats --rsh=/usr/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=no root@XXX

**Comment by AndrewPaglusch** [comment]
Click on a client. Expand the "Advanced" section at the bottom. You can fill in any SSH args you would like in the "SSH Args" field.

**Comment by elacunza** [comment]
As @AndrewPaglusch said, the file you modified is not a configuration file. You must use SSH Args in Advanced section to add additional SSH args.
