### ISSUE TITLE
1.3.3 Cross Site Scripting

### ISSUE THREAD

**Issue by doroniz** [elkarbackup/elkarbackup#427]
Is there any update on the XSS in 1.3.3 as explained here?
https://packetstormsecurity.com/files/158930/ElkarBackup-1.3.3-Cross-Site-Scripting.html

**Comment by elacunza** [comment]
We weren't aware of it - but fixed a similar one recently. I'll look into patching in the next point release (in one or two weeks).

**Comment by elacunza** [comment]
Fixed in merge #434

**Comment by doroniz** [comment]
Thanks for the fast response
