### ISSUE TITLE
Remove eb-installer.sh support

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#436]
Remove eb-installer.sh and update docs accordingly. Existing installations should migrate to docker image.

**Comment by HenryRc0** [comment]
Will there be a migration documentation instead?

**Comment by elacunza** [comment]
If someone contributes, I'll have a look at it. Could you contribute such documentation?

**Comment by HenryRc0** [comment]
Not really - I haven´t got experience with docker -> That´s why I am asking. 
My biggest concern here is the database migration - but then again - maybe it´s easy.
I´ve just never have done such a thing.

**Comment by elacunza** [comment]
Yeah, will not be a problem, mysqldump + mysqlrestore, or just point docker image to you current Mysql server :-)

**Comment by elacunza** [comment]
Fixed in #439 and elkarbackup-docs#12
