### ISSUE TITLE
Wrong user/permissions

### ISSUE THREAD

**Issue by cyberfarer** [elkarbackup/elkarbackup#442]
I messed up my system upgrading to the latest version. I'm running on Ubuntu 18.04. TL;DR the installer attempted to replace MariaDB with MySQL. It all went sideways. I have recovered my DB but I have an issue with scripts. The Apache web server runs as www-data and elkarbackup has a user/group and home directory. When the scripts run, they are running as www-data and fail. 

How does www-data execute a script as elkarbackup?

Log entry auth.log:
`Feb  3 14:40:03 ELKARBACKUP sudo: www-data : user NOT in sudoers ; TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/var/spool/elkarbackup/uploads/0002.script`

Log error elkarbackup:
`Job "3" PRE script "Mount Encrypted" execution failed. Diagnostic information follows: sudo: no tty present and no askpass program specified`

Thank you.

**Comment by elacunza** [comment]
Please use googlegroups "elkarbackup-user" mailing list to try to get help, besides developers other users could help you as well. Thanks
