### ISSUE TITLE
Fix Docker files for Symfony 3.4

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#446]
We should check whether we need modified files for Docker anymore:
docker/app.php
docker/app_dev.php
docker/composer.json.docker
docker/src/Builder.php

**Comment by xezpeleta** [comment]
First of all I saw we need to do few changes:
 - [ ] Upgrade from PHP 7.1 to 7.3 (or higher) in Docker image
 - [ ] Change console path from `app/console` to `bin/console`

**Comment by elacunza** [comment]
These changes have been done in #449
