### ISSUE TITLE
Should/Could we drop tahoe support

### ISSUE THREAD

**Issue by igorbga** [elkarbackup/elkarbackup#457]
Now that @uanabitarte is working towards upgrading Symfony versions in Elkarbackup I think that it might be worth rethinking the option of dropping Tahoe support.

Tahoe support was added to Elkarbackup years ago in order to allow some kind of offsite backup redundancy composed by "collaborative" servers of different organizations. It was a nice and probably too idealist idea but... is actually someone using it ?

Not sure if migrating it will give any headache, but I suspect that this feature has not been tested in a reasonable way for quite a long time and there is no any issue that suggest any activity related to this feature recently. 

So, could we just consider removing this feature as part of the upgrade to Symfony 4.4 ? @xezpeleta , @elacunza

**Comment by elacunza** [comment]
I wrote about this on the user mailing list and nobody objected.
We haven't tested Tahoe support for 1.4.0 and there isn't any time planned for it.
If we drop support we should call the new version 2.0.0 and not 1.5.0

**Comment by xezpeleta** [comment]
I agree. We should officially remove Tahoe support, as (apparently) nobody uses it and we're not going to test it in upcoming releases.

If you prefer, we can do it later, so in this way we can match the major version change with some interesting new feature ( #260 ?), to encourage migration :)

**Comment by elacunza** [comment]
Problem is that we are not testing Tahoe, and that it could end totally broken.

What about releasing 1.4.0 as 2.0.0 with Tahoe removed?

We don't want to waste any time on that, except for its removal really.

**Comment by xezpeleta** [comment]
> What about releasing 1.4.0 as 2.0.0 with Tahoe removed?

Looks good to me!

**Comment by igorbga** [comment]
I agree with the change to 2.0.0. Even though we are not adding new features the 2.0.0 makes it clear that something has really changed.

I'll talk to @uanabitarte about it and we will just "lost" it in our way to Symfony 4.4.

I close the issue.

**Comment by elacunza** [comment]
Finally we'll release 2.0.0 with Tahoe support removed and Symfony 4.4.
Tahoe removal tracked in issue #458
