### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by cyberfarer** [elkarbackup/elkarbackup#462]
Greetings,

I am trying to use includes and excludes intelligently but I could use some insight. As you know, with systems, the data to be backed up may be in different locations and I don't necessarily want to backup up everything. So for a scenario,  assume I want to backup only /var/lib/mysql /var/www/html and /etc/apache2. 

If put / into exclude and the locations I want into include, it backs up everything. If I place /var into exclude put /var/lib/mysql and /var/www/html into include, it backs up nothing. 

Do I need a separate job for each directory?

Thanks.

**Comment by xezpeleta** [comment]
Please, if you want to get help, use the mailing list: elkarbackup-users@googlegroups.com

Thanks
