### ISSUE TITLE
There is a "0" on editUser -> Role select field

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#468]
We see a "0" before the Role select field:

![image](https://user-images.githubusercontent.com/1846038/111999820-a1374b00-8b1d-11eb-85f0-a1e644189d48.png)

**Comment by uanabitarte** [comment]
Is there any reason to have the roles choice embedded in a collection? That "0" is the index of the choiceType element inside the collection. We can remove that by adding directly a choiceType element to the form builder, instead of a collectionType.

**Comment by elacunza** [comment]
I don't think there's any reason, seems a bug introduced during the migration to Symfony 3.4, Elkarbackup 1.3.4 doesn't show the issue.

**Comment by elacunza** [comment]
Xabi, can you test and if the issue if fixed, close this? Thanks.

**Comment by xezpeleta** [comment]
I confirm is fixed now.

Thanks @uanabitarte !!
