### ISSUE TITLE
Install script failed

### ISSUE THREAD

**Issue by redesitos** [elkarbackup/elkarbackup#474]
Hi everyone, the script install process fail.

$ bash -c "$(curl -s https://raw.githubusercontent.com/elkarbackup/elkarbackup/master/install/eb-installer.sh)"

Many thanks.

**Comment by elacunza** [comment]
We're in the process of releasing v2.0 and removing that installer.
Please use .deb packages or docker images: https://hub.docker.com/r/elkarbackup/elkarbackup
