### ISSUE TITLE
Enhacement: CLI command for interaction with REST API

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#498]
Develop a CLI command, independent from an Elkarbackup/symfony deployment that will be able to control Elkarbackup from a remote host.
Maybe a .phar file could be a good solution; maybe we should put it in a separate repository (elkarbackup/elkarbackup-cli)

**Comment by elacunza** [comment]
@uanabitarte  is working on this in https://github.com/elkarbackup/elkarbackup-api-cli

**Comment by xezpeleta** [comment]
IMHO elkarbackup-cli was a cooler name :P

**Comment by elacunza** [comment]
Hehe, that was in case we had another cli not based on API ;)

But we can rename it... no strong feelings on my part.
