### ISSUE TITLE
Jobs Listed as "OK" When Elkarbackup Failed to Connect

### ISSUE THREAD

**Issue by AndrewPaglusch** [elkarbackup/elkarbackup#499]
My `docker-compose.yml` (relevant portion) is below. I pulled the "2.0.0" tag later today. It looks like the 2.0.0 tag's been changed a few times already. I grabbed the following image:

```
root@home-nas:/opt/docker# docker image ls --digests
REPOSITORY                 TAG       DIGEST                                                                    IMAGE ID       CREATED         SIZE
elkarbackup/elkarbackup    2.0.0     sha256:c259527a01db145328b21254064270f907da4331381cde5af626c0b9dfcf2ebf   48e4a41a3775   4 hours ago     659MB
```

docker-compose.yml:
```
  elkarbackup:
    image: elkarbackup/elkarbackup:2.0.0
    container_name: elkarbackup
    restart: always
    environment:
      SYMFONY__DATABASE__PASSWORD: "REDACTED"
      SYMFONY__DATABASE__HOST: elkarbackup-db
      EB_CRON: "enabled"
      TZ: "America/Chicago"
      PHP_TZ: "America/Chicago"
    volumes:
      - /tank/serverbackups:/app/backups
      - ./elkarbackup/uploads:/app/uploads
      - ./elkarbackup/scripts:/scripts
      - ./elkarbackup/sshkeys:/app/.ssh
    ports:
      - 80:80
  elkarbackup-db:
    image: mysql:5.7.22
    container_name: elkarbackup-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "REDACTED"
    volumes:
      - ./elkarbackup/db:/var/lib/mysql
```

I have a server (named `pbs02`) that is currently powered off and sitting next to me on the floor as I type this. After upgrading to Elkarbackup v2.0.0, I ran a backup against `pbs02` and was surprised to see that it resulted in a green "OK" status in the backup list.

The logs, however, show that the backup completely failed. Subsequent backups of the server fail as expected, so I unfortunately can not share steps to reliably reproduce the issue. I'm not sure if this is a one-time problem, or if it will silently fail in the future again if the server is unreachable.

Here are the logs for the `pbs02` backup:

```
[2021-04-23T18:10:03] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.38_38.cfg Daily: started
[2021-04-23T18:10:03] Setting locale to POSIX "C"
[2021-04-23T18:10:03] echo 147 > /app/tmp/rsnapshot.0038_0038.pid
[2021-04-23T18:10:03] mkdir -m 0755 -p /app/backups/0038/0038/Daily.0/
[2021-04-23T18:10:03] /usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats <excludes redacted> /app/backups/0038/0038/Daily.0/.
[2021-04-23T18:10:06] ssh: connect to host pbs02 port 22: No route to host
[2021-04-23T18:10:06] rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
[2021-04-23T18:10:06] rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
[2021-04-23T18:10:06] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.38_38.cfg Daily: ERROR: /usr/bin/rsync returned 255 while processing pbs02:/
[2021-04-23T18:10:06] touch /app/backups/0038/0038/Daily.0/
[2021-04-23T18:10:06] rm -f /app/tmp/rsnapshot.0038_0038.pid
[2021-04-23T18:10:06] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.38_38.cfg Daily: ERROR: /usr/bin/rsnapshot -c /app/tmp/rsnapshot.38_38.cfg Daily: completed, but with some errors
```

**Comment by mattburchett** [comment]
I was able to confirm this bug as well after talking with @AndrewPaglusch. 

I have a server for offsite backups at his location and I had him remove the ethernet cable from my server. Elkarbackup reaches out to that server over a Wireguard tunnel and that had been established prior to him disconnecting the ethernet cable. 

I am running Elkarbackup in Docker and am currently running the latest commit of 2.0.0 available on Dockerhub:
```bash
backups01 /opt/docker/elkar/logs/jobs [125]# docker images --digests
REPOSITORY                TAG            DIGEST                                                                    IMAGE ID       CREATED         SIZE
elkarbackup/elkarbackup   2.0.0          sha256:c259527a01db145328b21254064270f907da4331381cde5af626c0b9dfcf2ebf   48e4a41a3775   4 hours ago     659MB
```

When running the backup job, the UI shows it as a successful backup: 

![image](https://user-images.githubusercontent.com/783042/115941852-d9a7ad00-a46c-11eb-937d-e56a7d362e84.png)

On the logs page, it clearly has failed the job:

![image](https://user-images.githubusercontent.com/783042/115941863-f04e0400-a46c-11eb-82a3-13f5ee818854.png)

and the logs seem to confirm that too:

```
[2021-04-24T02:43:42] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.39_39.cfg Daily: started
[2021-04-24T02:43:42] Setting locale to POSIX "C"
[2021-04-24T02:43:42] echo 522 > /app/tmp/rsnapshot.0039_0039.pid
[2021-04-24T02:43:42] /usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded --chmod=Fug=rwX,Dug=rwx,Fo=r,Do=rx --stats --inplace <excludes redacted> --rsh=/usr/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=no lros-pbs01.linuxrocker.cloud:/ /app/backups/0039/0039/Daily.0/.
[2021-04-24T02:45:49] ssh: connect to host lros-pbs01.linuxrocker.cloud port 22: Connection timed out
[2021-04-24T02:45:49] rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
[2021-04-24T02:45:49] rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
[2021-04-24T02:45:49] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.39_39.cfg Daily: ERROR: /usr/bin/rsync returned 255 while processing lros-pbs01.linuxrocker.cloud:/
[2021-04-24T02:45:49] touch /app/backups/0039/0039/Daily.0/
[2021-04-24T02:45:49] rm -f /app/tmp/rsnapshot.0039_0039.pid
[2021-04-24T02:45:49] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.39_39.cfg Daily: ERROR: /usr/bin/rsnapshot -c /app/tmp/rsnapshot.39_39.cfg Daily: completed, but with some errors
```

**Comment by elacunza** [comment]
Seems a bug, let's see if we can reproduce it. @uanabitarte can you try to reproduce/fix this?

**Comment by elacunza** [comment]
We seem unable to reproduce this issue.
@mattburchett you log screenshot seems to have logs unordered? Could you produce one with the logs in order?
The job error time is 2:45:49 but job post script log time is 2:44:40...
Also the client line should show "OK" but it's empty... maybe it's a GUI problem...?

**Comment by xezpeleta** [comment]
I think we have two different issues:

@AndrewPaglusch

> I ran a backup against pbs02 and was surprised to see that it resulted in a green "OK" status in the backup list.

Did you see the CLIENT row with the green OK and jobs with red FAIL?

![image](https://user-images.githubusercontent.com/1846038/116306143-fb729e00-a7a4-11eb-8c20-7549bc92d35e.png)

I agree that this can be confusing. Actually CLIENT will only show a red FAIL if its pre-post scripts return a value different from 0. Otherwise will be considered OK.

On the other hand, @mattburchett  tried to reproduce the issue and doing so he got a very rare error.

The key here is the warning message "_Job data could not be stored_" (from RunJobCommand).

https://github.com/elkarbackup/elkarbackup/blob/6254dfafd59d89793fbb1ee213e33995156b1fd0/src/Command/RunJobCommand.php#L247-L262

If I'm not wrong, this error should not happen. The only explanation I find is that the connection between Elkarbackup and the database was interrupted.

> Also the client line should show "OK" but it's empty... maybe it's a GUI problem...?
When a new client is created, on the first execution this line will remain empty until all its jobs are done.

**Comment by mattburchett** [comment]
@xezpeleta

> If I'm not wrong, this error should not happen. The only explanation I find is that the connection between Elkarbackup and the database was interrupted.

I am running the DB through docker on the same host that Elkar is hosted. Is it likely that it'd lose connection to the DB when it's local?

Here is my `docker-compose.yml` if you're interested:

```yaml
version: '3'
services:
  elkarbackup:
    restart: always
    image: elkarbackup/elkarbackup:2.0.0
    environment:
      SYMFONY__DATABASE__PASSWORD: "redacted"
      EB_CRON: "enabled"
      SYMFONY__EB__MAX__PARALLEL__JOBS: 3
    volumes:
      - '/storage/nas/backups/elkar:/app/backups'
      - '/opt/docker/elkar/uploads:/app/uploads'
      - '/opt/docker/elkar/.ssh:/app/.ssh'
      - '/opt/docker/elkar/scripts:/scripts'
      - '/opt/docker/elkar/logs:/app/elkarbackup/var/log'
    ports:
      - 8000:80

  db:
    restart: always
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "redacted"
    volumes:
      - '/opt/docker/elkar/db:/var/lib/mysql'
```

**Comment by xezpeleta** [comment]
Ok, I will try to reproduce it using the same config

**Comment by elacunza** [comment]
@AndrewPaglusch , can you check current v2.0.x branch? I just detected+fixed a weird lock problem that might be related... #530

**Comment by xezpeleta** [comment]
You can use the tag `elkarbackup/elkarbackup:2.0-dev`

https://hub.docker.com/layers/elkarbackup/elkarbackup/2.0-dev/images/sha256-9544a26fd10258a5d61ed1196ba51f5d0aa44613730b6efad427c3b885fa95ce?context=explore

**Comment by xezpeleta** [comment]
Hi, v2.0.1 has been released. Can you try with the folllowing image tag?

`elkarbackup/elkarbackup:2.0.1`

Thanks

**Comment by AndrewPaglusch** [comment]
Hey @xezpeleta, Matt and I typically meet up each Friday and work on projects together. We will both try the new tag out and report back. Thanks!

**Comment by mattburchett** [comment]
Hey @xezpeleta,

I tested out the `2.0.1` tag on my end. It seems to be failing as expected now.

**Comment by AndrewPaglusch** [comment]
All fixed. I now see that the client backup shows a failure message like it should. Thank you, @xezpeleta

**Comment by elacunza** [comment]
Thanks for reporting back to both!!
