### ISSUE TITLE
Opción de auto-restauración

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#5]
Propuesta: En la vista de restore, poner un botón alternativo para que el fichero o carpeta seleccionados se restauren automáticamente en su ubicación original.

Tenemos las credenciales para poder hacer el restore, ya que son las mismas que utilizamos para hacer la copia. 

Para evitar errores, habría que pedir confirmación al usuario.

**Comment by elacunza** [comment]
Tenemos un duplicado en #203 . Como este está en español y el otro en inglés, cierro este pidiendo disculpas con antelación a @parreitu
