### ISSUE TITLE
"Recordar contraseña" en el navegador puede cambiar la clave de MySQL sin querer

### ISSUE THREAD

**Issue by alfredobz** [elkarbackup/elkarbackup#50]
Kaixo.

En los listados de logs, en la última columna aparecen los enlaces a los clientes y tareas a las que se refiere la entrada de log de la base de datos.

Logueando como 10.22.3.86/elkarbackup redirige a …/elkarbackup/login.php

Entrando a logs, ir a clientes, crear el cliente 1. guardar y volver a logs:

Seleccionados TODOS:
En el listado de logs…aparece una línea “save client” que pone /elkarbackup/client y apunta a DIRIP/elkarbackup/client y nos lleva a un feo error 405.

Ir a policies, crear una nueva política, listar las políticas ir a los lobs, y aparece una línea “view policy”que pone /elkarbackup/policy y apunta a DIRIP/elkarbackup/policy que da un error 405.

Después aparece una línea “save policy” que pone /elkarbackup/policy/-1 y apunta a DIRIP/elkarbackup/policy/-1. Aparece una página en blanco.

Ir a scripts, crear un script, listar los scripts e ir a los lobs. Aparece una línea “save script 0000.script” que pone /elkarbackup/script/-1 y apunta a DIRIP/elkarbackup/script/-1. Aparece una página en blanco.

Si modifico el parámetro del nivel de warning de cuota, en el log aparece la línea “Set Parameter warning_load_level” y pone /elkarbackup/policies” apuntando a   DIRIP/elkarbackup/policies/ y va a esa dirección.

Si voy a mirar los parámetros de configuración, también me indica lo mismo en el log.
Si cambio el path de los ficheros de backup, me indica lo mismo.

Con users:
Si voy a usuarios, bien.
Si creo un usuario, pone “View user .” con enlace a /elkarbackup/user/new.
Al guardar el usuario, pone /elkarbackup/user/-1 que apunta a una página en blanco.
Si voy a cambiar el password de usuario y no lo cambio, el log no indica nada.

Si cambio el idioma, no indica nada.

Con el usuario jon, cambio el password, y lo indica, enviándome a /elkarbackup/users/2. Al pinchar en el enlace me aparece error 403 (forbiden). Al usuario root sí le deja acceder a la página del usuario.

Cuando voy a configuración -> Script de copia del repositoria y le doy a guardar sin hacer nada más, aparece “Updating key file” pero sin enlace.

Cuando se autentifican los usuarios aparece "Log in attempt with user:" . No aparecen los enlaces, y tampoco el nombre del usuario.

Cuando se ejecuta una tarea a mano, ya no aparece "/elkarbackup", con lo que los enlaces terminan en "Not found".

Parece que hay cosas por hacer en este tema.

**Comment by xezpeleta** [comment]
De momento lo cerramos al parecer que es un caso aislado. Si se ve necesarario lo volveremos a abrir.
