### ISSUE TITLE
Publickey download not working

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#500]
Hi,

I'm using Elkarbackup v2.0.0 on Docker (image `elkarbackup/elkarbackup:2.0.0`). When I download the public key with Curl I get an empty file:

```
> GET /config/publickey/get HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 26 Apr 2021 10:16:54 GMT
< Server: Apache/2.4.38 (Debian)
< X-Powered-By: PHP/7.3.27
< Content-Disposition: attachment; filename="Publickey.pub"
< Cache-Control: no-cache, private
< Content-Length: 0
< Content-Type: text/plain; charset=UTF-8
```

I see no errors in logs:

```
elkarbackup_1  | elkarbackup.local:80 172.29.0.1 - - [26/Apr/2021:12:16:54 +0200] "GET /config/publickey/get HTTP/1.1" 200 267 "-" "curl/7.58.0"
```

I confirm the keypair exists and it's accessible.

```
-rw-r--r-- 1 root root 416 Apr 26 12:12 /app/.ssh/id_rsa.pub
```

I'm using the default `docker-compose.yml` template.

Swapping the image to `elkarbackup/elkarbackup:1.3.5` the download works as expected.

**Comment by elacunza** [comment]
I can confirm this. @uanabitarte can you check it?
As a related note, I see that not showing "Manage parameters" menú in docker image prevents downloading pubkey from WUI... but this isn't new in 2.0.0

**Comment by xezpeleta** [comment]
> As a related note, I see that not showing "Manage parameters" menú in docker image prevents downloading pubkey from WUI... but this isn't new in 2.0.0

That change was made on purpose. Parameters in Docker are defined using environment variables (we cannot change `parameters.yml`).  I removed the access to "Manage parameters" until these parameters are stored in the DB (#485)

**Comment by elacunza** [comment]
Yes I know the reason for this, but it can be an inconvenience for the admin, something to look at as part of the rework yes ;)

**Comment by xezpeleta** [comment]
Thanks!! I confirm is fixed now
