### ISSUE TITLE
Job token generation doesn't work

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#514]
### Describe the bug

A clear and concise description of what the bug is. Include the following information:

- Elkarbackup version: master / v2.0.0
- Docker image name: elkarbackup/elkarbackup:2.0.0

### Steps to reproduce the behavior

1. I edit a Job
2. Advanced -> Token
3. Click on **Generate** button

### Expected vs actual behavior

It should create a token, which can be used to run (enqueue) a job remotely as documented [here](https://github.com/elkarbackup/elkarbackup/wiki/FAQ#remotely-job-execution)

```
curl -k -d "token=0602f4a69af07fcb1327cc8d3f1371e7" https://192.168.33.10/client/1/job/1/run
```

Anyway, maybe this "endpoint" should be moved to the API
What do you think @elacunza ?

### Logs

I can't see any error log

**Comment by elacunza** [comment]
We may move it to the API, but 2.0.0 has no API, so this should work.

**Comment by uanabitarte** [comment]
thank you! @xezpeleta

**Comment by xezpeleta** [comment]
Apparently there is a new bug
