### ISSUE TITLE
Propuesta para añadir un buscador

### ISSUE THREAD

**Issue by antton** [elkarbackup/elkarbackup#53]
Estaría bien poder contar con un buscador para poder localizar archivos entre los backups.
Pienso que sería una funcionalidad un poco pesada al menos para procesar los datos tal como los gestiona, pero es simplemente una propuesta.

**Comment by xezpeleta** [comment]
Se ha añadido en [Ideas](https://github.com/elkarbackup/elkarbackup/wiki/Ideas)

Cierro la incidencia
