### ISSUE TITLE
API: Incorrect notification email address with empty notifications_email and notifications_to "email" not set

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#535]
### Describe the bug

- Elkarbackup version: master

### Steps to reproduce the behavior

1. Call API - POST job with empty notificationsEmail and notificationsTo set only for "owner"

### Expected vs actual behavior

API returns error: {"detail": "Incorrect notification email address", "title": "An error occurred", "type": "https://tools.ietf.org/html/rfc2616#section-10"}
That should work because email can be empty if notificationsTo doesn't include email.

**Comment by uanabitarte** [comment]
Hi, did you send an empty string as notificationsEmail? I will make the commit to accept that, but I would suggest to just omit the notificationsEmail parameter in the request to leave it as null, as it is not required.

**Comment by elacunza** [comment]
Ok, I omited the param in ansible module call, but it may have and empty string value.
I'll check and report back, if null/omiting works then nothing is to fix. :-)

**Comment by elacunza** [comment]
Empty string and null value are not accepted. For null value:
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Serializer\Exception\UnexpectedValueException: "The input data is misformatted." at /app/elkarbackup/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php line 211 {"exception":"[object] (Symfony\\Component\\Serializer\\Exception\\UnexpectedValueException(code: 0): The input data is misformatted. at /app/elkarbackup/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php:211, Symfony\\Component\\Serializer\\Exception\\NotNormalizableValueException(code: 0): The type of the \"notificationsEmail\" attribute for class \"App\\Api\\Dto\\JobInput\" must be one of \"string\" (\"NULL\" given). at /app/elkarbackup/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:478)"} {"user":"[object] (App\\Entity\\User: {\"newPassword\":null})","user_email":"root@localhost","user_id":1,"user_name":"root"}

If I remove the field from the json, then it works and its value becomes null.

I think it should accept null value for the field. Not accepting empty string is OK.

**Comment by elacunza** [comment]
Also, can we make the error info more concrete? "The input data is misformatted" is not very helpful without the affected field name...

**Comment by elacunza** [comment]
There seems to be the same problem with include and exclude fields. If empty string is set, field have null value afterwards, but API doesn't accept null value.

**Comment by uanabitarte** [comment]
Ok, I think API won't accept null value in any field. I will try to change that.
