### ISSUE TITLE
Button "Run now" in edit job form doesn't work

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#536]
### Describe the bug

- Elkarbackup version: master, 2.0.1
- OS: Debian 10 Buster

### Steps to reproduce the behavior

1. Go to a existing job edit form
2. Click "Run now" button

### Expected vs actual behavior

It is expected the job to be qeued.
Instead nothing happens. Browser console shows an TyperError: checkbox is null when loading that form; could be related.

### Logs

Browser console (Firefox):
Uncaught TypeError: checkbox is null
    showHideEmailBox https://backup.binovo.net/js/edit-job.js:20
    initNotificationsEmail https://backup.binovo.net/js/edit-job.js:29
    <anonymous> https://backup.binovo.net/js/edit-job.js:32
    Dojo 66
    <anonymous> https://backup.binovo.net/js/edit-job.js:5

**Comment by larsfessler** [comment]
I have the same issue with a freshly installed instance, installed with ubuntu 20.4 apt

**Comment by larsfessler** [comment]
Since you can allways enqueue it from the jobs list it is in my case not the most pressing issue.
