### ISSUE TITLE
Restore to client gets stuck at Starting restore job

### ISSUE THREAD

**Issue by larsfessler** [elkarbackup/elkarbackup#543]
- Elkarbackup version: 2.0.1
- OS: Ubuntu 20.04 Focal

### Steps to reproduce the behavior

1. go to jobs
2. click the cloud arrow down button
3. navigate through the directories and click the link "Restore to client" behind one specific file
4. on the following page click submit - on another try i added the filename to the Remote path with same result
5. click Submit - Elkarbackup prints "Your backup restore process has been enqueued"

The restore does not appear on the Status page. Looking on the Logs page it never gets past "Starting restore job" - see screenshot.
![grafik](https://user-images.githubusercontent.com/71665588/117316317-c511de80-ae88-11eb-8d33-ec6c57ce0a92.png)

### Expected vs actual behavior

Expected: Restored file should appear in the original directory on the machine it was backuped from or log entry with helpful error information
Actual: it does not appear there nor anywhere else on that machine.

### Logs

[2021-05-06 14:35:13] 'BnvWeb.INFO: 'Client "1" restore started '{"source":"DefaultController","link":"/client/1"} 'fessler 'lars.fessler@bitbw.bwl.de
[2021-05-06 14:36:01] 'BnvWeb.INFO: 'About to run command: {"command":"elkarbackup:restore_backup","url":"XXXXX@XXX.XXX.XXX.XXX","sourcePath":"\/var\/spool\/elkarbackup\/backups\/0001\/0001\/.sync\/home\/fessler\/testfile","remotePath":"\/home\/fessler","sshArgs":null} '{"source":"TickCommand"} ' '
[2021-05-06 14:36:01] 'BnvWeb.INFO: 'Starting restore job  '{"source":"RestoreBackups"} ' '

**Comment by xezpeleta** [comment]
Confirmed. The output of `/var/log/elkarbackup/prod.log`:

> [2021-05-06 17:10:01] console.CRITICAL: Error thrown while running command "elkarbackup:tick". Message: "Class 'Symfony\Component\Process\Process' not found" {"exception":"[object] (Error(code: 0): Class 'Symfony\\Component\\Process\\Process' not found at /usr/share/elkarbackup/src/Command/RemoteRestoreCommand.php:70)","command":"elkarbackup:tick","message":"Class 'Symfony\\Component\\Process\\Process' not found"} {"user":null,"user_email":"","user_id":"","user_name":""}
> [2021-05-06 17:10:01] console.DEBUG: Command "elkarbackup:tick" exited with code "1" {"command":"elkarbackup:tick","code":1} {"user":null,"user_email":"","user_id":"","user_name":""}
> [2021-05-06 17:10:01] php.CRITICAL: Uncaught Error: Class 'Symfony\Component\Process\Process' not found {"exception":"[object] (Error(code: 0): Class 'Symfony\\Component\\Process\\Process' not found at /usr/share/elkarbackup/src/Command/RemoteRestoreCommand.php:70)"} {"user":null,"user_email":"","user_id":"","user_name":""}

**Comment by larsfessler** [comment]
Thanks for the quick confirmation. Will this be fixed soon? I don't ask to put pressure on the issue. It's only because we are in a decision process about a web gui for rsync. What i really like about this one is that it leverages rsnapshot. And with the restore function working it would enable my not so familiar with rsync colleagues to do much of the work themselves instead of comming to me.

**Comment by elacunza** [comment]
Can't tell for sure, I think will release 2.0.2 next week and 2.1.0 in 4 weeks. If someone has time to look into this it will be fixed for sure.
By the way, are you aware that file permissions are not preserved? #365

**Comment by elacunza** [comment]
@larsfessler could you build .deb package from v2.0.x branch and check that this is fixed for you?

**Comment by larsfessler** [comment]
It doesn't seem to work. It might have something to do with keep permissions while backing up. I did the cronjob change mentioned in issue #201. But even es i changed owner and group of a specific file i tried to restore to elkarbackup and checked if they can read the file, that didn't work.

This is the directory entry of the file i tried to restore:
![grafik](https://user-images.githubusercontent.com/71665588/117666146-dbc77680-b1a3-11eb-9de1-d49268c6ee8a.png)

To make the debian package i did this: https://github.com/elkarbackup/elkarbackup/wiki/BuildPackage
After dpkg -i the resulting file i rebooted the server to make sure the changes take effect.

![grafik](https://user-images.githubusercontent.com/71665588/117665645-5643c680-b1a3-11eb-9a5e-025831968929.png)

**Comment by elacunza** [comment]
Ok, this is another issue. 
You originally reported that restore job was not passing "Starting restore job", but now it does so it is fixed.
You now have a permission issue, can you post to elkarbackup-users@googlegroups.com so others can help you?
Thanks
