### ISSUE TITLE
Login with user which has the role User leads to http 403

### ISSUE THREAD

**Issue by larsfessler** [elkarbackup/elkarbackup#544]
Every time i login with a Elkarbackup user which has the role User instead of Admin this leads directly to http 403 forbidden.
If i change the user role to Admin and login again, everything is fine

Since out goal is to not give everybody admin permissions this - does anybody have a solution for this?

Thank you all!

**Comment by elacunza** [comment]
We don't have a solution for this currently. USER roles have been blocked in 2.0.x because see #488
