### ISSUE TITLE
Is there an option to encrypt backups?

### ISSUE THREAD

**Issue by duven87** [elkarbackup/elkarbackup#550]
Hello!
I was browsing for backup server alternatives to the one I currently use and found your project. 
Your project looks really good and I would like to test it but I haven't found any section where you talk about encrypting the backups.
Is it not possible to encrypt the backups made natively with elkarbackup?

Thanks

Regards!

**Comment by cyberfarer** [comment]
Hello,

If it helps, I mount an external volume and create an encrypted folder for
data that is confidential. I then use Elkarbackup's scripts feature to
mount/dismount the volume. So far so good. A benefit is that I can automate
mounting the encrypted volume while keeping the storage and key on separate
devices.

Sean.

**Comment by duven87** [comment]
Hi cyberfarer,
thanks for your answer.
I was just thinking about that alternative with Veracrypt for example. 
Yes, it is a solution.
I just wanted to know if you were thinking of implementing it natively in the near future and make sure that the functionality doesn't exist natively because I haven't found anything in the documentation.
Regards

**Comment by parreitu** [comment]
Hi @duven87 

It is not natively supported, the idea is to encrypt the disk that you will later use for backups. More info here https://github.com/elkarbackup/elkarbackup/issues/392
