### ISSUE TITLE
Improve error handling when client name already exists

### ISSUE THREAD

**Issue by uanabitarte** [elkarbackup/elkarbackup#554]
### Describe the bug

When you try to create a new client with a name that already exists, it return a kind of ugly error message.

### Steps to reproduce the behavior

1. Create a client
2. Try to create another client with the same name

### Expected vs actual behavior

The sql error exception should be handled and return a more clear message, such as "Client already exists"

### Logs

> Unable to save your changes: An exception occurred while executing 'INSERT INTO Client (description, isActive, name, url, quota, sshArgs, rsyncShortArgs, rsyncLongArgs, state, maxParallelJobs, data, owner_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, 1, "localhost", "", -1, null, null, null, "NOT READY", 1, null, 1]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'localhost' for key 'Client.UNIQ_C0E801635E237E06'

**Comment by elacunza** [comment]
Is this only for API, o f also/only for web interface?

**Comment by uanabitarte** [comment]
Also for the web interface
