### ISSUE TITLE
SSH parameters getting ignored on restore

### ISSUE THREAD

**Issue by Joshua2504** [elkarbackup/elkarbackup#555]
### Describe the bug

A clear and concise description of what the bug is. Include the following information:

- Elkarbackup version: 2.0.2
- OS: Debian 10
- Deb package version / Docker image name: Deb

### Steps to reproduce the behavior

1. set custom ssh args, e.g. username: -l root
2. create a backup
3. restore backup to client

### Expected vs actual behavior

SSH arguments are getting ignored. E.g. if you set username root and port 2222, it will not use those parameters.

**Comment by xezpeleta** [comment]
Hi @Joshua2504 

Try removing "-l root" and specifying the username in the Host URL (`user@address`). The port (-p2222) should work.

pd: if I'm not wrong, this restore command doesn't understand all the SSH advanced options, only SSH? (maybe @antton can confirm this)

Thanks

**Comment by antton** [comment]
Hello, 

As I remember right now and as @xezpeleta comments you can use -p2222 as there is a function that will extract the port automatically to pass it to the rsync command.  Let us know the result.

Thanks

**Comment by antton** [comment]
Oh,

And yes, we only recognize the port in the sshargs parameter, so it will take the username from hostURL. Use it as indicated by @xezpeleta user@hotname.

**Comment by Joshua2504** [comment]
Ah, thanks, that works.

You should put that in the SSH argument description :)
