### ISSUE TITLE
API tests don't pass

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#564]
I get two errors. 

First one may be related to the DB version, mine is MariaDB  10.3.29 (ubuntu oficial repo), maybe test was developed with Mysql. Maybe a less stric checking of the string will do, like comparing until key name.

Second one isn't very self-explanatory...

 ./run-tests.sh 
Dropped database `elkarbackup_test` for connection named default
Created database `elkarbackup_test` for connection named default
[notice] Migrating up to DoctrineMigrations\Version20210315133526
[notice] finished in 2195.4ms, used 26M memory, 31 migrations executed, 103 sql queries

PHPUnit 8.5.15 by Sebastian Bergmann and contributors.

Testing Elkarbackup API
...F................................F..............               51 / 51 (100%)

Time: 3.09 seconds, Memory: 118.50 MB

There were 2 failures:

1) App\Tests\api\ClientTest::testCreateClientRepeatedName
Failed asserting that an array has the subset Array &0 (
    '@context' => '/api/contexts/Error'
    '@type' => 'hydra:Error'
    'hydra:title' => 'An error occurred'
    'hydra:description' => 'An exception occurred while executing 'INSERT INTO Client (description, isActive, name, url, quota, sshArgs, rsyncShortArgs, rsyncLongArgs, state, maxParallelJobs, data, owner_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, 1, "client_1621262980_6489", "", -1, null, null, null, "NOT READY", 1, null, 1]:\n
\n
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'client_1621262980_6489' for key 'Client.UNIQ_C0E801635E237E06''
).
--- Expected
+++ Actual
@@ @@
   'hydra:title' => 'An error occurred',
   'hydra:description' => 'An exception occurred while executing \'INSERT INTO Client (description, isActive, name, url, quota, sshArgs, rsyncShortArgs, rsyncLongArgs, state, maxParallelJobs, data, owner_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\' with params [null, 1, "client_1621262980_6489", "", -1, null, null, null, "NOT READY", 1, null, 1]:
 
-SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry \'client_1621262980_6489\' for key \'Client.UNIQ_C0E801635E237E06\'',
+SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry \'client_1621262980_6489\' for key \'UNIQ_C0E801635E237E06\'',
   'trace' => 
   array (
     0 =>

/home/elacunza/git/elkarbackup/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Constraint/ArraySubsetTrait.php:68
/home/elacunza/git/elkarbackup/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Constraint/ArraySubsetLegacy.php:32
/home/elacunza/git/elkarbackup/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php:99
/home/elacunza/git/elkarbackup/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php:56
/home/elacunza/git/elkarbackup/tests/api/BaseApiTestCase.php:17
/home/elacunza/git/elkarbackup/tests/api/ClientTest.php:71

2) App\Tests\api\JobTest::testGetJobs
Assert job exists in collection
Failed asserting that false is true.

/home/elacunza/git/elkarbackup/tests/api/JobTest.php:213

**Comment by uanabitarte** [comment]
I have made a PR to correct the second error, #563 
And for the first one, you're right, I think it might be a DB version issue

**Comment by elacunza** [comment]
The second one seems fixed yes.
So only the first is left to fix :) You can try installing mariadb-server instead of mysql-server

**Comment by uanabitarte** [comment]
This would be fixed if the enhancement suggested in #554 is made. What do you think if I try to fix that in order to have a more clear message and independent of the DB version?

**Comment by igorbga** [comment]
+1 , great idea

**Comment by elacunza** [comment]
Ok, do so please

**Comment by elacunza** [comment]
Now works like a charm, good job @uanabitarte !
