### ISSUE TITLE
run-tests.sh sudo command not found

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#568]
### Describe the feature or problem you’d like to solve

`run-tests.sh` fails in Docker due to lack of sudo command

### Proposed solution

Run with sudo, only if sudo exists

**Comment by elacunza** [comment]
Seems we should check user ID, and use sudo only if not 0

**Comment by xezpeleta** [comment]
Closing this issue. Finally we'll probably solve it running test in prod image
