### ISSUE TITLE
Docker container ends immediately when EB_CRON is not enabled

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#576]
### Describe the bug

A clear and concise description of what the bug is. Include the following information:

- Docker image name: elkarbackup/elkarbackup:2.1.0

### Steps to reproduce the behavior

1. Modify default docker-compose.yml, setting EB_CRON=disable
2. docker-compose up
3. The elkarbackup container exits immediately

### Expected vs actual behavior

Elkarbackup should keep alive.
The only different should be Tick commands not executing every minute.

**Comment by xezpeleta** [comment]
By the way, by default EB_CRON is disabled, as having two processes (apache and cron) running on the same container is not following the Docker best practices. If we want to follow them, we can run another container every minute to run the tick command...

I guess most users don't matter this and we will want to enable EB_CRON. So should we change the default value to enable?

**Comment by elacunza** [comment]
Yes, default should be enabled.
