### ISSUE TITLE
Remote job trigger should not require https

### ISSUE THREAD

**Issue by jvies** [elkarbackup/elkarbackup#578]
When elkarbackup is running in a Docker container, it is very common to only expose a http connectivity.

In this case, the job trigger presented here https://github.com/elkarbackup/elkarbackup/wiki/FAQ#remotely-job-execution is not available.
It would be better if this https requirement could be deactivated, and so deactivated in the docker configuration.

**Comment by xezpeleta** [comment]
It my opinion it makes sense. My only concern is about not making the web UI too complex with so many options.

What do you think @elacunza ? Any ideas?

**Comment by elacunza** [comment]
Yes, I agree we can remove HTTPS requirement in DefaultController.php:615 (in enqueueJobAction)

**Comment by jvies** [comment]
here is a PR to implement the proposed solution:
https://github.com/elkarbackup/elkarbackup/pull/583
