### ISSUE TITLE
additional advanced field for a client

### ISSUE THREAD

**Issue by jvies** [elkarbackup/elkarbackup#579]
hi,

I'd like to use the same pre-script for several clients. This script would send a wakeonlan magic packet, so it needs the MAC address of the client.
It would be easier if some "MAC address" field is defined per client, and available in a env variable for the scripts.

Maybe another option, would be to have a generic key/value mechanism to populate the env variables.

**Comment by xezpeleta** [comment]
Hi,

If I'm not wrong, this enhancement has been already proposed #196 

Thanks

**Comment by jvies** [comment]
yes you're right. I'd have checked better before :neutral_face: 

I close this request.
