### ISSUE TITLE
elkarbackup docker container constantly restarts with no errors as to why

### ISSUE THREAD

**Issue by UntouchedWagons** [elkarbackup/elkarbackup#580]
### Describe the bug

A clear and concise description of what the bug is. Include the following information:

- Elkarbackup version: 2.1.0
- OS: Ubuntu 20.04 Focal
- Deb package version / Docker image name: elkarbackup/elkarbackup:2.1.0

### Steps to reproduce the behavior

1. Create docker-compose.yaml file
2. docker-compose up
3. I don't know what to put here

### Expected vs actual behavior

I expect it to not constantly restart with no obvious error message?

### Logs

    elkarbackup    | Database `elkarbackup` for connection named default already exists. Skipped.
    elkarbackup    |
    elkarbackup    |  [OK] Already at the latest version ("DoctrineMigrations\Version20210315133526")
    elkarbackup    |
    elkarbackup    | Admin user exists and reset was not requested. Nothing to do.
    elkarbackup    |
    elkarbackup    |  // Clearing the cache for the prod environment with debug
    elkarbackup    |  // false
    elkarbackup    |
    elkarbackup    |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
    elkarbackup    |
    elkarbackup    |
    elkarbackup    |  Installing assets as hard copies.
    elkarbackup    |
    elkarbackup    |  --- ------------------- ----------------
    elkarbackup    |       Bundle              Method / Error
    elkarbackup    |  --- ------------------- ----------------
    elkarbackup    |   ✔   ApiPlatformBundle   copy
    elkarbackup    |  --- ------------------- ----------------
    elkarbackup    |
    elkarbackup    |  ! [NOTE] Some assets were installed via copy. If you make changes to these
    elkarbackup    |  !        assets you have to run this command again.
    elkarbackup    |
    elkarbackup    |  [OK] All assets were successfully installed.
    elkarbackup    |
    elkarbackup    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
    elkarbackup    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
    elkarbackup    | [Mon May 31 00:16:32.470612 2021] [mpm_prefork:notice] [pid 54] AH00163: Apache/2.4.38 (Debian) PHP/7.3.28 configured -- resuming normal operations
    elkarbackup    | [Mon May 31 00:16:32.470721 2021] [core:notice] [pid 54] AH00094: Command line: 'apache2 -D FOREGROUND'

The container just constantly restarts printing the exact same messages to the console every single time.

My docker-compose.yaml:

    version: '3'

    services:
      mariadb:
        image: ghcr.io/linuxserver/mariadb
        container_name: mariadb
        environment:
          - PUID=1000
          - PGID=1000
          - MYSQL_ROOT_PASSWORD=ScandalBarbedLettuce
          - TZ=America/Toronto
          - MYSQL_DATABASE=elkarbackup
          - MYSQL_USER=elkarbackup
          - MYSQL_PASSWORD=EffectiveSideAttraction
        volumes:
          - mariadb_data:/config
        restart: unless-stopped

      elkarbackup:
        image: elkarbackup/elkarbackup:2.1.0
        container_name: elkarbackup
        restart: unless-stopped
    #    user: "1000:1000" # Seriously, either this
        ports:
          - 4834:80
        links:
          - mariadb
        depends_on:
          - mariadb
        volumes:
          - elkarbackup_sshkeys:/app/.ssh
          - /mnt/data/Backups:/mnt/data/Backups
        environment:
    #      - PUID=1000 # or this should work, running
    #      - PGID=1000 # containers as root is a bad idea
          - SYMFONY__DATABASE__HOST=mariadb
          - SYMFONY__DATABASE__NAME=elkarbackup
          - SYMFONY__DATABASE__USER=elkarbackup
          - SYMFONY__DATABASE__PASSWORD=EffectiveSideAttraction
          - SYMFONY__EB__BACKUP__DIR=/mnt/data/Backups

    volumes:
      mariadb_data:
      elkarbackup_sshkeys:

**Comment by xezpeleta** [comment]
Hi!

You could be hitting bug #576 

Can you try adding the EB_CRON="enabled" environment variable?

Thanks

**Comment by UntouchedWagons** [comment]
I added that environment variable and elkarbackup still exits with no error message. In the console log for mariadb I did see this:

    mariadb        | 2021-05-31 14:49:27 10 [Warning] Access denied for user 'root'@'elkarbackup.elkarbackup_default' (using password: NO)

I don't know why elkarbackup is trying to use the root user, that's bad security

**Comment by xezpeleta** [comment]
I think this log is from mysqladmin ping. It's used just to check that database is up.

```sh
# Filename: entrypoint.sh

...
# Check database connection
until mysqladmin ping -h "${SYMFONY__DATABASE__HOST}" --silent; do
  >&2 echo "MySQL is unavailable - sleeping"
  sleep 1
done
...

```

Once the database is up, the entrypoint will use the credentials from environment variables to connect to the database.

I suggest you to start with the default docker-compose.yml file from [Docker Hub Elkarbackup overview page](https://hub.docker.com/r/elkarbackup/elkarbackup/) and then changing it progressively to try to find the source of the problem.

Thanks

**Comment by UntouchedWagons** [comment]
After fixing up the example a bit:

    version: '3'

    services:
      elkarbackup:
        image: elkarbackup/elkarbackup:latest
        container_name: elkarbackup
        restart: unless-stopped
        environment:
          - SYMFONY__DATABASE__PASSWORD=ScandalBarbedLettuce
          - EB_CRON=enabled
        volumes:
          - backups:/app/backups
          - uploads:/app/uploads
          - sshkeys:/app/.ssh
        ports:
          - 8000:80

      db:
        image: mysql:5.7.22
        restart: unless-stopped
        container_name: mysql
        environment:
          - MYSQL_ROOT_PASSWORD=ScandalBarbedLettuce
        volumes:
          - db:/var/lib/mysql

    volumes:
      db:
      backups:
      uploads:
      sshkeys:

I got it to start. I'll experiment a bit.
