### ISSUE TITLE
"Not Found" when I click on logs /client/1

### ISSUE THREAD

**Issue by dml33** [elkarbackup/elkarbackup#592]
Hi.

- Elkarbackup version: 2.1.0, but this also happened to me in 1.3.5.
- OS: Debian Buster 10.8

In logs section, when I click on "/client/1" or "/client/1/job/4", 

![image](https://user-images.githubusercontent.com/25033130/127776538-a613e608-22ff-4635-8e2c-1b03b84b93b7.png)

a page is open with the following text:

![image](https://user-images.githubusercontent.com/25033130/127776552-c7b629ec-57e9-4fd7-9cca-be8db13c8660.png)

I do not know exactly what should be opened, but I think it is the indicated job webpage.

However, if I click on the "/elkarbackup/user/1", it works perfectly, and the user 1 information web page is opened.

Thanks.

**Comment by xezpeleta** [comment]
Related to https://github.com/elkarbackup/elkarbackup/issues/593#issuecomment-912485280

**Comment by xezpeleta** [comment]
Fixed adding the URL prefix "/elkarbackup" in Preferences
