### ISSUE TITLE
Missing icon/image in main page

### ISSUE THREAD

**Issue by dml33** [elkarbackup/elkarbackup#593]
Hi.

- Elkarbackup version: 2.1.0, but this also happened to me in 1.3.5.
- OS: Debian Buster 10.8

I see a broken icon/image in the main page, at the upper left corner. The link goes to /elkarbackup/clients

![image](https://user-images.githubusercontent.com/25033130/127776694-7a96dde5-ffd2-4874-98e9-3354171ac00a.png)

Also, as you can see, there is another missing icon on the right, where "disc" is displayed.

Thanks.

**Comment by xezpeleta** [comment]
Hi @dml33 

Can you check that the "Url prefix" value ("Manage parameters") is correctly configured?

> **Url prefix**
> Depending on the Apache configuration the URL generated by the backups jobs that show up in the logs might be wrong. For example, if http://your.host/client/1 is generated where you would expect http://your.host/elkarbackup/client/1 set this parameter to /elkarbackup.

**Comment by dml33** [comment]
Hi.

I have just added `elkarbackup` in the _Url prefix_ section, but an error ocurrs when I press `Save`.

![image](https://user-images.githubusercontent.com/25033130/132128978-98c04dba-c4e5-41c3-9a5f-7c4fa824f096.png)

Anyway, it seems to be updated when I run

`/usr/share/elkarbackup/bin/console cache:clear --env=prod`

as suggested in FAQ. I even restarted. Then:

![image](https://user-images.githubusercontent.com/25033130/132135787-c23dceab-da82-4ff2-93f0-a923b1987e92.png)

But, still the prefix seems not to be working, since the address for those icons remain as:

http://192.168.8.105/img/elkarbackup.png
http://192.168.8.105/img/disc-status.png

However, the issues related with https://github.com/elkarbackup/elkarbackup/issues/592 have been solved:

![image](https://user-images.githubusercontent.com/25033130/132135985-10bfb478-dea7-4c61-8acb-42cfeff8c00a.png)

Almost fixed!

**Comment by xezpeleta** [comment]
Thanks @dml33 , you're right. Apparently there are some incorrect image URLs.
