### ISSUE TITLE
Formulario para automatizar la copia de la clave pública en el destino

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#6]
En estos momentos tenemos que descargar la clave pública y configurarla en el fichero authorized_keys del cliente de forma manual (a través de un ssh-copy-id)

La propuesta es habilitar en el formulario de clientes una sección opcional para automatizar este proceso, y evitar la necesidad de recurrir a la consola. Bastaría con pedir el usuario y contraseña en ese mismo formulario, y luego lanzar por debajo el comando.

**Comment by antton** [comment]
Hi everyone!

I already did, after analyze different libs. Here you are!

https://youtu.be/z1olSE8Pai4

**Comment by xezpeleta** [comment]
Great!

**Comment by parreitu** [comment]
Fabulous!!

- - - - - - - - - - - - - - - - - - - - - - - - - - - -
Zuk nahi badezu, hemendik aurrera euskaraz egingo degu.

Pedro Arreitunandia

**Comment by elacunza** [comment]
Really nice, I think button shouldn't appear when creating a new client; 
only when it's saved? ;)

El 13/12/15 a las 16:41, Pedro Arreitunandia escribió:
> Fabulous!!
>
> - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Zuk nahi badezu, hemendik aurrera euskaraz egingo degu.
>
> Pedro Arreitunandia
> El 12/12/2015 14:09, "Antton Rodriguez" <notifications@github.com> 
> escribió:
>
> > Hi everyone!
> >
> > I already did, after analyze different libs. Here you are!
> >
> > https://youtu.be/z1olSE8Pai4
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/elkarbackup/elkarbackup/issues/6#issuecomment-164148642>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/6#issuecomment-164269217>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
@elacunza agree, I'll remove it until the client is already saved. 
But if I do this I think we should remove also the "add job" button, for now both are disabled if the client is not already saved.

**Comment by elacunza** [comment]
If they're disabled it's ok for me... I thought it was active... :)

El 14/12/15 a las 13:25, Antton Rodriguez escribió:
>
> @elacunza <https://github.com/elacunza> agree, I'll remove it until 
> the client is already saved.
> But if I do this I think we should remove also the "add job" button, 
> for now both are disabled if the client is not already saved.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/6#issuecomment-164424571>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by xezpeleta** [comment]
I don't agree! :D

Disabling the button, instead of hiding it, you can indicate to the user
why the action is not available at the moment. If I'm not wrong, currently
the "Add job" button works like that; when it's disabled it shows a message
like "you must save the client first".

On the other hand, hiding the button can be confusing. Sometimes you see a
button, sometimes no... specially for the new users it can be harder to
learn the software features and behavior.

Anyway, I'm not a web usability expert, so if the people thinks it's better
to hide the buttons, we'll do that! :P


2015-12-14 13:25 GMT+01:00 Antton Rodriguez <notifications@github.com>:

**Comment by elacunza** [comment]
I think we do agree, it was a mistake on my part in the first mail. :)

El 14/12/15 a las 13:49, Xabi escribió:
> I don't agree! :D
>
> Disabling the button, instead of hiding it, you can indicate to the user
> why the action is not available at the moment. If I'm not wrong, currently
> the "Add job" button works like that; when it's disabled it shows a 
> message
> like "you must save the client first".
>
> On the other hand, hiding the button can be confusing. Sometimes you see a
> button, sometimes no... specially for the new users it can be harder to
> learn the software features and behavior.
>
> Anyway, I'm not a web usability expert, so if the people thinks it's 
> better
> to hide the buttons, we'll do that! :P
>
>
> 2015-12-14 13:25 GMT+01:00 Antton Rodriguez <notifications@github.com>:
>
> > @elacunza <https://github.com/elacunza> agree, I'll remove it until the
> > client is already saved.
> > But if I do this I think we should remove also the "add job" button, for
> > now both are disabled if the client is not already saved.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/elkarbackup/elkarbackup/issues/6#issuecomment-164424571>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/6#issuecomment-164428500>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by xezpeleta** [comment]
:+1:

**Comment by xezpeleta** [comment]
This feature has been added with the PR #127 

Anyway, maybe we should warn that the most popular Linux distributions don't allow to the 'root' user to log in with the password by SSH (ssh key is required). So that would be only useful for non root users.

We can solve this problem using a custom (sudo enabled) user to copy the ssh id.

**Comment by xezpeleta** [comment]
Esta funcionalidad ha quedado descartada definitivamente. Las políticas de seguridad de las nuevas distribuciones no permiten el login de root por SSH sin la llave y esto complica la solución.

Por contra, se ha decidido apostar otra alternativa: un paquete o script para el cliente, que ayude a instalar las dependencias necesarias y descargarse la llave ssh del servidor de elkarbackup.
