### ISSUE TITLE
replace rsnaphost with restic backup

### ISSUE THREAD

**Issue by m2acgi** [elkarbackup/elkarbackup#640]
rsnaphost is obsolete, restic backup is a good alternatives.

**Comment by JoshuaPettus** [comment]
Out of curiosity, and I'm just the peanut gallery, but in what way is it better than rsnapshot?

**Comment by m2acgi** [comment]
- compression
- de-duplicate
- secure (encryption)
- compatible with almost all OS

**Comment by JoshuaPettus** [comment]
I think you would have better luck starting contributing to another project or starting your own around restic.  Elkar is practically a front-end for rsnapshot, and to switch to restic with restic's feature set would probably be tantamount to starting from scratch.  There doesn't look like there is anyone available atm to just do the maintenance this project deserves as it is (PHP8.1 support for instance).

**Comment by elacunza** [comment]
@JoshuaPettus is right, we don't have time for this project ATM :( . I'm sure restic backup is very cool, but that would be a completely different project.
