### ISSUE TITLE
Mejoras en edición de cuotas

### ISSUE THREAD

**Issue by alfredobz** [elkarbackup/elkarbackup#67]
1- Tanto si escribimos directamente como si lo hacemos con las flechas del interface, se permiten números negativos distintos de -1. No debería ser así.

2- Poner las cuotas en KB en los tiempos que corren, no parece adecuado. Debería de soportar las unidades de cuota. Ej: 300MB, 150GB, etc. Si esto no es posible, sería adecuado como medida intermedia, poner el número en GBs o MBs.

**Comment by antton** [comment]
Solución punto 1
nano Form/Type/ClientType.php (linea 25)
eta hau aldatu
                ->add('quota'         , 'integer'   , array('label' => $t->trans('Quota', array(), 'BinovoElkarBackup'),
                                                            'attr'  => array('class'    => 'form-control','min' => '-1')))

**Comment by antton** [comment]
Si lo ponemos así podemos ir incrementando de 1024Kb  en 1024Kb
'attr'  => array('class'    => 'form-control','min' => '-1','step' => '1024')))

Ale geroarte!
