### ISSUE TITLE
Script selection and deselection

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#68]
We should change the way we select/deselect scripts (Client/Job edition). It's not obvious to know if a script is enabled, and how to deselect it (Ctrl + click)

![multiple-select-box](https://cloud.githubusercontent.com/assets/1846038/5301815/117fc502-7bdc-11e4-8ab0-91111f6f32bf.png)

**Comment by antton** [comment]
We should try this way.
http://dojotoolkit.org/reference-guide/1.10/dojox/form/CheckedMultiSelect.html

**Comment by xezpeleta** [comment]
Primeran! :D

**Comment by parreitu** [comment]
uauuuu  !!!!

Oso itxura polita !!

2015-01-27 16:05 GMT+01:00 Antton Rodriguez <notifications@github.com>:

**Comment by antton** [comment]
Aurre-produkzioa egina dago beraz laster izango duzue bertsio berrian!
