### ISSUE TITLE
Nombres de ficheros con espacios en excluir

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#70]
Hola,

Antes de la 1.1.x (?) tenía excluidos unos directorios con nombres en los espacios así:
Un\ directorio\ con\ espacios
Con la versión 1.1.2 esto da un error con rsync. He probado a simplemente poner espacios, pero no funciona. Al final lo he solucionado poniendo:
'Un directorio con espacios'

**Comment by xezpeleta** [comment]
Tras los cambios realizados, esta es la situación:

- Al crear un cliente local (Url vacio) NO funcionan los directorios con espacios. Parece que es un problema reconocido de RSnapshot.
- En directorios remotos (cliente SSH), los directorios con espacios funcionan correctamente si escapamos los espacios con la contrabarra (\): /tmp/directorio\ con\ espacios

Se hará efectivo en la versión 1.1.3

**Comment by xezpeleta** [comment]
@elacunza  Atención con la actualización a la versión Elkarbackup 1.1.3, ya que de nuevo hay que indicar los espacios con la contrabarra, tal como lo hacías antes
