### ISSUE TITLE
Versión para Ubuntu anticuada

### ISSUE THREAD

**Issue by alfredobz** [elkarbackup/elkarbackup#71]
La versión del repositorio de Ubuntu es la 1.0.23.

**Comment by xezpeleta** [comment]
Ya está actualizado el paquete de Ubuntu Trusty:

http://elkarbackup.org/apt/ubuntu/pool/main/e/elkarbackup/

De todas formas, al tener un único paquete DEB universal, tal vez tendríamos que publicar una única dirección universal...

**Comment by alfredobz** [comment]
Estoy de acuerdo.
El paquete Weezy hasta ahora funciona bien en todo lo que he probado.
Lo que no he probado es el tema del los directorios de configuración de Apache,
