### ISSUE TITLE
Ideas para futuras versiones

### ISSUE THREAD

**Issue by alfredobz** [elkarbackup/elkarbackup#75]
Aupa

1- Propuestas para versiones siguientes:
En las versiones siguientes: 1.1.3, 1.1.4, ... etc
Propongo que se mantenga la versión de la BB de DD y se intente reducir al máximo el número de bugs existentes en el programa.

Hay bugs que hemos de corregir. No hay excusa.

2- Para la versión 2.0.0 del programa, se hace necesario que se modifique el esquema de la base de datos. Esta modificación ha de ser consensuada entre los desarrolladores, para poder adecuar convenientemente, las necesiadaes futuras que se vean en al desarrollo de este software.

Propuesta de modificaciones:

1- Hay cosas en el menú de configuración y en el menú principal que corrsponden a preferencias del usuario.
Propongo hace una nueva entrada en el menú proncipal: "Preferences" que contenga el idioma preferido del usuario, el número de líneas en los logs, el cambio del password y el estado del interface de usuario (p.e.: si prefiere la ayuda en pantalla o la frefiere oculta por defecto).

2- Pasar la opción de configuración "Manage Backups Location" a "Manage Parameters"

3- Pasar "Repository Backup Script" a "Scripts".

4- Crear una entrada en el menú principal para "Clients"
En este menú listar los clientes. En este menú poner "Delete" + "Add". Conceptualmente, es una burrada añadir y borrar clientes en el panel de tareas.

5- Quitar las entradas de submenús "Add". Modificar el nombre del menú "Session" por "Quit" / "Logout". Reordenar los submenús de izquierda a derecha con el orden de utilizazión.
1-- Config
2-- Policies
3-- Clients
4-- Jobs
5-- Scripts
6-- Logs
7--Users
8--Quit

6- Con estos cambios quedaría solamente el submenú "Show" en el menú principal. Borrar los submenús diciendo a Digit que cree menús de solo botón (o mejor crear menús estáticos que es más rápido).

Cambios importantes:

7- Poder seleccionar en cada cliente dónde realizar las copias de seguridad. Actualmente solamente existe una única rama de donde cuelgan todas las copias de seguridad. Hacer que cada cliente pueda escoger una diferente. Si no se pone, por defecto cogería la rama principal o de "sistema". Un usuario puede desear poner los backup de clientes importantes en RAID1 y las de clientes menos importantes en un disco USB, al igual que las copias importantes se mantienen más tiempo y las menos importantes menos tiempo.

8- Dar un contenido al menú "User". Propongo que el administrador asigne a un Usuario clientes. De este modo un usuario podría crear jobs en los clientes y restaurar sus dartos y ver los logs. Solamente el administrador podría crear usuarios.

9- Hacer el programa compatible con SQLite. De tal forma que el administrador seleccione en la instalación (y después?) el tipo de BBDD que desea utilizar.

10- Definir a cuales backups hacerles copia de respaldo en un servidor remoto. A lo mejor hay clientes / jobs a los cuales no merezca la pena hacer una copia remota.

11- Dejar en /etc/elkarbackup/parameters.yml solamente los siete parámetros de la BBDD. El resto pasarlos a una tbla "Config" de la BBDD:

**Comment by antton** [comment]
Kaixo Alfredo,

Analizando lo que comentas, he mirado punto por punto lo que se puede hacer y lo que estamos haciendo.

1.- Menú nuevo de Preferencias: Sobre todos los temas que comentas solo se esta trabajando el que la ayuda aparezca y desaparezca con un click en un botón, ya tengo el javascript escrito y solo falta incluirlo donde haga falta (no hemos decidido si queremos que la ayuda salga desplegada o no, pero yo soy partidario de que aparezca oculta por defecto)

2.- Veo que no hace falta tocar la BBDD tal vez si un par de funciones pero estos parametros al guardarse en un .yml no parece tan complicado.

3.- Lo he cambiado hace un momento en preproducción y yo también estoy de acuerdo en reorganizar los menús, pero también estamos barajando en como hacer para que todos los submenus desaparezcan y tengamos acceso directo donde haga falta dando funcionalidad de click al menú principal (ahora hace falta hacer click en el principal para que salga el submenu y una vez sale poder acceder donde se quiere)

4.- Si te refieres a la parte inferior dentro de clientes donde se muestran 4 campos de tareas, estamos dándole una vuelta para quitar eso de ahí y ponerlo donde realmente hace falta (en caso de que haga falta) Solo vemos que sirve para cambiar masivamente politicas, nombres o activar desactivar. Se puede crear una nueva entrada para todo esto o darle una vuelta a como gestionar esta parte.

5.- Lo dicho antes, que nuestra intención es el reorganizar todos los menús y antes de hacer nada si queréis añadiremos pantallazos de nuestra idea.

6.- Estamos deacuerdo.

* 7.- Seria una funcionalidad muy interesante y sí se tiene que cambiar la estructura de la BBDD*
* 8.- ¿Ese usuario solo vería esa pantalla de acciones que propones? *
* 9.- ¿Para que queremos compatibilidad con SQLlite? En su momento se comentaba el que funcionase en una raspberry pi podría ser interesante pero MySQL es muy pesado para ello. La salida al mercado de la Rpi 2 creo que solventa este problema. (De todos modos no parece tan complicado el dar soporte de SQLlite) *
* 10.- Seria una funcionalidad muy interesante y sí se tiene que cambiar la estructura de la BBDD*
* 11.- Si se efectúan los cambios 7 y 10, si que tenemos que analizar que se dejaría en el parameters.yml

Queda claro que tenemos mucho por hacer!

Hablamos.

**Comment by xezpeleta** [comment]
Se ha intentado resumir esto en el [Roadmap](https://github.com/elkarbackup/elkarbackup/wiki/Roadmap).

En la wiki también hay una lista de [Ideas](https://github.com/elkarbackup/elkarbackup/wiki/Ideas) para conceptos menos concretos o más complicados de materializar.

De momento cierro la incidencia.
