### ISSUE TITLE
Improve the look of the action buttons (Show clients window)

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#76]
![showclients-botones-acciones](https://cloud.githubusercontent.com/assets/1846038/6409552/930f0170-be65-11e4-956d-46f82d09e04b.png)

Any advice?

**Comment by elacunza** [comment]
Maybe keeping a column for each action could improve the look, ie move 
"+Add a job" buttons to their own column.

On 27/02/15 09:47, Xabi wrote:
>
> showclients-botones-acciones 
> <https://cloud.githubusercontent.com/assets/1846038/6409552/930f0170-be65-11e4-956d-46f82d09e04b.png>
>
> Any advice?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/76>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
Do you mean pulling to the right the last button or instead just separate the buttons on a differents <td> ?

**Comment by elacunza** [comment]
Moving to the right, so that:

| remove | restore | run job now |

| remove | restore | run job now |

| remove | + add new job |


becomes:

| remove | restore | run job now |

| remove | restore | run job now |

| remove |         |             |+ add new job |


Another option could be to put a checkbox in each row, and move 
"remove", "run now" actions to the top/bottom of the list, so that they 
can be done for multiple jobs and as bonus free space in the current 
action zone in each row; but this would be more than a look change. :)


On 27/02/15 10:00, Antton Rodriguez wrote:
>
> Do you mean pulling to the right the last button or instead just 
> separate the buttons on a differents
>
> ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/76#issuecomment-76358852>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
I see you last solution quite complicate to start developing now,I think that we need to start just thinking in a good UI and then improve it with more code in case. ;)

something like that?

![captura de pantalla 2015-02-27 a la s 13 02 56](https://cloud.githubusercontent.com/assets/1666548/6412206/29494806-be81-11e4-855c-53029c97d206.png)

**Comment by elacunza** [comment]
I don't like there to be some actions with icon+text and some other only 
with icons.

On 27/02/15 13:04, Antton Rodriguez wrote:
>
> I see you last solution quite complicate to start developing now,I 
> think that we need to start just thinking in a good UI and then 
> improve it with more code in case. ;)
>
> something like that?
>
> captura de pantalla 2015-02-27 a la s 13 02 56 
> <https://cloud.githubusercontent.com/assets/1666548/6412206/29494806-be81-11e4-855c-53029c97d206.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/76#issuecomment-76384841>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
Me neither, It was just to show you the idea, I'd like to transform everything to just icon modality, and using the tooltips for the rest of the text part.

**Comment by xezpeleta** [comment]
I like the idea of using only icons (with tooltips) :)

**Comment by elacunza** [comment]
I hate it :)

On 27/02/15 13:35, Xabi wrote:
>
> I like the idea of using only icons (with tooltips) :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/76#issuecomment-76388116>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by antton** [comment]
Easy to say and hard to listen! I'm gonna try to give you an other idea on which everybody would be happy. Let me know!

![captura de pantalla 2015-03-02 a la s 09 27 11](https://cloud.githubusercontent.com/assets/1666548/6437369/6c9133e6-c0be-11e4-8426-bac7af3e0ca8.png)

**Comment by antton** [comment]
Or...
![captura de pantalla 2015-03-02 a la s 09 30 16](https://cloud.githubusercontent.com/assets/1666548/6437412/c8bbe8c8-c0be-11e4-99fe-7d4cf6837071.png)

**Comment by elacunza** [comment]
I suspect that if there is not enough horizontal space the buttons will 
appear "mixed"?

I don't like to have buttons with different backgrounds; all buttons 
should have the very same form/colors.

On 02/03/15 09:30, Antton Rodriguez wrote:
>
> Or...
> captura de pantalla 2015-03-02 a la s 09 30 16 
> <https://cloud.githubusercontent.com/assets/1666548/6437412/c8bbe8c8-c0be-11e4-99fe-7d4cf6837071.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/76#issuecomment-76674208>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by xezpeleta** [comment]
My idea was to do it more minimalist, maybe too minimalist... :-)

![captura de pantalla 2015-03-11 a las 20 56 52](https://cloud.githubusercontent.com/assets/1846038/6605787/e3e9fe48-c832-11e4-8c29-9eb2f583a72d.png)

Actually our current main window is not so ugly (in the english version). We can also keep the current look but do it more calm and "zen" :palm_tree: 

![captura de pantalla 2015-03-11 a las 20 28 27](https://cloud.githubusercontent.com/assets/1846038/6605905/e7303f44-c833-11e4-987f-842daec0d325.png)

What do you think?

The problem is that in spanish/basque version buttons have different sizes... Moving the "Add job" button to the right doesn't convince me. I see it a little bit confusing. I'll try to think another option...

**Comment by elacunza** [comment]
So, is it really useful to have all those buttons on the list?

For example, I don't think removing a host or a task is such a frequent 
action. Maybe it belongs to each host/task window. The same for restore?

Another option is to use a drop-down button for all the actions on each 
row, that would be very compact even with labels.

On 11/03/15 21:33, Xabi wrote:
>
> My idea was to do it more minimalist, maybe too minimalist... :-)
>
> captura de pantalla 2015-03-11 a las 20 56 52 
> <https://cloud.githubusercontent.com/assets/1846038/6605787/e3e9fe48-c832-11e4-8c29-9eb2f583a72d.png>
>
> Actually our current main window is not so ugly (in the english 
> version). We can also keep the current look but do it more calm and 
> "zen" :palm_tree:
>
> captura de pantalla 2015-03-11 a las 20 28 27 
> <https://cloud.githubusercontent.com/assets/1846038/6605905/e7303f44-c833-11e4-987f-842daec0d325.png>
>
> What do you think?
>
> The problem is that in spanish/basque version buttons have different 
> sizes... Moving the "Add job" button to the right doesn't convince me. 
> I see it a little bit confusing. I'll try to think another option...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/76#issuecomment-78364885>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by xezpeleta** [comment]
Well, finally we took some ideas from this issue and we are working on a mixed solution. You'll see that not only the action buttons have changed ;-)

![captura de pantalla 2016-01-19 a las 16 59 16](https://cloud.githubusercontent.com/assets/1846038/12423929/0eb7c03c-bece-11e5-82ee-16ed4f7b0e60.png)
