### ISSUE TITLE
The parameter "mailer_host" must be defined

### ISSUE THREAD

**Issue by witzkito** [elkarbackup/elkarbackup#78]
Saludos!!
Actualice a la ultima versión el elkar en mi servidor, a través del apt. Luego de esto obtenía un error cuando quería ingresar a Configuración-> Gestionar Parametros. "500 Internal Server Error", los logs no me marcaban nada, así que pase el archivo app.php a modo dev y me arroja lo siguiente

The parameter "mailer_host" must be defined. 

at appDevDebugProjectContainer ->getParameter ('mailer_host')
in /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle/Controller/DefaultController.php at line 1139

**Comment by xezpeleta** [comment]
¿Puedes mostrarnos el contenido del fichero `/etc/elkarbackup/parameters.yml`?

**Comment by witzkito** [comment]
Ni va ser falta, al ver el contenido de parameters.yml para mostrártelo me doy cuenta que esta faltando justamente ese parámetro. Tras agregarlo quedo funcionando correctamente.

Muchas Gracias!!

**Comment by xezpeleta** [comment]
Ok, cierro la incidencia
