### ISSUE TITLE
New login backgrounds very heavy on bandwidth for remote servers

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#79]
The new 1.1.x login backgrounds are very attractive but they're a pain when trying to login on a remote bandwitdh-constrained elkarbackup server.

I think it could be useful to be able to disable those background images with a configuration parameter.

**Comment by xezpeleta** [comment]
Done. Added new "disable_background" parameter (False by default). It will be available in the next version (v1.1.4).

**Comment by elacunza** [comment]
Thanks a lot Xabi!

On 24/03/15 00:04, Xabi wrote:
>
> Done. Added new "disable_background" parameter (False by default). It 
> will be available in the next version (v1.1.4).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/79#issuecomment-85240997>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es
