### ISSUE TITLE
Mail sent by elkarbackup has root@localhost in From: header

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#81]
I think this should be configurable, or maybe better, it should use the domain name defined in /etc/mailname

**Comment by xezpeleta** [comment]
What mail transport are you using? (`Config -> Parameters`)

Did you change *root* user's email addres? (`Users -> root`)

**Comment by elacunza** [comment]
On 01/04/15 22:24, Xabi wrote:
>
> What mail transport are you using? (|Config -> Parameters|)
>
smtp, localhost (default values) . Local root user has an alias so that 
the email is forwarded to a good email box.
>
> Did you change /root/ user's email addres? (|Users -> root|)
>
No, but I thought this was the recipient email, not the sender?

Thanks a lot Xabi

Cheers
Eneko

-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by elacunza** [comment]
Changing the user email does work. I'm not sure that this is a correct behaviour though...it is a bit strange that the system uses the same email for From and To...

**Comment by xezpeleta** [comment]
I agree, using the recipient email as a sender it's a strange behavior.

We should add a new field for the sender. By the moment, it could be a parameter (in parameters.yml), and in some future update we can move all these preference values from parameters.yml to the DB.

**Comment by elacunza** [comment]
Seems a good plan :)

On 13/04/15 14:48, Xabi wrote:
>
> I agree, using the recipient email as a sender it's a strange behavior.
>
> We should add a new field for the sender. By the moment, it could be a 
> parameter (in parameters.yml), and in some future update we can move 
> all these preference values from parameters.yml to the DB.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/81#issuecomment-92340765>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es
