### ISSUE TITLE
Rsnapshot bug in Debian Jessie

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#88]
I've just discovered there is an important bug in Rsnapshot in Debian Jessie that may result in a non-working backup.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717451

If you really want to use Debian Jessie, you should downgrade Rsnapshot to 1.3.1-3

http://snapshot.debian.org/package/rsnapshot/1.3.1-3/#rsnapshot_1.3.1-3

Another possibility is to modify the file /usr/bin/rsnapshot (line 3459), removing the quotation marks
https://github.com/ramLlama/rsnapshot/commit/b7886d7933bc78094847026577586a3209799ece

If you are unsure, I suggest not updating to Jessie by the moment. We will try to find a workaround to avoid this bug.

**Comment by xezpeleta** [comment]
We can't fix the bug, but it may be interesting to show an alert if we detect that the buggy Rsnapshot version is installed (not patched).

What do you think?
![captura de pantalla 2015-04-26 a las 21 09 29](https://cloud.githubusercontent.com/assets/1846038/7338865/ead66282-ec59-11e4-90f1-7ff82ba84800.png)

**Comment by antton** [comment]
Good idea!

**Comment by parreitu** [comment]
I agree with you !   +1


2015-04-26 22:24 GMT+02:00 Antton Rodriguez <notifications@github.com>:

**Comment by xezpeleta** [comment]
Another option to avoid this problem is to add a newer Rsnapshot deb package from Debian Sid (1.3.1-**6**) in our Elkarbackup deb repository (only under Jessie).

http://ftp.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.3.1-6_all.deb

TODO:
- [ ] Install Rsnapshot 1.3.1-**6** deb package manually in Jessie
- [ ] Check if everything works well with Elkarbackup and SSH connections
- [ ] Add deb package in our repository
- [ ] Update && Upgrade my current Jessie (currently with Rsnapshot 1.3.1-**4**)
- [ ] Test a clean Elkarbackup installation over a Jessie

It wont work for people who installed Elkarbackup downloading manually the deb package, but it would work for most of the people.

**Comment by xezpeleta** [comment]
I confirm that the maintainer didn't fix the bug in Debian Sid package (Rsnapshot 1.3.1-6). The thing is that the patch exists in the source pkg, but he didn't apply it :S

If we want to fix this issue using a newer version instead of downgrading, we should use Ubuntu stable package: 1.3.1-6ubuntu1

https://launchpad.net/ubuntu/+source/rsnapshot/1.3.1-6ubuntu1/+build/6750119/+files/rsnapshot_1.3.1-6ubuntu1_all.deb

**Comment by xezpeleta** [comment]
I added Ubuntu Rsnapshot deb package in our Elkarbackup repository and I confirm that everything works well now in Debian Jessie with a simple `apt-get update && apt-get upgrade`

Note: you must have elkarbackup repository configured (remember to change to **jessie**): 
```sh
# Elkarbackup repository
deb http://elkarbackup.org/apt/debian jessie main
```

I'll modify the explanation about this bug in the wiki [1] and then I'll close this issue.

1: https://github.com/elkarbackup/elkarbackup/wiki/JessieRsnapshotIssue

**Comment by antton** [comment]
Perfect!

2015-04-28 12:48 GMT+02:00 Xabi <notifications@github.com>:
