### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by Codelica** [elkarbackup/elkarbackup#90]
Hello,

I was running through he Ubuntu installation instructions on:

https://github.com/elkarbackup/elkarbackup/wiki/Installation

which include adding the following:

`deb http://elkarbackup.org/apt/debian trusty main`

But it appears the trusty repo is gone? I get:

`Failed to fetch http://elkarbackup.org/apt/debian/dists/trusty/main/binary-amd64/Packages`

Any insight would be appreciated!

-James

**Comment by xezpeleta** [comment]
Sorry @Codelica , it was a typo. The right line to add in sources.list is this one:

```
deb http://elkarbackup.org/apt/ubuntu trusty main
```

I've just corrected the wiki with the right information. Thanks for reporting!

**Comment by Codelica** [comment]
Thanks, that did the trick!
