### ISSUE TITLE
1.1.3 -> 1.1.4 update problems

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#91]
Hi,

I just updated to 1.1.4 and noticed several things:

- Upgrade put a new /etc/elkarbackup/parameters.yml file with "disable_background: false". Changing this parameter doesn't seem to work, only changing the parameter from within the web GUI worked. This may be because the issue below:

- When trying to change the parameter from GUI, I got a 500 internal error when saving changed parameters. This worked ok after doing a "php app/console cache:clear", I think this should be done by the upgrade script.

Cheers
Eneko

**Comment by xezpeleta** [comment]
The installation/upgrade script (postinst) always executes the "cache:clear" command:

https://github.com/elkarbackup/elkarbackup/blob/3e59ed8215f29cad66b93f9cc3ff3fd132afe4b4/debian/DEBIAN/postinst#L92

When you edit parameters.yml manually, you also have to clean the cache manually:

https://github.com/elkarbackup/elkarbackup/wiki/FAQ#ive-changed-parametersyml-but-it-doesnt-work

The GUI does it everything automatically, so I don't understand why you got the 500 internal error the first time. Maybe some parameter was missing in the file?

**Comment by elacunza** [comment]
I have to update a 3rd elkarbackup installation today, will try to reproduce the problem and will report back.

**Comment by elacunza** [comment]
I have been unable to reproduce this problem on this update. Changing the parameter from the GUI has worked OK, but I have cleaned the cache beforehand trying to fix another problems.

I'm closing this, shall I find the same problem in the future, I will post a new issue.

Thanks
