### ISSUE TITLE
Non-root user permission problem

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#92]
Hi,

I noticed that a non-root user can't access "Config" and "Users" screens. Not sure this is a new issue in 1.1.4 or it was there before.

**Comment by xezpeleta** [comment]
This was already fixed in #32 

Can you try again creating a new user?

Thanks

**Comment by elacunza** [comment]
Sorry, I didn't event recall having filled that bug. I just fixed the role-issue in the database. Thanks a lot.

**Comment by xezpeleta** [comment]
:+1:
