### ISSUE TITLE
imagenes vm con errores crc

### ISSUE THREAD

**Issue by rearjm** [elkarbackup/elkarbackup#93]
Estoy descargandome las imágenes VM de VirtualBox para empezar a probar pero el fichero parece que está corrupto.

tar ztvf elkarbackup64b-1.0.23-ova.tar.gz 
-rw------- xezpeleta/xezpeleta 718205952 2014-07-10 16:37 elkarbackup-vm.ova

gzip: stdin: invalid compressed data--crc error
tar: Child returned status 1
tar: Error is not recoverable: exiting now

¿Podeis volver a generarlo e incluir md5, sha1?
Gracias

**Comment by xezpeleta** [comment]
¿Te pasa lo mismo con la versión 1.1.2?

Más info:
https://github.com/elkarbackup/elkarbackup/wiki/DownloadVirtualMachine

**Comment by rearjm** [comment]
Pues parece que funciona bien la 1.1.2
Gracias

**Comment by xezpeleta** [comment]
Ok! Te recomiendo que una vez en marcha actualices a la última versión
(1.1.4) mediante el comando:

```
apt-get update && apt-get upgrade
```

Hasta luego

2015-06-15 18:26 GMT+02:00 rearjm <notifications@github.com>:
