### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by parreitu** [elkarbackup/elkarbackup#94]
Hace unos meses tuve que migrar de máquina la instalación de Elkarbackup, por lo que hice uso de la BD que se genera automáticamente junto a la copia del repositorio.

La recuperación fué teóricamente correcta, y luego simplemente tuve que volver a enlazarlo con el repositorio de los ficheros.

Ahora me he dado cuenta de que algunos clientes han desaparecido del interfaz web, aunque en la BD siguen existiendo esos registros, y en el repositorio de ficheros siguen existiendo las carpetas, aunque eso si, no se han hecho copias desde entonces.

Si en el navegador escribo a mano la URL http://elkarbackup/client/13 , donde 13 es el código de cliente que sin visualizarse en el interfaz web sigue existiendo en la BD, se muestra su información.

¿ Alguna idea ?

**Comment by parreitu** [comment]
Bueno, siguiendo con la investigación, y como pista, al menos algunas tareas de las que no se ven en el interfaz, se están realizando, aunque también he localizado alguna que no, pero igual es por alguna otra razón.

**Comment by parreitu** [comment]
Confirmado, aunque no se vean los backups se siguen haciendo bien, el que me había despistado estaba fallando por otra razón.

**Comment by xezpeleta** [comment]
¿Has echado un vistazo a la BBDD? ¿Alguna diferencia entre los clientes que aparecen listados y los que no?

**Comment by parreitu** [comment]
No he visto nada raro en la tabla Client, aquí esta el volcado de esta tabla (ocultando IPs)
No aparecen los clientes con id [4,13,14,18,31,33,34,36,37,39]

mysql> select * from Client;
+----+------------------------------+----------+---------------------------------+---------------------+-------+
| id | description                  | isActive | name                            | url                 | quota |
+----+------------------------------+----------+---------------------------------+---------------------+-------+
|  1 | NULL                         |        1 | Cluster                         | root@X.Y.Z.19    |    -1 |
|  2 | NULL                         |        0 | OpenFiler                       | root@X.Y.Z.1     |    -1 |
|  3 | Datu Base zerbitzaria        |        0 | IMH01DB01 (X.Y.Z.49)         | root@X.Y.Z.49    |    -1 |
|  4 | NULL                         |        1 | DB (172.16.1.2)          | root@172.16.1.2     |    -1 |
| 13 | SAGE                         |        1 | Windows2003-02 (X.Y.Z.44)    | X.Y.Z.44:        |    -1 |
| 14 | NULL                         |        1 | FW                       | root@X.Y.Z.35 |    -1 |
| 16 | NULL                         |        1 | Firewall                    | root@X.Y.Z.8     |    -1 |
| 17 | NULL                         |        1 | IkasguneBerria                  | root@X.Y.Z.4   |    -1 |
| 18 | NULL                         |        0 | Wifi zerbitzaria                | root@X.Y.Z.5     |    -1 |
| 19 | NULL                         |        1 | IMH01AUX03                      | X.Y.Z.16:        |    -1 |
| 20 | Zitages                      |        1 | IMH01AUX01 (X.Y.Z.12)        | X.Y.Z.12:        |    -1 |
| 21 | NULL                         |        1 | DMZ-SUBVERSION (X.Y.Z.10)  | root@X.Y.Z.10  |    -1 |
| 22 | NULL                         |        1 | DMZ-Eposta (X.Y.Z.12)      | root@X.Y.Z.12  |    -1 |
| 24 | NULL                         |        1 | DMZ-IMHDEBIAN04 (X.Y.Z.14) | root@X.Y.Z.14  |    -1 |
| 25 | NULL                         |        1 | DMZ-IMHDEBIAN03 (X.Y.Z.16) | root@X.Y.Z.16  |    -1 |
| 26 | NULL                         |        1 | DMZ-IMHDMZ02 (X.Y.Z.7)     | root@X.Y.Z.7   |    -1 |
| 27 | NULL                         |        1 | DMZ-IMHDEBIAN06 (X.Y.Z.17) | root@X.Y.Z.17  |    -1 |
| 28 | NULL                         |        1 | DMZ-XYZ (X.Y.Z.9)      | root@X.Y.Z.9   |    -1 |
| 29 | NULL                         |        1 | DMZ-PERIMETRALA X.Y.Z.3)   | root@X.Y.Z.3   |    -1 |
| 30 | NULL                         |        0 | DMZ-IMHDMZ01 (X.Y.Z.2)     | root@X.Y.Z.2   |    -1 |
| 31 | NULL                         |        1 | Web (X.Y.Z.37)     | root@X.Y.Z.37 |    -1 |
| 32 | NULL                         |        1 | IMH01BIRT01 (X.Y.Z.43)       | root@X.Y.Z.43    |    -1 |
| 33 | NULL                         |        1 | PROXMOX03 (X.Y.Z.4)          | root@X.Y.Z.4     |    -1 |
| 34 | NULL                         |        1 | PROXMOX02 (X.Y.Z.2)          | root@X.Y.Z.2     |    -1 |
| 35 | NULL                         |        1 | IMH01BIRT05 (X.Y.Z.7)        | root@X.Y.Z.7     |    -1 |
| 36 | NULL                         |        1 | PROXMOX01 (X.Y.Z.13)         | root@X.Y.Z.13    |    -1 |
| 37 | NULL                         |        1 | localhost (elkarbackup)         | root@X.Y.Z.1     |    -1 |
| 38 | NULL                         |        1 | ANTIBIRUSA02 (X.Y.Z.58)      | X.Y.Z.58:        |    -1 |
| 39 | W7 bezero bat probak egiteko |        0 | Windows7 Bezeroa                | 10.23.38.162:       |    -1 |
| 40 | NULL                         |        1 | EkonOpenSuse                    | root@X.Y.Z.28    |    -1 |
| 41 | NULL                         |        1 | DMZ-IMHDEBIAN07 (X.Y.Z.18) | root@X.Y.Z.18  |    -1 |
| 42 | NULL                         |        1 | ARE3 (X.Y.Z.59)              | X.Y.Z.59:        |    -1 |
| 43 | Datu Base zerbitzaria        |        1 | IMH01DB02                       | root@X.Y.Z.50    |    -1 |
+----+------------------------------+----------+---------------------------------+---------------------+-------+
33 rows in set (0.00 sec)

**Comment by parreitu** [comment]
Al utilizar el modelo vista-controlador en el código no hay una query que pueda probar para ver cual es el problema ...., pero por alguna razón no está mostrando todos los registros de la tabla ...

**Comment by xezpeleta** [comment]
Los logs devuelven algún error?

2015-07-14 22:27 GMT+02:00 Pedro Arreitunandia <notifications@github.com>:

**Comment by parreitu** [comment]
No, no veo nada en los logs.

Los que habéis trabajado con Simphony, ¿ sabéis si se puede activar algún modo debug que muestre las sentencias SQL que va generando en tiempo real ?

**Comment by blaskurain** [comment]
Yo [activaría el general_log de MySQL](http://dev.mysql.com/doc/refman/5.5/en/query-log.html) para ver qué consultas llegan a la base de datos.

**Comment by elacunza** [comment]
Peio, otra prueba simple que puedes hacer es, en la pantalla de listado 
de clientes, sacar la ventana de código fuente de la página del 
navegador, y ver si en el código fuente están esos clientes que faltan, 
por si es un problema de visualización.

-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by parreitu** [comment]
Aupa !!

Con la prueba propuesta por @elacunza no se ve nada especial, los clientes que faltan tampoco están en el código, pero con la idea de @blaskurain creo que he encontrado la causa.

He activado el general_log y he capturado las sentencias SQL que se ejecutan al mostrar la página de clientes. Con la primera veo que encuentra los 33 clientes que tengo dados de alta

```
mysql> SELECT count(DISTINCT c0_.id) AS sclr0 FROM Client c0_;
+-------+
| sclr0 |
+-------+
|    33 |
+-------+
1 row in set (0.00 sec)
```
Posteriormente obtiene los códigos de los clientes limitando el resultado a 20. Como podeís observar, no los muestra ordenados

```
mysql> SELECT DISTINCT c0_.id AS id0 FROM Client c0_ LIMIT 20 OFFSET 0;
+-----+
| id0 |
+-----+
|  38 |
|  42 |
|   1 |
|  28 |
|  22 |
|  25 |
|  24 |
|  27 |
|  41 |
|  30 |
|  26 |
|  29 |
|  21 |
|  40 |
|  16 |
|  17 |
|  20 |
|  19 |
|  32 |
|  35 |
+-----+
20 rows in set (0.00 sec)
```
Y posteriormente obtiene el resto de campos necesarios para la tabla, solamente para esos 20 códigos de cliente

```
SELECT c0_.description AS description0, c0_.id AS id1, c0_.isActive AS isActive2, c0_.name AS name3, c0_.url AS url4, c0_.quota AS quota5 FROM Client c0_ WHERE c0_.id IN ('38', '42', '1', '28', '22', '25', '24', '27', '41', '30', '26', '29', '21', '40', '16', '17', '20', '19', '32', '35')
```

Lo curioso es que si ejecuto la misma consulta pero quitando el límite de 20, al final de la lista aparecen los clientes que han desaparecido en mi vista de clientes, los que van del 37 al 31

```
mysql> SELECT  c0_.id AS id0 FROM Client c0_ ;
+-----+
| id0 |
+-----+
|  38 |
|  42 |
|   1 |
|  28 |
|  22 |
|  25 |
|  24 |
|  27 |
|  41 |
|  30 |
|  26 |
|  29 |
|  21 |
|  40 |
|  16 |
|  17 |
|  20 |
|  19 |
|  32 |
|  35 |
|   3 |
|  43 |
|  37 |
|   2 |
|  36 |
|  34 |
|  33 |
|  18 |
|  13 |
|  39 |
|   4 |
|  14 |
|  31 |
+-----+
33 rows in set (0.00 sec)

```
20 es el número de filas a mostrar en cada página que he configurado en la sección de parámetros. Si cambio ese valor y pongo uno >33, todos los clientes se muestran sin problemas y correctamente ordenados. 

Si pongo uno más pequeño, por ejemplo 10, me lo divide en 4 páginas y me muestra en cada página estos clientes, como veis algunos de ellos aparecen en varias de las páginas y con un orden incorrecto.

Página 1
=======
 Cliente 1
Cliente 22
Cliente 24
Cliente 25
Cliente 27
Cliente 28
Cliente 30
Cliente 38
Cliente 41
Cliente 42

Página 2
=======
 Cliente 16
Cliente 17
Cliente 19
Cliente 20
Cliente 21
Cliente 26
Cliente 29
Cliente 32
Cliente 35
Cliente 40

Página 3
=======

 Cliente 2
Cliente 3
Cliente 13
Cliente 33
Cliente 34
Cliente 36
Cliente 37
Cliente 39
Cliente 43

Página 4
========

 Cliente 41
Cliente 42
Cliente 43


¿Podriais probar si este comportamiento se repite en vuestras instalaciones ?

**Comment by xezpeleta** [comment]
Efectivamente, parece que la paginación no está funcionando correctamente. Lo marco como bug.

**Comment by xezpeleta** [comment]
¿Alguien más puede confirmar este problema?

Estoy intentando reproducir este error en un entorno de pruebas con una instalación limpia y aparentemente funciona correctamente

**Comment by xezpeleta** [comment]
He añadido un `ORDER BY` que debería solucionar este bug.

@parreitu : ¿Puedes comprobar que funciona en tu instalación?

Hay que sustitutir una línea en `src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
`:

https://github.com/elkarbackup/elkarbackup/commit/9ed763c2d4ae0c00159336687d16cce3458fc20b#diff-2c3b737cf716ad17c76613557c3cdc58R829

**Comment by parreitu** [comment]
Aupa !!

Acabo de hacer el cambio y tiene buena pinta, aunque mañana lo miraré más a
fondo para asegurarme de que están todos los clientes. Lo dicho, en un
primer vistazo tiene buena pinta.

Eskerrik asko !!



2015-09-12 9:25 GMT+02:00 Xabi <notifications@github.com>:

**Comment by xezpeleta** [comment]
This bug should be fixed in the new version 1.1.5 @parreitu 

Thanks!

**Comment by parreitu** [comment]
With his patch the problem in solved in my server.

:-)
