### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by icex** [elkarbackup/elkarbackup#95]
Maybe I'm doing it wrong, but it looks like the generated rsnapshot config does not exclude properly the specified paths. I've tinkered with it a bit and it seems that it works ONLY without quotes.

root@backup:~# diff rsnapshot.2_2.cfg rsnapshot.2_2.cfg-orig
155,157c155
< exclude	public_html/
---
> exclude	'public_html/'

I'm running the latest ubuntu 14.04 , rsnapshot 1.3.1, rsync  version 3.1.0  protocol version 31.

**Comment by xezpeleta** [comment]
Thanks, I will take a look

**Comment by xezpeleta** [comment]
It looks that patch added in #25 it's causing this issue. We should revert the changes, and avoid the quotes in exclude/include sections.

**Comment by xezpeleta** [comment]
The fix will be available in the next version (1.1.5) @icex

**Comment by xezpeleta** [comment]
This bug should be fixed in the new version 1.1.5 @icex 

Thanks!
