### ISSUE TITLE
Lanzar pre-scripts en Windows

### ISSUE THREAD

**Issue by asierph** [elkarbackup/elkarbackup#96]
Buenos días, estoy instalando ElkarBackup en la empresa en la que trabajo actualmente y me he encontrado con un problemilla.
La mayoría por no decir todos los clientes trabajan bajo windows y casi todos ellos trabajan con outlook. Necesito hacer un backup de la carpeta de outlook pero para que se realice correctamente es necesario para el servicio. Tengo el comando para cmd que cierra este proceso pero creo que los scripts que se configuran se lanzan en el servidor, y en caso que se puedan lanzar en cliente sera mediante bash.
¿Alguna solución o algo que pueda utilizar para solucionar este problema?
Muchas gracias de antemano, muy buen trabajo con elkarbackup.

**Comment by xezpeleta** [comment]
Efectivamente los scripts se ejecutan en el servidor. Si sabes como parar el servicio de Outlook mediante un comando, tendrías que ejecutar esa a través de SSH en el servidor. A modo de resumen:

- Instalas un servidor SSH en Windows (Cygwin)
- Pruebas a conectarte desde el servidor de Elkarbackup al cliente por SSH y ejecutar el comando para parar el Outlook. Si funciona, tiene buena pinta.
- Creas un script que se conecte al cliente desde el servior y ejecute ese comando. Lo ejecutas antes de cada copia.

Buena suerte

**Comment by xezpeleta** [comment]
Cierro la incidencia, al tratarse de una pregunta.
