### ISSUE TITLE
Instalar Elkarbackup en Debian 8 (contenedor de proxmox)

### ISSUE THREAD

**Issue by csanchez8** [elkarbackup/elkarbackup#99]
Hola, ¿os ha pasado que al instalar Elkarbackup desde el paquete DEB en un Debian 8 (contenedor de proxmox 4.0) os ha dado este error el autofs?

```
apache2_invoke: Enable module rewrite
[ ok ] Restarting web server: apache2.
apache2_invoke: Enable configuration elkarbackup
[ ok ] Reloading web server: apache2.
apache2_invoke: Enable site elkarbackup
[ ok ] Reloading web server: apache2.
[ ok ] Reloading web server: apache2.
Errors were encountered while processing:
 autofs
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up autofs (5.0.8-2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
[....] Starting automount.../usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
failed (no valid automount entries defined.).
invoke-rc.d: initscript autofs, action "start" failed.
dpkg: error processing package autofs (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 autofs
```

Gran trabajo el de este equipo de Elkarbakup !!

**Comment by antton** [comment]
Kaixo,

Por lo que he podido ver puede que tus problemas vengan del contenedor de proxmox y Jessie, la versión del Kernel en la que vive esa Jessie es de una RedHat si mal no me he informado 2.6.32, es un kernel que da problemas con sistemas que funcionan con systemd. Por tanto, puedes probar a montar una maquina con KVM en vez de utilizar un container de OpenVZ?

He visto que OpenVZ esta a punto de desaparecer a nivel de proxmox para pasar al uso de LXC pero bueno todo esto no te lo puedo afirmar.

Por otra parte he visto que podemos tener también problemas de este tipo en contenedores de tipo docker pero eso ya lo iremos probando.

Si nos confirmas que te funciona con una instalación en maquina 'real' ;) te lo agradecemos.

Ya nos contaras, geroarte Carlos!

**Comment by xezpeleta** [comment]
Kaixo Carlos,

Tal como apunta Antton, esto podría tener relación con el contenedor LXC
que utiliza Proxmox 4.0 En una Debian 8 (Jessie) sobre una VM normal la
instalación de autofs se hace sin problemas.

Por cierto, autofs no es una dependencia imprescindible para Elkarbackup.
También lo podrías omitir si quisieras.

Agur

2015-10-07 19:05 GMT+02:00 Antton Rodriguez <notifications@github.com>:

**Comment by xezpeleta** [comment]
Si todavía tienes interés en mantener tu instalación en un container LXC, prueba con esto:

https://www.debian.org/releases/stable/i386/release-notes/ch-information.en.html#issues-lxc-jessie-host

**Comment by antton** [comment]
Puedes pegarnos lo que te dice el sistema con lo siguiente:

modinfo autofs4

**Comment by csanchez8** [comment]
Efectivamente en Proxmox 4.0 ya han cambiado de OpenVZ a LXC.

He probado con los cambios que proponen en https://www.debian.org/releases/stable/i386/release-notes/ch-information.en.html#issues-lxc-jessie-host de modificar el fichero CONFIG del contenedor en /var/lib/lxc/CONTAINER_NAME/config añadiendo los siguientes parámetros
```
lxc.autodev = 1
lxc.kmsg = 0
```
pero sigue dando el error
```
root@ELKARBAKUP:~# aptitude install autofs            
The following partially installed packages will be configured:
  autofs 
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
Setting up autofs (5.0.8-2) ...          
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
[....] Starting automount.../usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
failed (no valid automount entries defined.).
invoke-rc.d: initscript autofs, action "start" failed.
dpkg: error processing package autofs (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 autofs
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up autofs (5.0.8-2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
[....] Starting automount.../usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
failed (no valid automount entries defined.).
invoke-rc.d: initscript autofs, action "start" failed.
dpkg: error processing package autofs (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 autos
```
De todas formas esto es para que al pinchar algo a los puertos USB lo monte automáticamente ¿no?
Si que tengo pensado pincharle un disco externo de 2TB.

Voy a probar en una máquina KVM a ver si va correcto.

Muchas gracias por la rápida respuesta ;-)

**Comment by csanchez8** [comment]
Por si le puede servir a alguien.
Para montar un HDD externo en un Container LXC en PROXMOX 4.0

Objetivo: montar un HDD externo que tenemos pinchado al servidor Proxmox y que se vea desde el contenedor LXC.

Formatear y montar el disco en el HOST
Conectamos el HDD externo al puerto USB
Desde proxmox (hosts) lo formateamos
Para ver el nombre del disco /dev/xxxxx
#fdisk -l
en nuestro caso le ha asignado /dev/sda

formaremos el disco externo
#fdisk /dev/sda
#p (ver las particiones)
#d  (borrar partición, así repetimos con todas las que tenga)
#n (crear una nueva partición) dejamos los sectores por defecto
#w (salir y guardar los cambios)

Darle formato
#mount (para ver el disco)
#mkfs.ext4 /dev/sda1

Montarlo
#mkdir /media/elkarbackup
#mount /dev/sda1 /media/elkarbackup

Dejar montaje permanente
#blkid (para ver el ID del HD)
#nano /etc/fstab
añadimos la línea
UUID=26d8d2fd-1a6f-4ef6-8d04-bc167c12eb05 /media/elkarbackup ext4 errors=remount-ro 0 1

reiniciamos el servidor para ver si lo monta al inicio
#df -h
y vemos que está montado correctamente


Montar el HDD del HOST en el CONTAINER (Bind mounts inside the container)

Modificar el fichero de configuración de la máquina LXC
Le añadimos la línea del fichero de configuración (le quitamos la que tiene que la añadiremos a ese fichero elkarbackup.conf)
root@pxm01:/var/lib/lxc/100# more config
lxc.arch = amd64
lxc.include = /usr/share/lxc/config/elkarbackup.conf
lxc.tty = 2
lxc.environment = TERM=linux
lxc.utsname = ELKARBAKUP
lxc.cgroup.memory.limit_in_bytes = 4294967296
lxc.cgroup.memory.memsw.limit_in_bytes = 4831838208
lxc.cgroup.cpu.cfs_period_us = 100000
lxc.cgroup.cpu.cfs_quota_us = 400000
lxc.cgroup.cpu.shares = 1024
lxc.rootfs = loop:/var/lib/vz/images/100/vm-100-disk-1.raw
lxc.network.type = veth
lxc.network.veth.pair = veth100i0
lxc.network.hwaddr = 62:D8:F

Aquí dejamos el fichero de configuración del container
root@pxm01:/var/lib/lxc/100# nano /usr/share/lxc/config/elkarbackup.conf 
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.loglevel = 1
lxc.logfile = /var/lib/lxc/100/100.log
lxc.autodev = 1
lxc.kmsg = 0
lxc.mount.entry = /media/elkarbackup backups none bind,create=dir 0 0

NOTA: cuidado porque el fichero de configuración /var/lib/lxc/100/config el servidor proxmox al apagar desde CONSOLA WEB el contenedor LXC lo vuelve a dejar como estaba originalmente.

**Comment by csanchez8** [comment]
Al final no he probado a montar en una KVM

**Comment by xezpeleta** [comment]
Eskerrik asko Carlos!

No lo he probado (todavía no tengo el PVE 4.0), pero se supone que esto
mismo se podría hacer con:

lxc-device add -n 100 /dev/sda1

Tendría la misma desventaja que tu opción; al apagar habría que volver a
repetirlo.

Para evitar eso, se supone que existe otra opción, editando el fichero
pct.conf:
http://forum.proxmox.com/threads/23256-LXC-Cannot-assign-a-block-device-to-container



2015-10-09 13:34 GMT+02:00 Carlos <notifications@github.com>:

**Comment by csanchez8** [comment]
Probado a instalar en una maquina KVM con Proxmox 4.0 y no da el error de "autofs" que daba con un contenedor LXC.

**Comment by csanchez8** [comment]
Para conectar el HDD Externo (USB) a la MV Guest de Elkarbackup en un Proxmox 4.0 he realizado estos pasos, por si le puede servir a alguien, (luego seguro que Xabi nos dará una solución mejor) ;-)

```
Desde el HOST, para ver en qué puerto USB está conectado
#lsusb -t
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=uhci_hcd/2p, 12M
    |__ Port 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 1: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 12M
        |__ Port 3: Dev 4, If 0, Class=Mass Storage, Driver=usb-storage, 12M  --> el que nos interesa
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/4p, 480M

Añadir en el fichero /etc/pve/qemu-server/<VM_ID>.conf
usb0: host=3-1.3   → que corresponde al disco externo

Parar y arrancar la MV

Montar el HDD
Para saber el UUID del HDD Externo
root@BACKUPS:~# blkid
/dev/vda1: UUID="8e600cd1-45aa-4ed6-97ac-e60840ae69aa" TYPE="ext4" PARTUUID="0cc03104-01"
/dev/vda5: UUID="4002488c-1794-4d75-b3d5-ad04cfb21793" TYPE="swap" PARTUUID="0cc03104-05"
/dev/sr0: UUID="2015-09-06-11-12-07-00" LABEL="Debian 8.2.0 amd64 1" TYPE="iso9660" PTUUID="7714c637" PTTYPE="dos"
/dev/sda1: UUID="26d8d2fd-1a6f-4ef6-8d04-bc167c12eb05" TYPE="ext4" PARTUUID="8f8f4890-7d65-4623-966b-7f77d5ba48f7"

Dejar el montaje permanente en la MV
root@BACKUPS:~# more /etc/fstab 
#add line
UUID=26d8d2fd-1a6f-4ef6-8d04-bc167c12eb05 /backups ext4 errors=remount-ro 0 1

```

**Comment by elacunza** [comment]
Kaixo Carlos,

Que yo conozca es la solución. El problema que tiene es que es manual :) 
pero bueno. Si quieres rotar el disco es un poco engorro :)

Hay que tener en cuenta que si desconectamos el disco la VM no arrancará 
hasta quitar la línea usb0 del .conf.

Otra posibilidad quizá pudiera ser exportar el disco USB por NFS a la 
VM, así el control sobre el disco USB lo tienes por completo en el 
hypervisor, no repartido entre dos VMs. También te permitiría mover la 
VM de hypervisor físico.

Saludos
Eneko

El 15/10/15 a las 08:24, Carlos escribió:
>
> Para conectar el HDD Externo (USB) a la MV Guest de Elkarbackup en un 
> Proxmox 4.0 he realizado estos pasos, por si le puede servir a 
> alguien, (luego seguro que Xabi nos dará una solución mejor) ;-)
>
> |Desde el HOST, para ver en qué puerto USB está conectado #lsusb -t /: 
> Bus 04.Port 1: Dev 1, Class=root_hub, Driver=uhci_hcd/2p, 12M |__ Port 
> 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M |__ 
> Port 1: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M 
> /: Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M |__ 
> Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 12M |__ Port 3: Dev 4, 
> If 0, Class=Mass Storage, Driver=usb-storage, 12M --> el que nos 
> interesa /: Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 
> 12M /: Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/4p, 480M 
> Añadir en el fichero /etc/pve/qemu-server/<VM_ID>.conf usb0: 
> host=3-1.3 → que corresponde al disco externo Parar y arrancar la MV 
> Montar el HDD Para saber el UUID del HDD Externo root@BACKUPS:~# blkid 
> /dev/vda1: UUID="8e600cd1-45aa-4ed6-97ac-e60840ae69aa" TYPE="ext4" 
> PARTUUID="0cc03104-01" /dev/vda5: 
> UUID="4002488c-1794-4d75-b3d5-ad04cfb21793" TYPE="swap" 
> PARTUUID="0cc03104-05" /dev/sr0: UUID="2015-09-06-11-12-07-00" 
> LABEL="Debian 8.2.0 amd64 1" TYPE="iso9660" PTUUID="7714c637" 
> PTTYPE="dos" /dev/sda1: UUID="26d8d2fd-1a6f-4ef6-8d04-bc167c12eb05" 
> TYPE="ext4" PARTUUID="8f8f4890-7d65-4623-966b-7f77d5ba48f7" Dejar el 
> montaje permanente en la MV root@BACKUPS:~# more /etc/fstab #add line 
> UUID=26d8d2fd-1a6f-4ef6-8d04-bc167c12eb05 /backups ext4 
> errors=remount-ro 0 1 |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/99#issuecomment-148293540>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by csanchez8** [comment]
Al final voy a montar un NAS (¿alguna recomendación?) con los discos que tenga por aquí de sobra y exportar como NFS para Elkarbackup y para los backups de proxmox.
Gracias por todo !!

**Comment by antton** [comment]
Yo siento curiosidad con el OpenMediaVault pero no lo se, que dice la
gente? FreeNAS? Resulta que Volker es el creador de FreeNAS y es el creador
de OpenMediaVault (NAS basado en Debian)

Ya nos contaras algo con tu nueva aventura ;)

Geroarte!

**Comment by elacunza** [comment]
Yo la verdad es que para dar servicio NFS no me complicaría la vida, 
Debian + nfs-kernel-server y a correr, se pone en marcha en un plis. :)

El 16/10/15 a las 09:12, Antton Rodriguez escribió:
> Yo siento curiosidad con el OpenMediaVault pero no lo se, que dice la
> gente? FreeNAS? Resulta que Volker es el creador de FreeNAS y es el 
> creador
> de OpenMediaVault (NAS basado en Debian)
>
> Ya nos contaras algo con tu nueva aventura ;)
>
> Geroarte!
>
> El 16 de octubre de 2015, 9:09, Carlos <notifications@github.com> 
> escribió:
>
> > Al final voy a montar un NAS (¿alguna recomendación?) con los discos que
> > tenga por aquí de sobra y exportar como NFS para Elkarbackup y para los
> > backups de proxmox.
> > Gracias por todo !!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/elkarbackup/elkarbackup/issues/99#issuecomment-148634091>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elkarbackup/elkarbackup/issues/99#issuecomment-148634433>.
>


-- 
Zuzendari Teknikoa / Director Técnico
Binovo IT Human Project, S.L.
Telf. 943575997
       943493611
Astigarraga bidea 2, planta 6 dcha., ofi. 3-2; 20180 Oiartzun (Gipuzkoa)
www.binovo.es

**Comment by csanchez8** [comment]
Al final voy a poner este equipo con 3x2Tb (Raid 5) y mediante iScsi me conecto al volumen.
